// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.23.1
// source: lsp/youtube/youtube.proto

package youtube

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VideoStatus int32

const (
	VideoStatus_Waiting VideoStatus = 0
	VideoStatus_Living  VideoStatus = 1
	VideoStatus_Upload  VideoStatus = 2
)

// Enum value maps for VideoStatus.
var (
	VideoStatus_name = map[int32]string{
		0: "Waiting",
		1: "Living",
		2: "Upload",
	}
	VideoStatus_value = map[string]int32{
		"Waiting": 0,
		"Living":  1,
		"Upload":  2,
	}
)

func (x VideoStatus) Enum() *VideoStatus {
	p := new(VideoStatus)
	*p = x
	return p
}

func (x VideoStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VideoStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_lsp_youtube_youtube_proto_enumTypes[0].Descriptor()
}

func (VideoStatus) Type() protoreflect.EnumType {
	return &file_lsp_youtube_youtube_proto_enumTypes[0]
}

func (x VideoStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VideoStatus.Descriptor instead.
func (VideoStatus) EnumDescriptor() ([]byte, []int) {
	return file_lsp_youtube_youtube_proto_rawDescGZIP(), []int{0}
}

type VideoType int32

const (
	VideoType_FirstLive VideoType = 0
	VideoType_Live      VideoType = 1
	VideoType_Video     VideoType = 2
)

// Enum value maps for VideoType.
var (
	VideoType_name = map[int32]string{
		0: "FirstLive",
		1: "Live",
		2: "Video",
	}
	VideoType_value = map[string]int32{
		"FirstLive": 0,
		"Live":      1,
		"Video":     2,
	}
)

func (x VideoType) Enum() *VideoType {
	p := new(VideoType)
	*p = x
	return p
}

func (x VideoType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VideoType) Descriptor() protoreflect.EnumDescriptor {
	return file_lsp_youtube_youtube_proto_enumTypes[1].Descriptor()
}

func (VideoType) Type() protoreflect.EnumType {
	return &file_lsp_youtube_youtube_proto_enumTypes[1]
}

func (x VideoType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VideoType.Descriptor instead.
func (VideoType) EnumDescriptor() ([]byte, []int) {
	return file_lsp_youtube_youtube_proto_rawDescGZIP(), []int{1}
}

var File_lsp_youtube_youtube_proto protoreflect.FileDescriptor

var file_lsp_youtube_youtube_proto_rawDesc = []byte{
	0x0a, 0x19, 0x6c, 0x73, 0x70, 0x2f, 0x79, 0x6f, 0x75, 0x74, 0x75, 0x62, 0x65, 0x2f, 0x79, 0x6f,
	0x75, 0x74, 0x75, 0x62, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x79, 0x6f, 0x75,
	0x74, 0x75, 0x62, 0x65, 0x2a, 0x32, 0x0a, 0x0b, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x57, 0x61, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x10, 0x00,
	0x12, 0x0a, 0x0a, 0x06, 0x4c, 0x69, 0x76, 0x69, 0x6e, 0x67, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x10, 0x02, 0x2a, 0x2f, 0x0a, 0x09, 0x56, 0x69, 0x64, 0x65,
	0x6f, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x46, 0x69, 0x72, 0x73, 0x74, 0x4c, 0x69,
	0x76, 0x65, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4c, 0x69, 0x76, 0x65, 0x10, 0x01, 0x12, 0x09,
	0x0a, 0x05, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x10, 0x02, 0x42, 0x0d, 0x5a, 0x0b, 0x6c, 0x73, 0x70,
	0x2f, 0x79, 0x6f, 0x75, 0x74, 0x75, 0x62, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lsp_youtube_youtube_proto_rawDescOnce sync.Once
	file_lsp_youtube_youtube_proto_rawDescData = file_lsp_youtube_youtube_proto_rawDesc
)

func file_lsp_youtube_youtube_proto_rawDescGZIP() []byte {
	file_lsp_youtube_youtube_proto_rawDescOnce.Do(func() {
		file_lsp_youtube_youtube_proto_rawDescData = protoimpl.X.CompressGZIP(file_lsp_youtube_youtube_proto_rawDescData)
	})
	return file_lsp_youtube_youtube_proto_rawDescData
}

var file_lsp_youtube_youtube_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_lsp_youtube_youtube_proto_goTypes = []interface{}{
	(VideoStatus)(0), // 0: youtube.VideoStatus
	(VideoType)(0),   // 1: youtube.VideoType
}
var file_lsp_youtube_youtube_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lsp_youtube_youtube_proto_init() }
func file_lsp_youtube_youtube_proto_init() {
	if File_lsp_youtube_youtube_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lsp_youtube_youtube_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lsp_youtube_youtube_proto_goTypes,
		DependencyIndexes: file_lsp_youtube_youtube_proto_depIdxs,
		EnumInfos:         file_lsp_youtube_youtube_proto_enumTypes,
	}.Build()
	File_lsp_youtube_youtube_proto = out.File
	file_lsp_youtube_youtube_proto_rawDesc = nil
	file_lsp_youtube_youtube_proto_goTypes = nil
	file_lsp_youtube_youtube_proto_depIdxs = nil
}
