// Code generated by protoc-gen-go. DO NOT EDIT.
// source: weibo.proto

package weibo

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GenVisitorResponse struct {
	Retcode              int64                    `protobuf:"varint,1,opt,name=retcode,proto3" json:"retcode,omitempty"`
	Msg                  string                   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 *GenVisitorResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *GenVisitorResponse) Reset()         { *m = GenVisitorResponse{} }
func (m *GenVisitorResponse) String() string { return proto.CompactTextString(m) }
func (*GenVisitorResponse) ProtoMessage()    {}
func (*GenVisitorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4102e518bff17504, []int{0}
}

func (m *GenVisitorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenVisitorResponse.Unmarshal(m, b)
}
func (m *GenVisitorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenVisitorResponse.Marshal(b, m, deterministic)
}
func (m *GenVisitorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenVisitorResponse.Merge(m, src)
}
func (m *GenVisitorResponse) XXX_Size() int {
	return xxx_messageInfo_GenVisitorResponse.Size(m)
}
func (m *GenVisitorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenVisitorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenVisitorResponse proto.InternalMessageInfo

func (m *GenVisitorResponse) GetRetcode() int64 {
	if m != nil {
		return m.Retcode
	}
	return 0
}

func (m *GenVisitorResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *GenVisitorResponse) GetData() *GenVisitorResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type GenVisitorResponse_Data struct {
	Tid                  string   `protobuf:"bytes,1,opt,name=tid,proto3" json:"tid,omitempty"`
	NewTid               bool     `protobuf:"varint,2,opt,name=new_tid,json=newTid,proto3" json:"new_tid,omitempty"`
	Confidence           int32    `protobuf:"varint,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenVisitorResponse_Data) Reset()         { *m = GenVisitorResponse_Data{} }
func (m *GenVisitorResponse_Data) String() string { return proto.CompactTextString(m) }
func (*GenVisitorResponse_Data) ProtoMessage()    {}
func (*GenVisitorResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_4102e518bff17504, []int{0, 0}
}

func (m *GenVisitorResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenVisitorResponse_Data.Unmarshal(m, b)
}
func (m *GenVisitorResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenVisitorResponse_Data.Marshal(b, m, deterministic)
}
func (m *GenVisitorResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenVisitorResponse_Data.Merge(m, src)
}
func (m *GenVisitorResponse_Data) XXX_Size() int {
	return xxx_messageInfo_GenVisitorResponse_Data.Size(m)
}
func (m *GenVisitorResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_GenVisitorResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_GenVisitorResponse_Data proto.InternalMessageInfo

func (m *GenVisitorResponse_Data) GetTid() string {
	if m != nil {
		return m.Tid
	}
	return ""
}

func (m *GenVisitorResponse_Data) GetNewTid() bool {
	if m != nil {
		return m.NewTid
	}
	return false
}

func (m *GenVisitorResponse_Data) GetConfidence() int32 {
	if m != nil {
		return m.Confidence
	}
	return 0
}

type VisitorIncarnateResponse struct {
	Retcode              int64                          `protobuf:"varint,1,opt,name=retcode,proto3" json:"retcode,omitempty"`
	Msg                  string                         `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 *VisitorIncarnateResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *VisitorIncarnateResponse) Reset()         { *m = VisitorIncarnateResponse{} }
func (m *VisitorIncarnateResponse) String() string { return proto.CompactTextString(m) }
func (*VisitorIncarnateResponse) ProtoMessage()    {}
func (*VisitorIncarnateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4102e518bff17504, []int{1}
}

func (m *VisitorIncarnateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VisitorIncarnateResponse.Unmarshal(m, b)
}
func (m *VisitorIncarnateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VisitorIncarnateResponse.Marshal(b, m, deterministic)
}
func (m *VisitorIncarnateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VisitorIncarnateResponse.Merge(m, src)
}
func (m *VisitorIncarnateResponse) XXX_Size() int {
	return xxx_messageInfo_VisitorIncarnateResponse.Size(m)
}
func (m *VisitorIncarnateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VisitorIncarnateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VisitorIncarnateResponse proto.InternalMessageInfo

func (m *VisitorIncarnateResponse) GetRetcode() int64 {
	if m != nil {
		return m.Retcode
	}
	return 0
}

func (m *VisitorIncarnateResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *VisitorIncarnateResponse) GetData() *VisitorIncarnateResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type VisitorIncarnateResponse_Data struct {
	Sub                  string   `protobuf:"bytes,1,opt,name=sub,proto3" json:"sub,omitempty"`
	Subp                 string   `protobuf:"bytes,2,opt,name=subp,proto3" json:"subp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VisitorIncarnateResponse_Data) Reset()         { *m = VisitorIncarnateResponse_Data{} }
func (m *VisitorIncarnateResponse_Data) String() string { return proto.CompactTextString(m) }
func (*VisitorIncarnateResponse_Data) ProtoMessage()    {}
func (*VisitorIncarnateResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_4102e518bff17504, []int{1, 0}
}

func (m *VisitorIncarnateResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VisitorIncarnateResponse_Data.Unmarshal(m, b)
}
func (m *VisitorIncarnateResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VisitorIncarnateResponse_Data.Marshal(b, m, deterministic)
}
func (m *VisitorIncarnateResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VisitorIncarnateResponse_Data.Merge(m, src)
}
func (m *VisitorIncarnateResponse_Data) XXX_Size() int {
	return xxx_messageInfo_VisitorIncarnateResponse_Data.Size(m)
}
func (m *VisitorIncarnateResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_VisitorIncarnateResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_VisitorIncarnateResponse_Data proto.InternalMessageInfo

func (m *VisitorIncarnateResponse_Data) GetSub() string {
	if m != nil {
		return m.Sub
	}
	return ""
}

func (m *VisitorIncarnateResponse_Data) GetSubp() string {
	if m != nil {
		return m.Subp
	}
	return ""
}

func init() {
	proto.RegisterType((*GenVisitorResponse)(nil), "weibo.GenVisitorResponse")
	proto.RegisterType((*GenVisitorResponse_Data)(nil), "weibo.GenVisitorResponse.Data")
	proto.RegisterType((*VisitorIncarnateResponse)(nil), "weibo.VisitorIncarnateResponse")
	proto.RegisterType((*VisitorIncarnateResponse_Data)(nil), "weibo.VisitorIncarnateResponse.Data")
}

func init() {
	proto.RegisterFile("weibo.proto", fileDescriptor_4102e518bff17504)
}

var fileDescriptor_4102e518bff17504 = []byte{
	// 247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0x31, 0x4b, 0xc4, 0x30,
	0x18, 0x86, 0x89, 0xed, 0x5d, 0xbd, 0xef, 0x16, 0xf9, 0x16, 0x83, 0xc3, 0x51, 0x0e, 0x87, 0x0e,
	0xd2, 0xe1, 0x5c, 0x9c, 0x45, 0x10, 0x47, 0x83, 0x38, 0xb8, 0x48, 0xd2, 0x7c, 0x4a, 0x06, 0x93,
	0x92, 0xa4, 0xf4, 0x5f, 0xf9, 0x37, 0xfc, 0x5b, 0x92, 0x5c, 0x0f, 0x2b, 0xe2, 0x72, 0xdb, 0xfb,
	0x86, 0xf0, 0x3e, 0x3c, 0x7c, 0xb0, 0x1e, 0xc9, 0x28, 0xd7, 0xf6, 0xde, 0x45, 0x87, 0x8b, 0x5c,
	0xb6, 0x5f, 0x0c, 0xf0, 0x9e, 0xec, 0xb3, 0x09, 0x26, 0x3a, 0x2f, 0x28, 0xf4, 0xce, 0x06, 0x42,
	0x0e, 0x95, 0xa7, 0xd8, 0x39, 0x4d, 0x9c, 0xd5, 0xac, 0x29, 0xc4, 0xa1, 0xe2, 0x19, 0x14, 0x1f,
	0xe1, 0x9d, 0x9f, 0xd4, 0xac, 0x59, 0x89, 0x14, 0x71, 0x07, 0xa5, 0x96, 0x51, 0xf2, 0xa2, 0x66,
	0xcd, 0x7a, 0xb7, 0x69, 0xf7, 0x94, 0xbf, 0xa3, 0xed, 0x9d, 0x8c, 0x52, 0xe4, 0xbf, 0x17, 0x8f,
	0x50, 0xa6, 0x96, 0xd6, 0xa2, 0xd1, 0x99, 0xb1, 0x12, 0x29, 0xe2, 0x39, 0x54, 0x96, 0xc6, 0xd7,
	0xf4, 0x9a, 0x18, 0xa7, 0x62, 0x69, 0x69, 0x7c, 0x32, 0x1a, 0x37, 0x00, 0x9d, 0xb3, 0x6f, 0x46,
	0x93, 0xed, 0x28, 0xc3, 0x16, 0x62, 0xf6, 0xb2, 0xfd, 0x64, 0xc0, 0x27, 0xe2, 0x83, 0xed, 0xa4,
	0xb7, 0x32, 0xd2, 0x51, 0x3e, 0x37, 0xbf, 0x7c, 0x2e, 0x27, 0x9f, 0xff, 0xa6, 0xe7, 0x56, 0x57,
	0x3f, 0x56, 0x61, 0x50, 0x07, 0xab, 0x30, 0x28, 0x44, 0x28, 0xc3, 0xa0, 0xfa, 0x09, 0x93, 0xf3,
	0x6d, 0xf5, 0xb2, 0xbf, 0x81, 0x5a, 0xe6, 0x8b, 0x5c, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0x28,
	0x0d, 0x38, 0xa4, 0xa0, 0x01, 0x00, 0x00,
}
