// Code generated by protoc-gen-go. DO NOT EDIT.
// source: weibo.proto

package weibo

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CardType int32

const (
	CardType_Unknown CardType = 0
	// 发文字，图文，都是9
	CardType_Normal CardType = 9
)

var CardType_name = map[int32]string{
	0: "Unknown",
	9: "Normal",
}

var CardType_value = map[string]int32{
	"Unknown": 0,
	"Normal":  9,
}

func (x CardType) String() string {
	return proto.EnumName(CardType_name, int32(x))
}

func (CardType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4102e518bff17504, []int{0}
}

type GenVisitorResponse struct {
	Retcode              int64                    `protobuf:"varint,1,opt,name=retcode,proto3" json:"retcode,omitempty"`
	Msg                  string                   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 *GenVisitorResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *GenVisitorResponse) Reset()         { *m = GenVisitorResponse{} }
func (m *GenVisitorResponse) String() string { return proto.CompactTextString(m) }
func (*GenVisitorResponse) ProtoMessage()    {}
func (*GenVisitorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4102e518bff17504, []int{0}
}

func (m *GenVisitorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenVisitorResponse.Unmarshal(m, b)
}
func (m *GenVisitorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenVisitorResponse.Marshal(b, m, deterministic)
}
func (m *GenVisitorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenVisitorResponse.Merge(m, src)
}
func (m *GenVisitorResponse) XXX_Size() int {
	return xxx_messageInfo_GenVisitorResponse.Size(m)
}
func (m *GenVisitorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenVisitorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenVisitorResponse proto.InternalMessageInfo

func (m *GenVisitorResponse) GetRetcode() int64 {
	if m != nil {
		return m.Retcode
	}
	return 0
}

func (m *GenVisitorResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *GenVisitorResponse) GetData() *GenVisitorResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type GenVisitorResponse_Data struct {
	Tid                  string   `protobuf:"bytes,1,opt,name=tid,proto3" json:"tid,omitempty"`
	NewTid               bool     `protobuf:"varint,2,opt,name=new_tid,json=newTid,proto3" json:"new_tid,omitempty"`
	Confidence           int32    `protobuf:"varint,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenVisitorResponse_Data) Reset()         { *m = GenVisitorResponse_Data{} }
func (m *GenVisitorResponse_Data) String() string { return proto.CompactTextString(m) }
func (*GenVisitorResponse_Data) ProtoMessage()    {}
func (*GenVisitorResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_4102e518bff17504, []int{0, 0}
}

func (m *GenVisitorResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenVisitorResponse_Data.Unmarshal(m, b)
}
func (m *GenVisitorResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenVisitorResponse_Data.Marshal(b, m, deterministic)
}
func (m *GenVisitorResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenVisitorResponse_Data.Merge(m, src)
}
func (m *GenVisitorResponse_Data) XXX_Size() int {
	return xxx_messageInfo_GenVisitorResponse_Data.Size(m)
}
func (m *GenVisitorResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_GenVisitorResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_GenVisitorResponse_Data proto.InternalMessageInfo

func (m *GenVisitorResponse_Data) GetTid() string {
	if m != nil {
		return m.Tid
	}
	return ""
}

func (m *GenVisitorResponse_Data) GetNewTid() bool {
	if m != nil {
		return m.NewTid
	}
	return false
}

func (m *GenVisitorResponse_Data) GetConfidence() int32 {
	if m != nil {
		return m.Confidence
	}
	return 0
}

type VisitorIncarnateResponse struct {
	Retcode              int64                          `protobuf:"varint,1,opt,name=retcode,proto3" json:"retcode,omitempty"`
	Msg                  string                         `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 *VisitorIncarnateResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *VisitorIncarnateResponse) Reset()         { *m = VisitorIncarnateResponse{} }
func (m *VisitorIncarnateResponse) String() string { return proto.CompactTextString(m) }
func (*VisitorIncarnateResponse) ProtoMessage()    {}
func (*VisitorIncarnateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4102e518bff17504, []int{1}
}

func (m *VisitorIncarnateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VisitorIncarnateResponse.Unmarshal(m, b)
}
func (m *VisitorIncarnateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VisitorIncarnateResponse.Marshal(b, m, deterministic)
}
func (m *VisitorIncarnateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VisitorIncarnateResponse.Merge(m, src)
}
func (m *VisitorIncarnateResponse) XXX_Size() int {
	return xxx_messageInfo_VisitorIncarnateResponse.Size(m)
}
func (m *VisitorIncarnateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VisitorIncarnateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VisitorIncarnateResponse proto.InternalMessageInfo

func (m *VisitorIncarnateResponse) GetRetcode() int64 {
	if m != nil {
		return m.Retcode
	}
	return 0
}

func (m *VisitorIncarnateResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *VisitorIncarnateResponse) GetData() *VisitorIncarnateResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type VisitorIncarnateResponse_Data struct {
	Sub                  string   `protobuf:"bytes,1,opt,name=sub,proto3" json:"sub,omitempty"`
	Subp                 string   `protobuf:"bytes,2,opt,name=subp,proto3" json:"subp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VisitorIncarnateResponse_Data) Reset()         { *m = VisitorIncarnateResponse_Data{} }
func (m *VisitorIncarnateResponse_Data) String() string { return proto.CompactTextString(m) }
func (*VisitorIncarnateResponse_Data) ProtoMessage()    {}
func (*VisitorIncarnateResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_4102e518bff17504, []int{1, 0}
}

func (m *VisitorIncarnateResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VisitorIncarnateResponse_Data.Unmarshal(m, b)
}
func (m *VisitorIncarnateResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VisitorIncarnateResponse_Data.Marshal(b, m, deterministic)
}
func (m *VisitorIncarnateResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VisitorIncarnateResponse_Data.Merge(m, src)
}
func (m *VisitorIncarnateResponse_Data) XXX_Size() int {
	return xxx_messageInfo_VisitorIncarnateResponse_Data.Size(m)
}
func (m *VisitorIncarnateResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_VisitorIncarnateResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_VisitorIncarnateResponse_Data proto.InternalMessageInfo

func (m *VisitorIncarnateResponse_Data) GetSub() string {
	if m != nil {
		return m.Sub
	}
	return ""
}

func (m *VisitorIncarnateResponse_Data) GetSubp() string {
	if m != nil {
		return m.Subp
	}
	return ""
}

type ApiContainerGetIndexProfileResponse struct {
	Ok                   int32                                     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Data                 *ApiContainerGetIndexProfileResponse_Data `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                  `json:"-"`
	XXX_unrecognized     []byte                                    `json:"-"`
	XXX_sizecache        int32                                     `json:"-"`
}

func (m *ApiContainerGetIndexProfileResponse) Reset()         { *m = ApiContainerGetIndexProfileResponse{} }
func (m *ApiContainerGetIndexProfileResponse) String() string { return proto.CompactTextString(m) }
func (*ApiContainerGetIndexProfileResponse) ProtoMessage()    {}
func (*ApiContainerGetIndexProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4102e518bff17504, []int{2}
}

func (m *ApiContainerGetIndexProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiContainerGetIndexProfileResponse.Unmarshal(m, b)
}
func (m *ApiContainerGetIndexProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiContainerGetIndexProfileResponse.Marshal(b, m, deterministic)
}
func (m *ApiContainerGetIndexProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiContainerGetIndexProfileResponse.Merge(m, src)
}
func (m *ApiContainerGetIndexProfileResponse) XXX_Size() int {
	return xxx_messageInfo_ApiContainerGetIndexProfileResponse.Size(m)
}
func (m *ApiContainerGetIndexProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiContainerGetIndexProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApiContainerGetIndexProfileResponse proto.InternalMessageInfo

func (m *ApiContainerGetIndexProfileResponse) GetOk() int32 {
	if m != nil {
		return m.Ok
	}
	return 0
}

func (m *ApiContainerGetIndexProfileResponse) GetData() *ApiContainerGetIndexProfileResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type ApiContainerGetIndexProfileResponse_Data struct {
	UserInfo             *ApiContainerGetIndexProfileResponse_Data_UserInfo `protobuf:"bytes,1,opt,name=userInfo,proto3" json:"userInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                           `json:"-"`
	XXX_unrecognized     []byte                                             `json:"-"`
	XXX_sizecache        int32                                              `json:"-"`
}

func (m *ApiContainerGetIndexProfileResponse_Data) Reset() {
	*m = ApiContainerGetIndexProfileResponse_Data{}
}
func (m *ApiContainerGetIndexProfileResponse_Data) String() string { return proto.CompactTextString(m) }
func (*ApiContainerGetIndexProfileResponse_Data) ProtoMessage()    {}
func (*ApiContainerGetIndexProfileResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_4102e518bff17504, []int{2, 0}
}

func (m *ApiContainerGetIndexProfileResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiContainerGetIndexProfileResponse_Data.Unmarshal(m, b)
}
func (m *ApiContainerGetIndexProfileResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiContainerGetIndexProfileResponse_Data.Marshal(b, m, deterministic)
}
func (m *ApiContainerGetIndexProfileResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiContainerGetIndexProfileResponse_Data.Merge(m, src)
}
func (m *ApiContainerGetIndexProfileResponse_Data) XXX_Size() int {
	return xxx_messageInfo_ApiContainerGetIndexProfileResponse_Data.Size(m)
}
func (m *ApiContainerGetIndexProfileResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiContainerGetIndexProfileResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_ApiContainerGetIndexProfileResponse_Data proto.InternalMessageInfo

func (m *ApiContainerGetIndexProfileResponse_Data) GetUserInfo() *ApiContainerGetIndexProfileResponse_Data_UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

type ApiContainerGetIndexProfileResponse_Data_UserInfo struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ScreenName           string   `protobuf:"bytes,2,opt,name=screen_name,json=screenName,proto3" json:"screen_name,omitempty"`
	ProfileImageUrl      string   `protobuf:"bytes,3,opt,name=profile_image_url,json=profileImageUrl,proto3" json:"profile_image_url,omitempty"`
	ProfileUrl           string   `protobuf:"bytes,4,opt,name=profile_url,json=profileUrl,proto3" json:"profile_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiContainerGetIndexProfileResponse_Data_UserInfo) Reset() {
	*m = ApiContainerGetIndexProfileResponse_Data_UserInfo{}
}
func (m *ApiContainerGetIndexProfileResponse_Data_UserInfo) String() string {
	return proto.CompactTextString(m)
}
func (*ApiContainerGetIndexProfileResponse_Data_UserInfo) ProtoMessage() {}
func (*ApiContainerGetIndexProfileResponse_Data_UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4102e518bff17504, []int{2, 0, 0}
}

func (m *ApiContainerGetIndexProfileResponse_Data_UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiContainerGetIndexProfileResponse_Data_UserInfo.Unmarshal(m, b)
}
func (m *ApiContainerGetIndexProfileResponse_Data_UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiContainerGetIndexProfileResponse_Data_UserInfo.Marshal(b, m, deterministic)
}
func (m *ApiContainerGetIndexProfileResponse_Data_UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiContainerGetIndexProfileResponse_Data_UserInfo.Merge(m, src)
}
func (m *ApiContainerGetIndexProfileResponse_Data_UserInfo) XXX_Size() int {
	return xxx_messageInfo_ApiContainerGetIndexProfileResponse_Data_UserInfo.Size(m)
}
func (m *ApiContainerGetIndexProfileResponse_Data_UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiContainerGetIndexProfileResponse_Data_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ApiContainerGetIndexProfileResponse_Data_UserInfo proto.InternalMessageInfo

func (m *ApiContainerGetIndexProfileResponse_Data_UserInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ApiContainerGetIndexProfileResponse_Data_UserInfo) GetScreenName() string {
	if m != nil {
		return m.ScreenName
	}
	return ""
}

func (m *ApiContainerGetIndexProfileResponse_Data_UserInfo) GetProfileImageUrl() string {
	if m != nil {
		return m.ProfileImageUrl
	}
	return ""
}

func (m *ApiContainerGetIndexProfileResponse_Data_UserInfo) GetProfileUrl() string {
	if m != nil {
		return m.ProfileUrl
	}
	return ""
}

type ApiContainerGetIndexCardsResponse struct {
	Ok                   int32                                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Data                 *ApiContainerGetIndexCardsResponse_Data `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                `json:"-"`
	XXX_unrecognized     []byte                                  `json:"-"`
	XXX_sizecache        int32                                   `json:"-"`
}

func (m *ApiContainerGetIndexCardsResponse) Reset()         { *m = ApiContainerGetIndexCardsResponse{} }
func (m *ApiContainerGetIndexCardsResponse) String() string { return proto.CompactTextString(m) }
func (*ApiContainerGetIndexCardsResponse) ProtoMessage()    {}
func (*ApiContainerGetIndexCardsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4102e518bff17504, []int{3}
}

func (m *ApiContainerGetIndexCardsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiContainerGetIndexCardsResponse.Unmarshal(m, b)
}
func (m *ApiContainerGetIndexCardsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiContainerGetIndexCardsResponse.Marshal(b, m, deterministic)
}
func (m *ApiContainerGetIndexCardsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiContainerGetIndexCardsResponse.Merge(m, src)
}
func (m *ApiContainerGetIndexCardsResponse) XXX_Size() int {
	return xxx_messageInfo_ApiContainerGetIndexCardsResponse.Size(m)
}
func (m *ApiContainerGetIndexCardsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiContainerGetIndexCardsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApiContainerGetIndexCardsResponse proto.InternalMessageInfo

func (m *ApiContainerGetIndexCardsResponse) GetOk() int32 {
	if m != nil {
		return m.Ok
	}
	return 0
}

func (m *ApiContainerGetIndexCardsResponse) GetData() *ApiContainerGetIndexCardsResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type ApiContainerGetIndexCardsResponse_Data struct {
	CardlistInfo         *ApiContainerGetIndexCardsResponse_Data_CardListInfo `protobuf:"bytes,1,opt,name=cardlistInfo,proto3" json:"cardlistInfo,omitempty"`
	Cards                []*Card                                              `protobuf:"bytes,2,rep,name=cards,proto3" json:"cards,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                             `json:"-"`
	XXX_unrecognized     []byte                                               `json:"-"`
	XXX_sizecache        int32                                                `json:"-"`
}

func (m *ApiContainerGetIndexCardsResponse_Data) Reset() {
	*m = ApiContainerGetIndexCardsResponse_Data{}
}
func (m *ApiContainerGetIndexCardsResponse_Data) String() string { return proto.CompactTextString(m) }
func (*ApiContainerGetIndexCardsResponse_Data) ProtoMessage()    {}
func (*ApiContainerGetIndexCardsResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_4102e518bff17504, []int{3, 0}
}

func (m *ApiContainerGetIndexCardsResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiContainerGetIndexCardsResponse_Data.Unmarshal(m, b)
}
func (m *ApiContainerGetIndexCardsResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiContainerGetIndexCardsResponse_Data.Marshal(b, m, deterministic)
}
func (m *ApiContainerGetIndexCardsResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiContainerGetIndexCardsResponse_Data.Merge(m, src)
}
func (m *ApiContainerGetIndexCardsResponse_Data) XXX_Size() int {
	return xxx_messageInfo_ApiContainerGetIndexCardsResponse_Data.Size(m)
}
func (m *ApiContainerGetIndexCardsResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiContainerGetIndexCardsResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_ApiContainerGetIndexCardsResponse_Data proto.InternalMessageInfo

func (m *ApiContainerGetIndexCardsResponse_Data) GetCardlistInfo() *ApiContainerGetIndexCardsResponse_Data_CardListInfo {
	if m != nil {
		return m.CardlistInfo
	}
	return nil
}

func (m *ApiContainerGetIndexCardsResponse_Data) GetCards() []*Card {
	if m != nil {
		return m.Cards
	}
	return nil
}

type ApiContainerGetIndexCardsResponse_Data_CardListInfo struct {
	Containerid          string   `protobuf:"bytes,1,opt,name=containerid,proto3" json:"containerid,omitempty"`
	VP                   int32    `protobuf:"varint,2,opt,name=v_p,json=vP,proto3" json:"v_p,omitempty"`
	ShowStyle            int32    `protobuf:"varint,3,opt,name=show_style,json=showStyle,proto3" json:"show_style,omitempty"`
	Total                int32    `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	Page                 int32    `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiContainerGetIndexCardsResponse_Data_CardListInfo) Reset() {
	*m = ApiContainerGetIndexCardsResponse_Data_CardListInfo{}
}
func (m *ApiContainerGetIndexCardsResponse_Data_CardListInfo) String() string {
	return proto.CompactTextString(m)
}
func (*ApiContainerGetIndexCardsResponse_Data_CardListInfo) ProtoMessage() {}
func (*ApiContainerGetIndexCardsResponse_Data_CardListInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4102e518bff17504, []int{3, 0, 0}
}

func (m *ApiContainerGetIndexCardsResponse_Data_CardListInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiContainerGetIndexCardsResponse_Data_CardListInfo.Unmarshal(m, b)
}
func (m *ApiContainerGetIndexCardsResponse_Data_CardListInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiContainerGetIndexCardsResponse_Data_CardListInfo.Marshal(b, m, deterministic)
}
func (m *ApiContainerGetIndexCardsResponse_Data_CardListInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiContainerGetIndexCardsResponse_Data_CardListInfo.Merge(m, src)
}
func (m *ApiContainerGetIndexCardsResponse_Data_CardListInfo) XXX_Size() int {
	return xxx_messageInfo_ApiContainerGetIndexCardsResponse_Data_CardListInfo.Size(m)
}
func (m *ApiContainerGetIndexCardsResponse_Data_CardListInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiContainerGetIndexCardsResponse_Data_CardListInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ApiContainerGetIndexCardsResponse_Data_CardListInfo proto.InternalMessageInfo

func (m *ApiContainerGetIndexCardsResponse_Data_CardListInfo) GetContainerid() string {
	if m != nil {
		return m.Containerid
	}
	return ""
}

func (m *ApiContainerGetIndexCardsResponse_Data_CardListInfo) GetVP() int32 {
	if m != nil {
		return m.VP
	}
	return 0
}

func (m *ApiContainerGetIndexCardsResponse_Data_CardListInfo) GetShowStyle() int32 {
	if m != nil {
		return m.ShowStyle
	}
	return 0
}

func (m *ApiContainerGetIndexCardsResponse_Data_CardListInfo) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ApiContainerGetIndexCardsResponse_Data_CardListInfo) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type Card struct {
	CardType CardType `protobuf:"varint,1,opt,name=card_type,json=cardType,proto3,enum=weibo.CardType" json:"card_type,omitempty"`
	ItemId   string   `protobuf:"bytes,2,opt,name=itemId,proto3" json:"itemId,omitempty"`
	// 这个好像可以用来当做传送门链接
	Scheme               string      `protobuf:"bytes,3,opt,name=scheme,proto3" json:"scheme,omitempty"`
	Mblog                *Card_Mblog `protobuf:"bytes,4,opt,name=mblog,proto3" json:"mblog,omitempty"`
	LastWeiboCard        bool        `protobuf:"varint,5,opt,name=lastWeiboCard,proto3" json:"lastWeiboCard,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Card) Reset()         { *m = Card{} }
func (m *Card) String() string { return proto.CompactTextString(m) }
func (*Card) ProtoMessage()    {}
func (*Card) Descriptor() ([]byte, []int) {
	return fileDescriptor_4102e518bff17504, []int{4}
}

func (m *Card) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Card.Unmarshal(m, b)
}
func (m *Card) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Card.Marshal(b, m, deterministic)
}
func (m *Card) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Card.Merge(m, src)
}
func (m *Card) XXX_Size() int {
	return xxx_messageInfo_Card.Size(m)
}
func (m *Card) XXX_DiscardUnknown() {
	xxx_messageInfo_Card.DiscardUnknown(m)
}

var xxx_messageInfo_Card proto.InternalMessageInfo

func (m *Card) GetCardType() CardType {
	if m != nil {
		return m.CardType
	}
	return CardType_Unknown
}

func (m *Card) GetItemId() string {
	if m != nil {
		return m.ItemId
	}
	return ""
}

func (m *Card) GetScheme() string {
	if m != nil {
		return m.Scheme
	}
	return ""
}

func (m *Card) GetMblog() *Card_Mblog {
	if m != nil {
		return m.Mblog
	}
	return nil
}

func (m *Card) GetLastWeiboCard() bool {
	if m != nil {
		return m.LastWeiboCard
	}
	return false
}

type Card_Mblog struct {
	Visible *Card_Mblog_Visible `protobuf:"bytes,1,opt,name=visible,proto3" json:"visible,omitempty"`
	// 可以用 time.RubyDate 解析
	CreatedAt            string                                             `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Id                   string                                             `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Mid                  string                                             `protobuf:"bytes,4,opt,name=mid,proto3" json:"mid,omitempty"`
	Text                 string                                             `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	TextLength           int32                                              `protobuf:"varint,6,opt,name=textLength,proto3" json:"textLength,omitempty"`
	PicIds               []string                                           `protobuf:"bytes,7,rep,name=pic_ids,json=picIds,proto3" json:"pic_ids,omitempty"`
	User                 *ApiContainerGetIndexProfileResponse_Data_UserInfo `protobuf:"bytes,8,opt,name=user,proto3" json:"user,omitempty"`
	Pics                 []*Card_Mblog_Pics                                 `protobuf:"bytes,9,rep,name=pics,proto3" json:"pics,omitempty"`
	IsTop                bool                                               `protobuf:"varint,10,opt,name=isTop,proto3" json:"isTop,omitempty"`
	RetweetedStatus      *Card_Mblog                                        `protobuf:"bytes,11,opt,name=retweeted_status,json=retweetedStatus,proto3" json:"retweeted_status,omitempty"`
	RawText              string                                             `protobuf:"bytes,12,opt,name=raw_text,json=rawText,proto3" json:"raw_text,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                           `json:"-"`
	XXX_unrecognized     []byte                                             `json:"-"`
	XXX_sizecache        int32                                              `json:"-"`
}

func (m *Card_Mblog) Reset()         { *m = Card_Mblog{} }
func (m *Card_Mblog) String() string { return proto.CompactTextString(m) }
func (*Card_Mblog) ProtoMessage()    {}
func (*Card_Mblog) Descriptor() ([]byte, []int) {
	return fileDescriptor_4102e518bff17504, []int{4, 0}
}

func (m *Card_Mblog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Card_Mblog.Unmarshal(m, b)
}
func (m *Card_Mblog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Card_Mblog.Marshal(b, m, deterministic)
}
func (m *Card_Mblog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Card_Mblog.Merge(m, src)
}
func (m *Card_Mblog) XXX_Size() int {
	return xxx_messageInfo_Card_Mblog.Size(m)
}
func (m *Card_Mblog) XXX_DiscardUnknown() {
	xxx_messageInfo_Card_Mblog.DiscardUnknown(m)
}

var xxx_messageInfo_Card_Mblog proto.InternalMessageInfo

func (m *Card_Mblog) GetVisible() *Card_Mblog_Visible {
	if m != nil {
		return m.Visible
	}
	return nil
}

func (m *Card_Mblog) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Card_Mblog) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Card_Mblog) GetMid() string {
	if m != nil {
		return m.Mid
	}
	return ""
}

func (m *Card_Mblog) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Card_Mblog) GetTextLength() int32 {
	if m != nil {
		return m.TextLength
	}
	return 0
}

func (m *Card_Mblog) GetPicIds() []string {
	if m != nil {
		return m.PicIds
	}
	return nil
}

func (m *Card_Mblog) GetUser() *ApiContainerGetIndexProfileResponse_Data_UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Card_Mblog) GetPics() []*Card_Mblog_Pics {
	if m != nil {
		return m.Pics
	}
	return nil
}

func (m *Card_Mblog) GetIsTop() bool {
	if m != nil {
		return m.IsTop
	}
	return false
}

func (m *Card_Mblog) GetRetweetedStatus() *Card_Mblog {
	if m != nil {
		return m.RetweetedStatus
	}
	return nil
}

func (m *Card_Mblog) GetRawText() string {
	if m != nil {
		return m.RawText
	}
	return ""
}

type Card_Mblog_Visible struct {
	Type                 int64    `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	ListId               int64    `protobuf:"varint,2,opt,name=list_id,json=listId,proto3" json:"list_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Card_Mblog_Visible) Reset()         { *m = Card_Mblog_Visible{} }
func (m *Card_Mblog_Visible) String() string { return proto.CompactTextString(m) }
func (*Card_Mblog_Visible) ProtoMessage()    {}
func (*Card_Mblog_Visible) Descriptor() ([]byte, []int) {
	return fileDescriptor_4102e518bff17504, []int{4, 0, 0}
}

func (m *Card_Mblog_Visible) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Card_Mblog_Visible.Unmarshal(m, b)
}
func (m *Card_Mblog_Visible) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Card_Mblog_Visible.Marshal(b, m, deterministic)
}
func (m *Card_Mblog_Visible) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Card_Mblog_Visible.Merge(m, src)
}
func (m *Card_Mblog_Visible) XXX_Size() int {
	return xxx_messageInfo_Card_Mblog_Visible.Size(m)
}
func (m *Card_Mblog_Visible) XXX_DiscardUnknown() {
	xxx_messageInfo_Card_Mblog_Visible.DiscardUnknown(m)
}

var xxx_messageInfo_Card_Mblog_Visible proto.InternalMessageInfo

func (m *Card_Mblog_Visible) GetType() int64 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Card_Mblog_Visible) GetListId() int64 {
	if m != nil {
		return m.ListId
	}
	return 0
}

type Card_Mblog_Pics struct {
	Pid                  string                 `protobuf:"bytes,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Url                  string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Size                 string                 `protobuf:"bytes,3,opt,name=size,proto3" json:"size,omitempty"`
	Geo                  *Card_Mblog_Pics_Geo   `protobuf:"bytes,4,opt,name=geo,proto3" json:"geo,omitempty"`
	Large                *Card_Mblog_Pics_Large `protobuf:"bytes,5,opt,name=large,proto3" json:"large,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Card_Mblog_Pics) Reset()         { *m = Card_Mblog_Pics{} }
func (m *Card_Mblog_Pics) String() string { return proto.CompactTextString(m) }
func (*Card_Mblog_Pics) ProtoMessage()    {}
func (*Card_Mblog_Pics) Descriptor() ([]byte, []int) {
	return fileDescriptor_4102e518bff17504, []int{4, 0, 1}
}

func (m *Card_Mblog_Pics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Card_Mblog_Pics.Unmarshal(m, b)
}
func (m *Card_Mblog_Pics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Card_Mblog_Pics.Marshal(b, m, deterministic)
}
func (m *Card_Mblog_Pics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Card_Mblog_Pics.Merge(m, src)
}
func (m *Card_Mblog_Pics) XXX_Size() int {
	return xxx_messageInfo_Card_Mblog_Pics.Size(m)
}
func (m *Card_Mblog_Pics) XXX_DiscardUnknown() {
	xxx_messageInfo_Card_Mblog_Pics.DiscardUnknown(m)
}

var xxx_messageInfo_Card_Mblog_Pics proto.InternalMessageInfo

func (m *Card_Mblog_Pics) GetPid() string {
	if m != nil {
		return m.Pid
	}
	return ""
}

func (m *Card_Mblog_Pics) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Card_Mblog_Pics) GetSize() string {
	if m != nil {
		return m.Size
	}
	return ""
}

func (m *Card_Mblog_Pics) GetGeo() *Card_Mblog_Pics_Geo {
	if m != nil {
		return m.Geo
	}
	return nil
}

func (m *Card_Mblog_Pics) GetLarge() *Card_Mblog_Pics_Large {
	if m != nil {
		return m.Large
	}
	return nil
}

type Card_Mblog_Pics_Geo struct {
	Width                int32    `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height               int32    `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Croped               bool     `protobuf:"varint,3,opt,name=croped,proto3" json:"croped,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Card_Mblog_Pics_Geo) Reset()         { *m = Card_Mblog_Pics_Geo{} }
func (m *Card_Mblog_Pics_Geo) String() string { return proto.CompactTextString(m) }
func (*Card_Mblog_Pics_Geo) ProtoMessage()    {}
func (*Card_Mblog_Pics_Geo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4102e518bff17504, []int{4, 0, 1, 0}
}

func (m *Card_Mblog_Pics_Geo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Card_Mblog_Pics_Geo.Unmarshal(m, b)
}
func (m *Card_Mblog_Pics_Geo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Card_Mblog_Pics_Geo.Marshal(b, m, deterministic)
}
func (m *Card_Mblog_Pics_Geo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Card_Mblog_Pics_Geo.Merge(m, src)
}
func (m *Card_Mblog_Pics_Geo) XXX_Size() int {
	return xxx_messageInfo_Card_Mblog_Pics_Geo.Size(m)
}
func (m *Card_Mblog_Pics_Geo) XXX_DiscardUnknown() {
	xxx_messageInfo_Card_Mblog_Pics_Geo.DiscardUnknown(m)
}

var xxx_messageInfo_Card_Mblog_Pics_Geo proto.InternalMessageInfo

func (m *Card_Mblog_Pics_Geo) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Card_Mblog_Pics_Geo) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Card_Mblog_Pics_Geo) GetCroped() bool {
	if m != nil {
		return m.Croped
	}
	return false
}

type Card_Mblog_Pics_Large struct {
	Size                 string               `protobuf:"bytes,1,opt,name=size,proto3" json:"size,omitempty"`
	Url                  string               `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Geo                  *Card_Mblog_Pics_Geo `protobuf:"bytes,3,opt,name=geo,proto3" json:"geo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Card_Mblog_Pics_Large) Reset()         { *m = Card_Mblog_Pics_Large{} }
func (m *Card_Mblog_Pics_Large) String() string { return proto.CompactTextString(m) }
func (*Card_Mblog_Pics_Large) ProtoMessage()    {}
func (*Card_Mblog_Pics_Large) Descriptor() ([]byte, []int) {
	return fileDescriptor_4102e518bff17504, []int{4, 0, 1, 1}
}

func (m *Card_Mblog_Pics_Large) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Card_Mblog_Pics_Large.Unmarshal(m, b)
}
func (m *Card_Mblog_Pics_Large) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Card_Mblog_Pics_Large.Marshal(b, m, deterministic)
}
func (m *Card_Mblog_Pics_Large) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Card_Mblog_Pics_Large.Merge(m, src)
}
func (m *Card_Mblog_Pics_Large) XXX_Size() int {
	return xxx_messageInfo_Card_Mblog_Pics_Large.Size(m)
}
func (m *Card_Mblog_Pics_Large) XXX_DiscardUnknown() {
	xxx_messageInfo_Card_Mblog_Pics_Large.DiscardUnknown(m)
}

var xxx_messageInfo_Card_Mblog_Pics_Large proto.InternalMessageInfo

func (m *Card_Mblog_Pics_Large) GetSize() string {
	if m != nil {
		return m.Size
	}
	return ""
}

func (m *Card_Mblog_Pics_Large) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Card_Mblog_Pics_Large) GetGeo() *Card_Mblog_Pics_Geo {
	if m != nil {
		return m.Geo
	}
	return nil
}

func init() {
	proto.RegisterEnum("weibo.CardType", CardType_name, CardType_value)
	proto.RegisterType((*GenVisitorResponse)(nil), "weibo.GenVisitorResponse")
	proto.RegisterType((*GenVisitorResponse_Data)(nil), "weibo.GenVisitorResponse.Data")
	proto.RegisterType((*VisitorIncarnateResponse)(nil), "weibo.VisitorIncarnateResponse")
	proto.RegisterType((*VisitorIncarnateResponse_Data)(nil), "weibo.VisitorIncarnateResponse.Data")
	proto.RegisterType((*ApiContainerGetIndexProfileResponse)(nil), "weibo.ApiContainerGetIndexProfileResponse")
	proto.RegisterType((*ApiContainerGetIndexProfileResponse_Data)(nil), "weibo.ApiContainerGetIndexProfileResponse.Data")
	proto.RegisterType((*ApiContainerGetIndexProfileResponse_Data_UserInfo)(nil), "weibo.ApiContainerGetIndexProfileResponse.Data.UserInfo")
	proto.RegisterType((*ApiContainerGetIndexCardsResponse)(nil), "weibo.ApiContainerGetIndexCardsResponse")
	proto.RegisterType((*ApiContainerGetIndexCardsResponse_Data)(nil), "weibo.ApiContainerGetIndexCardsResponse.Data")
	proto.RegisterType((*ApiContainerGetIndexCardsResponse_Data_CardListInfo)(nil), "weibo.ApiContainerGetIndexCardsResponse.Data.CardListInfo")
	proto.RegisterType((*Card)(nil), "weibo.Card")
	proto.RegisterType((*Card_Mblog)(nil), "weibo.Card.Mblog")
	proto.RegisterType((*Card_Mblog_Visible)(nil), "weibo.Card.Mblog.Visible")
	proto.RegisterType((*Card_Mblog_Pics)(nil), "weibo.Card.Mblog.Pics")
	proto.RegisterType((*Card_Mblog_Pics_Geo)(nil), "weibo.Card.Mblog.Pics.Geo")
	proto.RegisterType((*Card_Mblog_Pics_Large)(nil), "weibo.Card.Mblog.Pics.Large")
}

func init() {
	proto.RegisterFile("weibo.proto", fileDescriptor_4102e518bff17504)
}

var fileDescriptor_4102e518bff17504 = []byte{
	// 986 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xcf, 0x6e, 0x23, 0x45,
	0x13, 0xff, 0xec, 0xf1, 0xf8, 0x4f, 0x4d, 0xbe, 0x4d, 0xb6, 0x85, 0x96, 0x59, 0x0b, 0x16, 0x6f,
	0x76, 0x25, 0xa2, 0x28, 0x18, 0xc9, 0x2b, 0xa1, 0x15, 0xe2, 0x12, 0x82, 0x14, 0x59, 0x84, 0x55,
	0xe8, 0x4d, 0x40, 0x02, 0x89, 0x51, 0x7b, 0xa6, 0x62, 0xb7, 0x32, 0x9e, 0x1e, 0x75, 0xb7, 0xe3,
	0x84, 0x27, 0x40, 0x5c, 0xb8, 0xf1, 0x18, 0x9c, 0x79, 0x03, 0x24, 0x9e, 0x03, 0x89, 0x1b, 0xcf,
	0x80, 0xaa, 0xa7, 0x9d, 0x8c, 0x95, 0x0d, 0xda, 0x85, 0x93, 0xab, 0xaa, 0x6b, 0x7e, 0x55, 0xf5,
	0xab, 0xaa, 0x6e, 0x43, 0xb4, 0x44, 0x39, 0x51, 0xc3, 0x52, 0x2b, 0xab, 0x58, 0xe8, 0x94, 0xed,
	0xdf, 0x1a, 0xc0, 0x0e, 0xb1, 0xf8, 0x4a, 0x1a, 0x69, 0x95, 0xe6, 0x68, 0x4a, 0x55, 0x18, 0x64,
	0x31, 0x74, 0x34, 0xda, 0x54, 0x65, 0x18, 0x37, 0x06, 0x8d, 0x9d, 0x80, 0xaf, 0x54, 0xb6, 0x05,
	0xc1, 0xdc, 0x4c, 0xe3, 0xe6, 0xa0, 0xb1, 0xd3, 0xe3, 0x24, 0xb2, 0x11, 0xb4, 0x32, 0x61, 0x45,
	0x1c, 0x0c, 0x1a, 0x3b, 0xd1, 0xe8, 0xd1, 0xb0, 0x8a, 0x72, 0x1b, 0x74, 0xf8, 0x99, 0xb0, 0x82,
	0x3b, 0xdf, 0xfe, 0x97, 0xd0, 0x22, 0x8d, 0xd0, 0xac, 0xcc, 0x5c, 0x8c, 0x1e, 0x27, 0x91, 0xbd,
	0x0d, 0x9d, 0x02, 0x97, 0x09, 0x59, 0x29, 0x46, 0x97, 0xb7, 0x0b, 0x5c, 0x9e, 0xc8, 0x8c, 0x3d,
	0x02, 0x48, 0x55, 0x71, 0x26, 0x33, 0x2c, 0x52, 0x74, 0xc1, 0x42, 0x5e, 0xb3, 0x6c, 0xff, 0xd2,
	0x80, 0xd8, 0x47, 0x1c, 0x17, 0xa9, 0xd0, 0x85, 0xb0, 0xf8, 0xaf, 0xea, 0x79, 0xbe, 0x56, 0xcf,
	0x53, 0x5f, 0xcf, 0x5d, 0xd0, 0xf5, 0xaa, 0xf6, 0x6e, 0xaa, 0x32, 0x8b, 0xc9, 0xaa, 0x2a, 0xb3,
	0x98, 0x30, 0x06, 0x2d, 0xb3, 0x98, 0x94, 0x3e, 0x8c, 0x93, 0xb7, 0xff, 0x68, 0xc2, 0x93, 0xfd,
	0x52, 0x1e, 0xa8, 0xc2, 0x0a, 0x59, 0xa0, 0x3e, 0x44, 0x3b, 0x2e, 0x32, 0xbc, 0x3c, 0xd6, 0xea,
	0x4c, 0xe6, 0x37, 0xb9, 0xdf, 0x83, 0xa6, 0x3a, 0x77, 0x60, 0x21, 0x6f, 0xaa, 0x73, 0x76, 0xe0,
	0xf3, 0x6b, 0xba, 0xfc, 0x3e, 0xf4, 0xf9, 0xbd, 0x06, 0x52, 0x3d, 0xd5, 0x3f, 0x1b, 0x3e, 0xd7,
	0x13, 0xe8, 0x2e, 0x0c, 0xea, 0x71, 0x71, 0xa6, 0x5c, 0x8c, 0x68, 0xf4, 0xfc, 0x0d, 0x11, 0x87,
	0xa7, 0xfe, 0x7b, 0x7e, 0x8d, 0xd4, 0xff, 0xa1, 0x01, 0xdd, 0x95, 0x99, 0x0a, 0xf0, 0x3d, 0x0e,
	0x78, 0x53, 0x66, 0xec, 0x3d, 0x88, 0x4c, 0xaa, 0x11, 0x8b, 0xa4, 0x10, 0x73, 0xf4, 0x9c, 0x40,
	0x65, 0x7a, 0x21, 0xe6, 0xc8, 0x76, 0xe1, 0x7e, 0x59, 0x05, 0x4a, 0xe4, 0x5c, 0x4c, 0x31, 0x59,
	0xe8, 0xdc, 0xb5, 0xa3, 0xc7, 0x37, 0xfd, 0xc1, 0x98, 0xec, 0xa7, 0x3a, 0x27, 0xb0, 0x95, 0x2f,
	0x79, 0xb5, 0x2a, 0x30, 0x6f, 0x3a, 0xd5, 0xf9, 0xf6, 0x4f, 0x01, 0x3c, 0x7e, 0x55, 0x29, 0x07,
	0x42, 0x67, 0xe6, 0x4e, 0x92, 0xf7, 0xd7, 0x48, 0xfe, 0xe0, 0x1f, 0x28, 0x59, 0xc3, 0xa9, 0x53,
	0xfc, 0x73, 0xd3, 0x53, 0xfc, 0x1d, 0x6c, 0xa4, 0x42, 0x67, 0xb9, 0x34, 0xb6, 0x46, 0xf3, 0xc7,
	0x6f, 0x84, 0x39, 0x24, 0xd3, 0x91, 0x47, 0xe0, 0x6b, 0x78, 0xec, 0x31, 0x84, 0xa4, 0x9b, 0xb8,
	0x39, 0x08, 0x76, 0xa2, 0x51, 0xe4, 0x81, 0xe9, 0x0b, 0x5e, 0x9d, 0xf4, 0x7f, 0x6c, 0xc0, 0x46,
	0x1d, 0x81, 0x0d, 0x20, 0x4a, 0x57, 0x51, 0xaf, 0x17, 0xb0, 0x6e, 0x62, 0x9b, 0x10, 0x5c, 0x24,
	0xd5, 0xc4, 0x86, 0xbc, 0x79, 0x71, 0xcc, 0xde, 0x05, 0x30, 0x33, 0xb5, 0x4c, 0x8c, 0xbd, 0xca,
	0x57, 0x0b, 0xd8, 0x23, 0xcb, 0x4b, 0x32, 0xb0, 0xb7, 0x20, 0xb4, 0xca, 0x8a, 0xaa, 0x05, 0x21,
	0xaf, 0x14, 0x1a, 0xfc, 0x52, 0x4c, 0x31, 0x0e, 0x9d, 0xd1, 0xc9, 0xdb, 0x7f, 0x75, 0xa0, 0x45,
	0xc9, 0xb0, 0x3d, 0xe8, 0x51, 0x7a, 0x89, 0xbd, 0x2a, 0xab, 0xbd, 0xbc, 0x37, 0xda, 0xac, 0x25,
	0x7f, 0x72, 0x55, 0x22, 0xef, 0xa6, 0x5e, 0x62, 0x0f, 0xa0, 0x2d, 0x2d, 0xce, 0xc7, 0x99, 0x9f,
	0x18, 0xaf, 0x91, 0xdd, 0xa4, 0x33, 0x9c, 0xa3, 0x1f, 0x11, 0xaf, 0xb1, 0xf7, 0x21, 0x9c, 0x4f,
	0x72, 0x35, 0x75, 0x09, 0x45, 0xa3, 0xfb, 0x35, 0xe4, 0xe1, 0x17, 0x74, 0xc0, 0xab, 0x73, 0xf6,
	0x14, 0xfe, 0x9f, 0x0b, 0x63, 0xbf, 0xa6, 0x63, 0x3a, 0x75, 0xc9, 0x76, 0xf9, 0xba, 0xb1, 0xff,
	0x6b, 0x1b, 0x42, 0xf7, 0x19, 0x7b, 0x06, 0x9d, 0x0b, 0x69, 0xe4, 0x24, 0x47, 0xdf, 0xca, 0x87,
	0xb7, 0xa0, 0xdd, 0x75, 0x31, 0xc9, 0x91, 0xaf, 0x3c, 0x89, 0xbd, 0x54, 0xa3, 0xb0, 0x98, 0x25,
	0xc2, 0xfa, 0x0a, 0x7a, 0xde, 0xb2, 0x6f, 0xfd, 0x8e, 0x54, 0x05, 0xd0, 0x8e, 0xd0, 0xb5, 0x24,
	0x33, 0x3f, 0xce, 0x24, 0x12, 0x93, 0x16, 0x2f, 0xad, 0x4b, 0xae, 0xc7, 0x9d, 0x4c, 0x77, 0x22,
	0xfd, 0x1e, 0x61, 0x31, 0xb5, 0xb3, 0xb8, 0x5d, 0xdd, 0x89, 0x37, 0x16, 0xba, 0x4c, 0x4b, 0x99,
	0x26, 0x32, 0x33, 0x71, 0x67, 0x10, 0x10, 0x37, 0xa5, 0x4c, 0xc7, 0x99, 0x61, 0x47, 0xd0, 0xa2,
	0x5d, 0x8d, 0xbb, 0xff, 0x71, 0xe3, 0x1d, 0x0a, 0xdb, 0x85, 0x56, 0x29, 0x53, 0x13, 0xf7, 0xdc,
	0xfc, 0x3d, 0xb8, 0xcd, 0xc6, 0xb1, 0x4c, 0x0d, 0x77, 0x3e, 0x34, 0x26, 0xd2, 0x9c, 0xa8, 0x32,
	0x06, 0x47, 0x72, 0xa5, 0xb0, 0x4f, 0x60, 0x4b, 0xa3, 0x5d, 0x22, 0x12, 0x3f, 0xc6, 0x0a, 0xbb,
	0x30, 0x71, 0x74, 0x57, 0xdb, 0x36, 0xaf, 0x5d, 0x5f, 0x3a, 0x4f, 0xf6, 0x10, 0xba, 0x5a, 0x2c,
	0x13, 0x47, 0xcf, 0x86, 0xa3, 0xa7, 0xa3, 0xc5, 0xf2, 0x04, 0x2f, 0x6d, 0xff, 0x23, 0xe8, 0xf8,
	0x56, 0x38, 0x02, 0x57, 0x83, 0x16, 0x70, 0x27, 0x13, 0x41, 0xb4, 0x46, 0x89, 0x7f, 0x6d, 0x02,
	0xde, 0x76, 0x5b, 0x95, 0xf5, 0x7f, 0x6f, 0x42, 0x8b, 0xb2, 0xa6, 0x46, 0x94, 0x37, 0x2f, 0x54,
	0x59, 0xb5, 0x86, 0x6e, 0x1a, 0xff, 0x62, 0x2c, 0xb4, 0x1b, 0x72, 0x23, 0xbf, 0x5f, 0xcd, 0x9f,
	0x93, 0xd9, 0x1e, 0x04, 0x53, 0x54, 0x7e, 0xf6, 0xfa, 0xaf, 0xa6, 0x64, 0x78, 0x88, 0x8a, 0x93,
	0x1b, 0x1b, 0x41, 0x98, 0x0b, 0xed, 0xf7, 0x24, 0x1a, 0xbd, 0x73, 0x87, 0xff, 0x11, 0xf9, 0xf0,
	0xca, 0xb5, 0xff, 0x39, 0x04, 0x87, 0xa8, 0x88, 0xd0, 0xa5, 0xcc, 0xec, 0xcc, 0x5f, 0x5e, 0x95,
	0x42, 0x4b, 0x31, 0x43, 0x39, 0x9d, 0x59, 0xbf, 0xc0, 0x5e, 0x23, 0x7b, 0xaa, 0x55, 0x89, 0xd5,
	0xac, 0x75, 0xb9, 0xd7, 0xfa, 0xdf, 0x42, 0xe8, 0xc0, 0xaf, 0x6b, 0x69, 0xd4, 0x6a, 0xb9, 0x5d,
	0xb1, 0xaf, 0x2e, 0x78, 0xad, 0xea, 0x76, 0x9f, 0x40, 0x77, 0xb5, 0xcf, 0x2c, 0x82, 0xce, 0x69,
	0x71, 0x5e, 0xa8, 0x65, 0xb1, 0xf5, 0x3f, 0x06, 0xd0, 0x7e, 0xa1, 0xf4, 0x5c, 0xe4, 0x5b, 0xbd,
	0x4f, 0x3b, 0xdf, 0x54, 0x7f, 0x49, 0x26, 0x6d, 0xf7, 0x07, 0xe5, 0xd9, 0xdf, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x47, 0xc7, 0x82, 0xef, 0xaf, 0x08, 0x00, 0x00,
}
