// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.23.1
// source: lsp/weibo/weibo.proto

package weibo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CardType int32

const (
	CardType_Unknown CardType = 0
	// 发文字，图文，都是9
	CardType_Normal CardType = 9
)

// Enum value maps for CardType.
var (
	CardType_name = map[int32]string{
		0: "Unknown",
		9: "Normal",
	}
	CardType_value = map[string]int32{
		"Unknown": 0,
		"Normal":  9,
	}
)

func (x CardType) Enum() *CardType {
	p := new(CardType)
	*p = x
	return p
}

func (x CardType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CardType) Descriptor() protoreflect.EnumDescriptor {
	return file_lsp_weibo_weibo_proto_enumTypes[0].Descriptor()
}

func (CardType) Type() protoreflect.EnumType {
	return &file_lsp_weibo_weibo_proto_enumTypes[0]
}

func (x CardType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CardType.Descriptor instead.
func (CardType) EnumDescriptor() ([]byte, []int) {
	return file_lsp_weibo_weibo_proto_rawDescGZIP(), []int{0}
}

type GenVisitorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Retcode int64                    `protobuf:"varint,1,opt,name=retcode,proto3" json:"retcode,omitempty"`
	Msg     string                   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data    *GenVisitorResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GenVisitorResponse) Reset() {
	*x = GenVisitorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lsp_weibo_weibo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenVisitorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenVisitorResponse) ProtoMessage() {}

func (x *GenVisitorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_weibo_weibo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenVisitorResponse.ProtoReflect.Descriptor instead.
func (*GenVisitorResponse) Descriptor() ([]byte, []int) {
	return file_lsp_weibo_weibo_proto_rawDescGZIP(), []int{0}
}

func (x *GenVisitorResponse) GetRetcode() int64 {
	if x != nil {
		return x.Retcode
	}
	return 0
}

func (x *GenVisitorResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GenVisitorResponse) GetData() *GenVisitorResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type VisitorIncarnateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Retcode int64                          `protobuf:"varint,1,opt,name=retcode,proto3" json:"retcode,omitempty"`
	Msg     string                         `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data    *VisitorIncarnateResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *VisitorIncarnateResponse) Reset() {
	*x = VisitorIncarnateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lsp_weibo_weibo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VisitorIncarnateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitorIncarnateResponse) ProtoMessage() {}

func (x *VisitorIncarnateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_weibo_weibo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitorIncarnateResponse.ProtoReflect.Descriptor instead.
func (*VisitorIncarnateResponse) Descriptor() ([]byte, []int) {
	return file_lsp_weibo_weibo_proto_rawDescGZIP(), []int{1}
}

func (x *VisitorIncarnateResponse) GetRetcode() int64 {
	if x != nil {
		return x.Retcode
	}
	return 0
}

func (x *VisitorIncarnateResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *VisitorIncarnateResponse) GetData() *VisitorIncarnateResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiContainerGetIndexProfileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok   int32                                     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Msg  string                                    `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	Data *ApiContainerGetIndexProfileResponse_Data `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ApiContainerGetIndexProfileResponse) Reset() {
	*x = ApiContainerGetIndexProfileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lsp_weibo_weibo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApiContainerGetIndexProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiContainerGetIndexProfileResponse) ProtoMessage() {}

func (x *ApiContainerGetIndexProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_weibo_weibo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiContainerGetIndexProfileResponse.ProtoReflect.Descriptor instead.
func (*ApiContainerGetIndexProfileResponse) Descriptor() ([]byte, []int) {
	return file_lsp_weibo_weibo_proto_rawDescGZIP(), []int{2}
}

func (x *ApiContainerGetIndexProfileResponse) GetOk() int32 {
	if x != nil {
		return x.Ok
	}
	return 0
}

func (x *ApiContainerGetIndexProfileResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ApiContainerGetIndexProfileResponse) GetData() *ApiContainerGetIndexProfileResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiContainerGetIndexCardsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok   int32                                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Msg  string                                  `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	Data *ApiContainerGetIndexCardsResponse_Data `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ApiContainerGetIndexCardsResponse) Reset() {
	*x = ApiContainerGetIndexCardsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lsp_weibo_weibo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApiContainerGetIndexCardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiContainerGetIndexCardsResponse) ProtoMessage() {}

func (x *ApiContainerGetIndexCardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_weibo_weibo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiContainerGetIndexCardsResponse.ProtoReflect.Descriptor instead.
func (*ApiContainerGetIndexCardsResponse) Descriptor() ([]byte, []int) {
	return file_lsp_weibo_weibo_proto_rawDescGZIP(), []int{3}
}

func (x *ApiContainerGetIndexCardsResponse) GetOk() int32 {
	if x != nil {
		return x.Ok
	}
	return 0
}

func (x *ApiContainerGetIndexCardsResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ApiContainerGetIndexCardsResponse) GetData() *ApiContainerGetIndexCardsResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type Card struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CardType CardType `protobuf:"varint,1,opt,name=card_type,json=cardType,proto3,enum=weibo.CardType" json:"card_type,omitempty"`
	ItemId   string   `protobuf:"bytes,2,opt,name=itemId,proto3" json:"itemId,omitempty"`
	// 这个好像可以用来当做传送门链接
	Scheme        string      `protobuf:"bytes,3,opt,name=scheme,proto3" json:"scheme,omitempty"`
	Mblog         *Card_Mblog `protobuf:"bytes,4,opt,name=mblog,proto3" json:"mblog,omitempty"`
	LastWeiboCard bool        `protobuf:"varint,5,opt,name=lastWeiboCard,proto3" json:"lastWeiboCard,omitempty"`
}

func (x *Card) Reset() {
	*x = Card{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lsp_weibo_weibo_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_weibo_weibo_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_lsp_weibo_weibo_proto_rawDescGZIP(), []int{4}
}

func (x *Card) GetCardType() CardType {
	if x != nil {
		return x.CardType
	}
	return CardType_Unknown
}

func (x *Card) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *Card) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *Card) GetMblog() *Card_Mblog {
	if x != nil {
		return x.Mblog
	}
	return nil
}

func (x *Card) GetLastWeiboCard() bool {
	if x != nil {
		return x.LastWeiboCard
	}
	return false
}

type GenVisitorResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tid        string `protobuf:"bytes,1,opt,name=tid,proto3" json:"tid,omitempty"`
	NewTid     bool   `protobuf:"varint,2,opt,name=new_tid,json=newTid,proto3" json:"new_tid,omitempty"`
	Confidence int32  `protobuf:"varint,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
}

func (x *GenVisitorResponse_Data) Reset() {
	*x = GenVisitorResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lsp_weibo_weibo_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenVisitorResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenVisitorResponse_Data) ProtoMessage() {}

func (x *GenVisitorResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_weibo_weibo_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenVisitorResponse_Data.ProtoReflect.Descriptor instead.
func (*GenVisitorResponse_Data) Descriptor() ([]byte, []int) {
	return file_lsp_weibo_weibo_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GenVisitorResponse_Data) GetTid() string {
	if x != nil {
		return x.Tid
	}
	return ""
}

func (x *GenVisitorResponse_Data) GetNewTid() bool {
	if x != nil {
		return x.NewTid
	}
	return false
}

func (x *GenVisitorResponse_Data) GetConfidence() int32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type VisitorIncarnateResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sub  string `protobuf:"bytes,1,opt,name=sub,proto3" json:"sub,omitempty"`
	Subp string `protobuf:"bytes,2,opt,name=subp,proto3" json:"subp,omitempty"`
}

func (x *VisitorIncarnateResponse_Data) Reset() {
	*x = VisitorIncarnateResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lsp_weibo_weibo_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VisitorIncarnateResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitorIncarnateResponse_Data) ProtoMessage() {}

func (x *VisitorIncarnateResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_weibo_weibo_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitorIncarnateResponse_Data.ProtoReflect.Descriptor instead.
func (*VisitorIncarnateResponse_Data) Descriptor() ([]byte, []int) {
	return file_lsp_weibo_weibo_proto_rawDescGZIP(), []int{1, 0}
}

func (x *VisitorIncarnateResponse_Data) GetSub() string {
	if x != nil {
		return x.Sub
	}
	return ""
}

func (x *VisitorIncarnateResponse_Data) GetSubp() string {
	if x != nil {
		return x.Subp
	}
	return ""
}

type ApiContainerGetIndexProfileResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserInfo *ApiContainerGetIndexProfileResponse_Data_UserInfo `protobuf:"bytes,1,opt,name=userInfo,proto3" json:"userInfo,omitempty"`
}

func (x *ApiContainerGetIndexProfileResponse_Data) Reset() {
	*x = ApiContainerGetIndexProfileResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lsp_weibo_weibo_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApiContainerGetIndexProfileResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiContainerGetIndexProfileResponse_Data) ProtoMessage() {}

func (x *ApiContainerGetIndexProfileResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_weibo_weibo_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiContainerGetIndexProfileResponse_Data.ProtoReflect.Descriptor instead.
func (*ApiContainerGetIndexProfileResponse_Data) Descriptor() ([]byte, []int) {
	return file_lsp_weibo_weibo_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ApiContainerGetIndexProfileResponse_Data) GetUserInfo() *ApiContainerGetIndexProfileResponse_Data_UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type ApiContainerGetIndexProfileResponse_Data_UserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ScreenName      string `protobuf:"bytes,2,opt,name=screen_name,json=screenName,proto3" json:"screen_name,omitempty"`
	ProfileImageUrl string `protobuf:"bytes,3,opt,name=profile_image_url,json=profileImageUrl,proto3" json:"profile_image_url,omitempty"`
	ProfileUrl      string `protobuf:"bytes,4,opt,name=profile_url,json=profileUrl,proto3" json:"profile_url,omitempty"`
}

func (x *ApiContainerGetIndexProfileResponse_Data_UserInfo) Reset() {
	*x = ApiContainerGetIndexProfileResponse_Data_UserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lsp_weibo_weibo_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApiContainerGetIndexProfileResponse_Data_UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiContainerGetIndexProfileResponse_Data_UserInfo) ProtoMessage() {}

func (x *ApiContainerGetIndexProfileResponse_Data_UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_weibo_weibo_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiContainerGetIndexProfileResponse_Data_UserInfo.ProtoReflect.Descriptor instead.
func (*ApiContainerGetIndexProfileResponse_Data_UserInfo) Descriptor() ([]byte, []int) {
	return file_lsp_weibo_weibo_proto_rawDescGZIP(), []int{2, 0, 0}
}

func (x *ApiContainerGetIndexProfileResponse_Data_UserInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ApiContainerGetIndexProfileResponse_Data_UserInfo) GetScreenName() string {
	if x != nil {
		return x.ScreenName
	}
	return ""
}

func (x *ApiContainerGetIndexProfileResponse_Data_UserInfo) GetProfileImageUrl() string {
	if x != nil {
		return x.ProfileImageUrl
	}
	return ""
}

func (x *ApiContainerGetIndexProfileResponse_Data_UserInfo) GetProfileUrl() string {
	if x != nil {
		return x.ProfileUrl
	}
	return ""
}

type ApiContainerGetIndexCardsResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CardlistInfo *ApiContainerGetIndexCardsResponse_Data_CardListInfo `protobuf:"bytes,1,opt,name=cardlistInfo,proto3" json:"cardlistInfo,omitempty"`
	Cards        []*Card                                              `protobuf:"bytes,2,rep,name=cards,proto3" json:"cards,omitempty"`
}

func (x *ApiContainerGetIndexCardsResponse_Data) Reset() {
	*x = ApiContainerGetIndexCardsResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lsp_weibo_weibo_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApiContainerGetIndexCardsResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiContainerGetIndexCardsResponse_Data) ProtoMessage() {}

func (x *ApiContainerGetIndexCardsResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_weibo_weibo_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiContainerGetIndexCardsResponse_Data.ProtoReflect.Descriptor instead.
func (*ApiContainerGetIndexCardsResponse_Data) Descriptor() ([]byte, []int) {
	return file_lsp_weibo_weibo_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ApiContainerGetIndexCardsResponse_Data) GetCardlistInfo() *ApiContainerGetIndexCardsResponse_Data_CardListInfo {
	if x != nil {
		return x.CardlistInfo
	}
	return nil
}

func (x *ApiContainerGetIndexCardsResponse_Data) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

type ApiContainerGetIndexCardsResponse_Data_CardListInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Containerid string `protobuf:"bytes,1,opt,name=containerid,proto3" json:"containerid,omitempty"`
	VP          int32  `protobuf:"varint,2,opt,name=v_p,json=vP,proto3" json:"v_p,omitempty"`
	ShowStyle   int32  `protobuf:"varint,3,opt,name=show_style,json=showStyle,proto3" json:"show_style,omitempty"`
	Total       int32  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	Page        int32  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *ApiContainerGetIndexCardsResponse_Data_CardListInfo) Reset() {
	*x = ApiContainerGetIndexCardsResponse_Data_CardListInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lsp_weibo_weibo_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApiContainerGetIndexCardsResponse_Data_CardListInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiContainerGetIndexCardsResponse_Data_CardListInfo) ProtoMessage() {}

func (x *ApiContainerGetIndexCardsResponse_Data_CardListInfo) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_weibo_weibo_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiContainerGetIndexCardsResponse_Data_CardListInfo.ProtoReflect.Descriptor instead.
func (*ApiContainerGetIndexCardsResponse_Data_CardListInfo) Descriptor() ([]byte, []int) {
	return file_lsp_weibo_weibo_proto_rawDescGZIP(), []int{3, 0, 0}
}

func (x *ApiContainerGetIndexCardsResponse_Data_CardListInfo) GetContainerid() string {
	if x != nil {
		return x.Containerid
	}
	return ""
}

func (x *ApiContainerGetIndexCardsResponse_Data_CardListInfo) GetVP() int32 {
	if x != nil {
		return x.VP
	}
	return 0
}

func (x *ApiContainerGetIndexCardsResponse_Data_CardListInfo) GetShowStyle() int32 {
	if x != nil {
		return x.ShowStyle
	}
	return 0
}

func (x *ApiContainerGetIndexCardsResponse_Data_CardListInfo) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ApiContainerGetIndexCardsResponse_Data_CardListInfo) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type Card_Mblog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Visible *Card_Mblog_Visible `protobuf:"bytes,1,opt,name=visible,proto3" json:"visible,omitempty"`
	// 可以用 time.RubyDate 解析
	CreatedAt       string                                             `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Id              string                                             `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Mid             string                                             `protobuf:"bytes,4,opt,name=mid,proto3" json:"mid,omitempty"`
	Text            string                                             `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	TextLength      int32                                              `protobuf:"varint,6,opt,name=textLength,proto3" json:"textLength,omitempty"`
	PicIds          []string                                           `protobuf:"bytes,7,rep,name=pic_ids,json=picIds,proto3" json:"pic_ids,omitempty"`
	User            *ApiContainerGetIndexProfileResponse_Data_UserInfo `protobuf:"bytes,8,opt,name=user,proto3" json:"user,omitempty"`
	Pics            []*Card_Mblog_Pics                                 `protobuf:"bytes,9,rep,name=pics,proto3" json:"pics,omitempty"`
	IsTop           int32                                              `protobuf:"varint,10,opt,name=isTop,proto3" json:"isTop,omitempty"`
	RetweetedStatus *Card_Mblog                                        `protobuf:"bytes,11,opt,name=retweeted_status,json=retweetedStatus,proto3" json:"retweeted_status,omitempty"`
	RawText         string                                             `protobuf:"bytes,12,opt,name=raw_text,json=rawText,proto3" json:"raw_text,omitempty"`
}

func (x *Card_Mblog) Reset() {
	*x = Card_Mblog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lsp_weibo_weibo_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Card_Mblog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card_Mblog) ProtoMessage() {}

func (x *Card_Mblog) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_weibo_weibo_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card_Mblog.ProtoReflect.Descriptor instead.
func (*Card_Mblog) Descriptor() ([]byte, []int) {
	return file_lsp_weibo_weibo_proto_rawDescGZIP(), []int{4, 0}
}

func (x *Card_Mblog) GetVisible() *Card_Mblog_Visible {
	if x != nil {
		return x.Visible
	}
	return nil
}

func (x *Card_Mblog) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Card_Mblog) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Card_Mblog) GetMid() string {
	if x != nil {
		return x.Mid
	}
	return ""
}

func (x *Card_Mblog) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Card_Mblog) GetTextLength() int32 {
	if x != nil {
		return x.TextLength
	}
	return 0
}

func (x *Card_Mblog) GetPicIds() []string {
	if x != nil {
		return x.PicIds
	}
	return nil
}

func (x *Card_Mblog) GetUser() *ApiContainerGetIndexProfileResponse_Data_UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Card_Mblog) GetPics() []*Card_Mblog_Pics {
	if x != nil {
		return x.Pics
	}
	return nil
}

func (x *Card_Mblog) GetIsTop() int32 {
	if x != nil {
		return x.IsTop
	}
	return 0
}

func (x *Card_Mblog) GetRetweetedStatus() *Card_Mblog {
	if x != nil {
		return x.RetweetedStatus
	}
	return nil
}

func (x *Card_Mblog) GetRawText() string {
	if x != nil {
		return x.RawText
	}
	return ""
}

type Card_Mblog_Visible struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type   int64 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	ListId int64 `protobuf:"varint,2,opt,name=list_id,json=listId,proto3" json:"list_id,omitempty"`
}

func (x *Card_Mblog_Visible) Reset() {
	*x = Card_Mblog_Visible{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lsp_weibo_weibo_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Card_Mblog_Visible) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card_Mblog_Visible) ProtoMessage() {}

func (x *Card_Mblog_Visible) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_weibo_weibo_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card_Mblog_Visible.ProtoReflect.Descriptor instead.
func (*Card_Mblog_Visible) Descriptor() ([]byte, []int) {
	return file_lsp_weibo_weibo_proto_rawDescGZIP(), []int{4, 0, 0}
}

func (x *Card_Mblog_Visible) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Card_Mblog_Visible) GetListId() int64 {
	if x != nil {
		return x.ListId
	}
	return 0
}

type Card_Mblog_Pics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pid   string                 `protobuf:"bytes,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Url   string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Size  string                 `protobuf:"bytes,3,opt,name=size,proto3" json:"size,omitempty"`
	Large *Card_Mblog_Pics_Large `protobuf:"bytes,5,opt,name=large,proto3" json:"large,omitempty"`
}

func (x *Card_Mblog_Pics) Reset() {
	*x = Card_Mblog_Pics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lsp_weibo_weibo_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Card_Mblog_Pics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card_Mblog_Pics) ProtoMessage() {}

func (x *Card_Mblog_Pics) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_weibo_weibo_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card_Mblog_Pics.ProtoReflect.Descriptor instead.
func (*Card_Mblog_Pics) Descriptor() ([]byte, []int) {
	return file_lsp_weibo_weibo_proto_rawDescGZIP(), []int{4, 0, 1}
}

func (x *Card_Mblog_Pics) GetPid() string {
	if x != nil {
		return x.Pid
	}
	return ""
}

func (x *Card_Mblog_Pics) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Card_Mblog_Pics) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *Card_Mblog_Pics) GetLarge() *Card_Mblog_Pics_Large {
	if x != nil {
		return x.Large
	}
	return nil
}

type Card_Mblog_Pics_Large struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size string `protobuf:"bytes,1,opt,name=size,proto3" json:"size,omitempty"`
	Url  string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *Card_Mblog_Pics_Large) Reset() {
	*x = Card_Mblog_Pics_Large{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lsp_weibo_weibo_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Card_Mblog_Pics_Large) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card_Mblog_Pics_Large) ProtoMessage() {}

func (x *Card_Mblog_Pics_Large) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_weibo_weibo_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card_Mblog_Pics_Large.ProtoReflect.Descriptor instead.
func (*Card_Mblog_Pics_Large) Descriptor() ([]byte, []int) {
	return file_lsp_weibo_weibo_proto_rawDescGZIP(), []int{4, 0, 1, 0}
}

func (x *Card_Mblog_Pics_Large) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *Card_Mblog_Pics_Large) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_lsp_weibo_weibo_proto protoreflect.FileDescriptor

var file_lsp_weibo_weibo_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6c, 0x73, 0x70, 0x2f, 0x77, 0x65, 0x69, 0x62, 0x6f, 0x2f, 0x77, 0x65, 0x69, 0x62,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x77, 0x65, 0x69, 0x62, 0x6f, 0x22, 0xc7,
	0x01, 0x0a, 0x12, 0x47, 0x65, 0x6e, 0x56, 0x69, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73,
	0x67, 0x12, 0x32, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x77, 0x65, 0x69, 0x62, 0x6f, 0x2e, 0x47, 0x65, 0x6e, 0x56, 0x69, 0x73, 0x69, 0x74,
	0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x51, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a,
	0x03, 0x74, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x69, 0x64, 0x12,
	0x17, 0x0a, 0x07, 0x6e, 0x65, 0x77, 0x5f, 0x74, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x6e, 0x65, 0x77, 0x54, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x64, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65, 0x22, 0xae, 0x01, 0x0a, 0x18, 0x56, 0x69, 0x73,
	0x69, 0x74, 0x6f, 0x72, 0x49, 0x6e, 0x63, 0x61, 0x72, 0x6e, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73,
	0x67, 0x12, 0x38, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x24, 0x2e, 0x77, 0x65, 0x69, 0x62, 0x6f, 0x2e, 0x56, 0x69, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x49,
	0x6e, 0x63, 0x61, 0x72, 0x6e, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x2c, 0x0a, 0x04, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x75, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x73, 0x75, 0x62, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x75, 0x62, 0x70, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x75, 0x62, 0x70, 0x22, 0xf6, 0x02, 0x0a, 0x23, 0x41, 0x70,
	0x69, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x6f,
	0x6b, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6d, 0x73, 0x67, 0x12, 0x43, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x2f, 0x2e, 0x77, 0x65, 0x69, 0x62, 0x6f, 0x2e, 0x41, 0x70, 0x69, 0x43, 0x6f, 0x6e,
	0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x50, 0x72,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0xe7, 0x01, 0x0a, 0x04, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x54, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x38, 0x2e, 0x77, 0x65, 0x69, 0x62, 0x6f, 0x2e, 0x41, 0x70, 0x69, 0x43,
	0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78,
	0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x44, 0x61, 0x74, 0x61, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x88, 0x01, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x63, 0x72, 0x65, 0x65,
	0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x11, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72,
	0x6c, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x75, 0x72, 0x6c,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x55,
	0x72, 0x6c, 0x22, 0xa1, 0x03, 0x0a, 0x21, 0x41, 0x70, 0x69, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69,
	0x6e, 0x65, 0x72, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x43, 0x61, 0x72, 0x64, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x41, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x77, 0x65, 0x69, 0x62, 0x6f,
	0x2e, 0x41, 0x70, 0x69, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x47, 0x65, 0x74,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x43, 0x61, 0x72, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x96, 0x02,
	0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x5e, 0x0a, 0x0c, 0x63, 0x61, 0x72, 0x64, 0x6c, 0x69,
	0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3a, 0x2e, 0x77,
	0x65, 0x69, 0x62, 0x6f, 0x2e, 0x41, 0x70, 0x69, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65,
	0x72, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x43, 0x61, 0x72, 0x64, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x43, 0x61, 0x72, 0x64,
	0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x63, 0x61, 0x72, 0x64, 0x6c, 0x69,
	0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x21, 0x0a, 0x05, 0x63, 0x61, 0x72, 0x64, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x77, 0x65, 0x69, 0x62, 0x6f, 0x2e, 0x43, 0x61,
	0x72, 0x64, 0x52, 0x05, 0x63, 0x61, 0x72, 0x64, 0x73, 0x1a, 0x8a, 0x01, 0x0a, 0x0c, 0x43, 0x61,
	0x72, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f,
	0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x69, 0x64, 0x12, 0x0f, 0x0a, 0x03,
	0x76, 0x5f, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x76, 0x50, 0x12, 0x1d, 0x0a,
	0x0a, 0x73, 0x68, 0x6f, 0x77, 0x5f, 0x73, 0x74, 0x79, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x73, 0x68, 0x6f, 0x77, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0xc5, 0x06, 0x0a, 0x04, 0x43, 0x61, 0x72, 0x64, 0x12,
	0x2c, 0x0a, 0x09, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x77, 0x65, 0x69, 0x62, 0x6f, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x08, 0x63, 0x61, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69,
	0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x12, 0x27, 0x0a,
	0x05, 0x6d, 0x62, 0x6c, 0x6f, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x77,
	0x65, 0x69, 0x62, 0x6f, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x2e, 0x4d, 0x62, 0x6c, 0x6f, 0x67, 0x52,
	0x05, 0x6d, 0x62, 0x6c, 0x6f, 0x67, 0x12, 0x24, 0x0a, 0x0d, 0x6c, 0x61, 0x73, 0x74, 0x57, 0x65,
	0x69, 0x62, 0x6f, 0x43, 0x61, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x6c,
	0x61, 0x73, 0x74, 0x57, 0x65, 0x69, 0x62, 0x6f, 0x43, 0x61, 0x72, 0x64, 0x1a, 0x8f, 0x05, 0x0a,
	0x05, 0x4d, 0x62, 0x6c, 0x6f, 0x67, 0x12, 0x33, 0x0a, 0x07, 0x76, 0x69, 0x73, 0x69, 0x62, 0x6c,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x77, 0x65, 0x69, 0x62, 0x6f, 0x2e,
	0x43, 0x61, 0x72, 0x64, 0x2e, 0x4d, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x56, 0x69, 0x73, 0x69, 0x62,
	0x6c, 0x65, 0x52, 0x07, 0x76, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x65, 0x78, 0x74, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x65, 0x78, 0x74, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68,
	0x12, 0x17, 0x0a, 0x07, 0x70, 0x69, 0x63, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x06, 0x70, 0x69, 0x63, 0x49, 0x64, 0x73, 0x12, 0x4c, 0x0a, 0x04, 0x75, 0x73, 0x65,
	0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x38, 0x2e, 0x77, 0x65, 0x69, 0x62, 0x6f, 0x2e,
	0x41, 0x70, 0x69, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x47, 0x65, 0x74, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x2a, 0x0a, 0x04, 0x70, 0x69, 0x63, 0x73, 0x18,
	0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x77, 0x65, 0x69, 0x62, 0x6f, 0x2e, 0x43, 0x61,
	0x72, 0x64, 0x2e, 0x4d, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x50, 0x69, 0x63, 0x73, 0x52, 0x04, 0x70,
	0x69, 0x63, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x73, 0x54, 0x6f, 0x70, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x69, 0x73, 0x54, 0x6f, 0x70, 0x12, 0x3c, 0x0a, 0x10, 0x72, 0x65, 0x74,
	0x77, 0x65, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x77, 0x65, 0x69, 0x62, 0x6f, 0x2e, 0x43, 0x61, 0x72, 0x64,
	0x2e, 0x4d, 0x62, 0x6c, 0x6f, 0x67, 0x52, 0x0f, 0x72, 0x65, 0x74, 0x77, 0x65, 0x65, 0x74, 0x65,
	0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x61, 0x77, 0x5f, 0x74,
	0x65, 0x78, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x61, 0x77, 0x54, 0x65,
	0x78, 0x74, 0x1a, 0x36, 0x0a, 0x07, 0x56, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x17, 0x0a, 0x07, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x6c, 0x69, 0x73, 0x74, 0x49, 0x64, 0x1a, 0xa1, 0x01, 0x0a, 0x04, 0x50,
	0x69, 0x63, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x70, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x32, 0x0a, 0x05, 0x6c,
	0x61, 0x72, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x77, 0x65, 0x69,
	0x62, 0x6f, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x2e, 0x4d, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x50, 0x69,
	0x63, 0x73, 0x2e, 0x4c, 0x61, 0x72, 0x67, 0x65, 0x52, 0x05, 0x6c, 0x61, 0x72, 0x67, 0x65, 0x1a,
	0x2d, 0x0a, 0x05, 0x4c, 0x61, 0x72, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x2a, 0x23,
	0x0a, 0x08, 0x43, 0x61, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x6e,
	0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x6f, 0x72, 0x6d, 0x61,
	0x6c, 0x10, 0x09, 0x42, 0x0b, 0x5a, 0x09, 0x6c, 0x73, 0x70, 0x2f, 0x77, 0x65, 0x69, 0x62, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lsp_weibo_weibo_proto_rawDescOnce sync.Once
	file_lsp_weibo_weibo_proto_rawDescData = file_lsp_weibo_weibo_proto_rawDesc
)

func file_lsp_weibo_weibo_proto_rawDescGZIP() []byte {
	file_lsp_weibo_weibo_proto_rawDescOnce.Do(func() {
		file_lsp_weibo_weibo_proto_rawDescData = protoimpl.X.CompressGZIP(file_lsp_weibo_weibo_proto_rawDescData)
	})
	return file_lsp_weibo_weibo_proto_rawDescData
}

var file_lsp_weibo_weibo_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_lsp_weibo_weibo_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_lsp_weibo_weibo_proto_goTypes = []interface{}{
	(CardType)(0),                                               // 0: weibo.CardType
	(*GenVisitorResponse)(nil),                                  // 1: weibo.GenVisitorResponse
	(*VisitorIncarnateResponse)(nil),                            // 2: weibo.VisitorIncarnateResponse
	(*ApiContainerGetIndexProfileResponse)(nil),                 // 3: weibo.ApiContainerGetIndexProfileResponse
	(*ApiContainerGetIndexCardsResponse)(nil),                   // 4: weibo.ApiContainerGetIndexCardsResponse
	(*Card)(nil),                                                // 5: weibo.Card
	(*GenVisitorResponse_Data)(nil),                             // 6: weibo.GenVisitorResponse.Data
	(*VisitorIncarnateResponse_Data)(nil),                       // 7: weibo.VisitorIncarnateResponse.Data
	(*ApiContainerGetIndexProfileResponse_Data)(nil),            // 8: weibo.ApiContainerGetIndexProfileResponse.Data
	(*ApiContainerGetIndexProfileResponse_Data_UserInfo)(nil),   // 9: weibo.ApiContainerGetIndexProfileResponse.Data.UserInfo
	(*ApiContainerGetIndexCardsResponse_Data)(nil),              // 10: weibo.ApiContainerGetIndexCardsResponse.Data
	(*ApiContainerGetIndexCardsResponse_Data_CardListInfo)(nil), // 11: weibo.ApiContainerGetIndexCardsResponse.Data.CardListInfo
	(*Card_Mblog)(nil),                                          // 12: weibo.Card.Mblog
	(*Card_Mblog_Visible)(nil),                                  // 13: weibo.Card.Mblog.Visible
	(*Card_Mblog_Pics)(nil),                                     // 14: weibo.Card.Mblog.Pics
	(*Card_Mblog_Pics_Large)(nil),                               // 15: weibo.Card.Mblog.Pics.Large
}
var file_lsp_weibo_weibo_proto_depIdxs = []int32{
	6,  // 0: weibo.GenVisitorResponse.data:type_name -> weibo.GenVisitorResponse.Data
	7,  // 1: weibo.VisitorIncarnateResponse.data:type_name -> weibo.VisitorIncarnateResponse.Data
	8,  // 2: weibo.ApiContainerGetIndexProfileResponse.data:type_name -> weibo.ApiContainerGetIndexProfileResponse.Data
	10, // 3: weibo.ApiContainerGetIndexCardsResponse.data:type_name -> weibo.ApiContainerGetIndexCardsResponse.Data
	0,  // 4: weibo.Card.card_type:type_name -> weibo.CardType
	12, // 5: weibo.Card.mblog:type_name -> weibo.Card.Mblog
	9,  // 6: weibo.ApiContainerGetIndexProfileResponse.Data.userInfo:type_name -> weibo.ApiContainerGetIndexProfileResponse.Data.UserInfo
	11, // 7: weibo.ApiContainerGetIndexCardsResponse.Data.cardlistInfo:type_name -> weibo.ApiContainerGetIndexCardsResponse.Data.CardListInfo
	5,  // 8: weibo.ApiContainerGetIndexCardsResponse.Data.cards:type_name -> weibo.Card
	13, // 9: weibo.Card.Mblog.visible:type_name -> weibo.Card.Mblog.Visible
	9,  // 10: weibo.Card.Mblog.user:type_name -> weibo.ApiContainerGetIndexProfileResponse.Data.UserInfo
	14, // 11: weibo.Card.Mblog.pics:type_name -> weibo.Card.Mblog.Pics
	12, // 12: weibo.Card.Mblog.retweeted_status:type_name -> weibo.Card.Mblog
	15, // 13: weibo.Card.Mblog.Pics.large:type_name -> weibo.Card.Mblog.Pics.Large
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_lsp_weibo_weibo_proto_init() }
func file_lsp_weibo_weibo_proto_init() {
	if File_lsp_weibo_weibo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lsp_weibo_weibo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenVisitorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lsp_weibo_weibo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VisitorIncarnateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lsp_weibo_weibo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApiContainerGetIndexProfileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lsp_weibo_weibo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApiContainerGetIndexCardsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lsp_weibo_weibo_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Card); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lsp_weibo_weibo_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenVisitorResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lsp_weibo_weibo_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VisitorIncarnateResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lsp_weibo_weibo_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApiContainerGetIndexProfileResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lsp_weibo_weibo_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApiContainerGetIndexProfileResponse_Data_UserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lsp_weibo_weibo_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApiContainerGetIndexCardsResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lsp_weibo_weibo_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApiContainerGetIndexCardsResponse_Data_CardListInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lsp_weibo_weibo_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Card_Mblog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lsp_weibo_weibo_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Card_Mblog_Visible); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lsp_weibo_weibo_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Card_Mblog_Pics); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lsp_weibo_weibo_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Card_Mblog_Pics_Large); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lsp_weibo_weibo_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lsp_weibo_weibo_proto_goTypes,
		DependencyIndexes: file_lsp_weibo_weibo_proto_depIdxs,
		EnumInfos:         file_lsp_weibo_weibo_proto_enumTypes,
		MessageInfos:      file_lsp_weibo_weibo_proto_msgTypes,
	}.Build()
	File_lsp_weibo_weibo_proto = out.File
	file_lsp_weibo_weibo_proto_rawDesc = nil
	file_lsp_weibo_weibo_proto_goTypes = nil
	file_lsp_weibo_weibo_proto_depIdxs = nil
}
