// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.23.1
// source: lsp/acfun/acfun.proto

package acfun

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApiChannelListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChannelListData *ApiChannelListResponse_ChannelListData `protobuf:"bytes,1,opt,name=channelListData,proto3" json:"channelListData,omitempty"`
}

func (x *ApiChannelListResponse) Reset() {
	*x = ApiChannelListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lsp_acfun_acfun_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApiChannelListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiChannelListResponse) ProtoMessage() {}

func (x *ApiChannelListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_acfun_acfun_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiChannelListResponse.ProtoReflect.Descriptor instead.
func (*ApiChannelListResponse) Descriptor() ([]byte, []int) {
	return file_lsp_acfun_acfun_proto_rawDescGZIP(), []int{0}
}

func (x *ApiChannelListResponse) GetChannelListData() *ApiChannelListResponse_ChannelListData {
	if x != nil {
		return x.ChannelListData
	}
	return nil
}

type LivePageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LiveInfo *LivePageResponse_LiveInfo `protobuf:"bytes,1,opt,name=liveInfo,proto3" json:"liveInfo,omitempty"`
}

func (x *LivePageResponse) Reset() {
	*x = LivePageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lsp_acfun_acfun_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LivePageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LivePageResponse) ProtoMessage() {}

func (x *LivePageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_acfun_acfun_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LivePageResponse.ProtoReflect.Descriptor instead.
func (*LivePageResponse) Descriptor() ([]byte, []int) {
	return file_lsp_acfun_acfun_proto_rawDescGZIP(), []int{1}
}

func (x *LivePageResponse) GetLiveInfo() *LivePageResponse_LiveInfo {
	if x != nil {
		return x.LiveInfo
	}
	return nil
}

type ApiChannelListResponse_ChannelListData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result     int64                                                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	RequestId  string                                                 `protobuf:"bytes,2,opt,name=requestId,proto3" json:"requestId,omitempty"`
	LiveList   []*ApiChannelListResponse_ChannelListData_LiveListItem `protobuf:"bytes,3,rep,name=liveList,proto3" json:"liveList,omitempty"`
	Count      int32                                                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Pcursor    string                                                 `protobuf:"bytes,5,opt,name=pcursor,proto3" json:"pcursor,omitempty"`
	TotalCount int32                                                  `protobuf:"varint,6,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
}

func (x *ApiChannelListResponse_ChannelListData) Reset() {
	*x = ApiChannelListResponse_ChannelListData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lsp_acfun_acfun_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApiChannelListResponse_ChannelListData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiChannelListResponse_ChannelListData) ProtoMessage() {}

func (x *ApiChannelListResponse_ChannelListData) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_acfun_acfun_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiChannelListResponse_ChannelListData.ProtoReflect.Descriptor instead.
func (*ApiChannelListResponse_ChannelListData) Descriptor() ([]byte, []int) {
	return file_lsp_acfun_acfun_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ApiChannelListResponse_ChannelListData) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ApiChannelListResponse_ChannelListData) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ApiChannelListResponse_ChannelListData) GetLiveList() []*ApiChannelListResponse_ChannelListData_LiveListItem {
	if x != nil {
		return x.LiveList
	}
	return nil
}

func (x *ApiChannelListResponse_ChannelListData) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ApiChannelListResponse_ChannelListData) GetPcursor() string {
	if x != nil {
		return x.Pcursor
	}
	return ""
}

func (x *ApiChannelListResponse_ChannelListData) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type ApiChannelListResponse_ChannelListData_LiveListItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User       *ApiChannelListResponse_ChannelListData_LiveListItem_User `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`
	CoverUrls  []string                                                  `protobuf:"bytes,7,rep,name=coverUrls,proto3" json:"coverUrls,omitempty"`
	Title      string                                                    `protobuf:"bytes,8,opt,name=title,proto3" json:"title,omitempty"`
	CreateTime int64                                                     `protobuf:"varint,9,opt,name=createTime,proto3" json:"createTime,omitempty"`
	AuthorId   int64                                                     `protobuf:"varint,10,opt,name=authorId,proto3" json:"authorId,omitempty"`
	LiveId     string                                                    `protobuf:"bytes,11,opt,name=liveId,proto3" json:"liveId,omitempty"`
}

func (x *ApiChannelListResponse_ChannelListData_LiveListItem) Reset() {
	*x = ApiChannelListResponse_ChannelListData_LiveListItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lsp_acfun_acfun_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApiChannelListResponse_ChannelListData_LiveListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiChannelListResponse_ChannelListData_LiveListItem) ProtoMessage() {}

func (x *ApiChannelListResponse_ChannelListData_LiveListItem) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_acfun_acfun_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiChannelListResponse_ChannelListData_LiveListItem.ProtoReflect.Descriptor instead.
func (*ApiChannelListResponse_ChannelListData_LiveListItem) Descriptor() ([]byte, []int) {
	return file_lsp_acfun_acfun_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *ApiChannelListResponse_ChannelListData_LiveListItem) GetUser() *ApiChannelListResponse_ChannelListData_LiveListItem_User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *ApiChannelListResponse_ChannelListData_LiveListItem) GetCoverUrls() []string {
	if x != nil {
		return x.CoverUrls
	}
	return nil
}

func (x *ApiChannelListResponse_ChannelListData_LiveListItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ApiChannelListResponse_ChannelListData_LiveListItem) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *ApiChannelListResponse_ChannelListData_LiveListItem) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *ApiChannelListResponse_ChannelListData_LiveListItem) GetLiveId() string {
	if x != nil {
		return x.LiveId
	}
	return ""
}

// bool disableDanmakuShow = 1;
// string requestId = 2;
// string groupId = 3;
// int32 action = 4;
// int32 href = 5;
type ApiChannelListResponse_ChannelListData_LiveListItem_User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action        int32  `protobuf:"varint,1,opt,name=action,proto3" json:"action,omitempty"`
	Id            string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name          string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	FanCountValue int64  `protobuf:"varint,4,opt,name=fanCountValue,proto3" json:"fanCountValue,omitempty"`
	FanCount      string `protobuf:"bytes,5,opt,name=fanCount,proto3" json:"fanCount,omitempty"`
	HeadUrl       string `protobuf:"bytes,6,opt,name=headUrl,proto3" json:"headUrl,omitempty"`
}

func (x *ApiChannelListResponse_ChannelListData_LiveListItem_User) Reset() {
	*x = ApiChannelListResponse_ChannelListData_LiveListItem_User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lsp_acfun_acfun_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApiChannelListResponse_ChannelListData_LiveListItem_User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiChannelListResponse_ChannelListData_LiveListItem_User) ProtoMessage() {}

func (x *ApiChannelListResponse_ChannelListData_LiveListItem_User) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_acfun_acfun_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiChannelListResponse_ChannelListData_LiveListItem_User.ProtoReflect.Descriptor instead.
func (*ApiChannelListResponse_ChannelListData_LiveListItem_User) Descriptor() ([]byte, []int) {
	return file_lsp_acfun_acfun_proto_rawDescGZIP(), []int{0, 0, 0, 0}
}

func (x *ApiChannelListResponse_ChannelListData_LiveListItem_User) GetAction() int32 {
	if x != nil {
		return x.Action
	}
	return 0
}

func (x *ApiChannelListResponse_ChannelListData_LiveListItem_User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ApiChannelListResponse_ChannelListData_LiveListItem_User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApiChannelListResponse_ChannelListData_LiveListItem_User) GetFanCountValue() int64 {
	if x != nil {
		return x.FanCountValue
	}
	return 0
}

func (x *ApiChannelListResponse_ChannelListData_LiveListItem_User) GetFanCount() string {
	if x != nil {
		return x.FanCount
	}
	return ""
}

func (x *ApiChannelListResponse_ChannelListData_LiveListItem_User) GetHeadUrl() string {
	if x != nil {
		return x.HeadUrl
	}
	return ""
}

type LivePageResponse_LiveInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *LivePageResponse_LiveInfo_User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *LivePageResponse_LiveInfo) Reset() {
	*x = LivePageResponse_LiveInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lsp_acfun_acfun_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LivePageResponse_LiveInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LivePageResponse_LiveInfo) ProtoMessage() {}

func (x *LivePageResponse_LiveInfo) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_acfun_acfun_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LivePageResponse_LiveInfo.ProtoReflect.Descriptor instead.
func (*LivePageResponse_LiveInfo) Descriptor() ([]byte, []int) {
	return file_lsp_acfun_acfun_proto_rawDescGZIP(), []int{1, 0}
}

func (x *LivePageResponse_LiveInfo) GetUser() *LivePageResponse_LiveInfo_User {
	if x != nil {
		return x.User
	}
	return nil
}

type LivePageResponse_LiveInfo_User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeadUrl       string `protobuf:"bytes,1,opt,name=headUrl,proto3" json:"headUrl,omitempty"`
	FanCountValue int32  `protobuf:"varint,2,opt,name=fanCountValue,proto3" json:"fanCountValue,omitempty"`
	Name          string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *LivePageResponse_LiveInfo_User) Reset() {
	*x = LivePageResponse_LiveInfo_User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lsp_acfun_acfun_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LivePageResponse_LiveInfo_User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LivePageResponse_LiveInfo_User) ProtoMessage() {}

func (x *LivePageResponse_LiveInfo_User) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_acfun_acfun_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LivePageResponse_LiveInfo_User.ProtoReflect.Descriptor instead.
func (*LivePageResponse_LiveInfo_User) Descriptor() ([]byte, []int) {
	return file_lsp_acfun_acfun_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *LivePageResponse_LiveInfo_User) GetHeadUrl() string {
	if x != nil {
		return x.HeadUrl
	}
	return ""
}

func (x *LivePageResponse_LiveInfo_User) GetFanCountValue() int32 {
	if x != nil {
		return x.FanCountValue
	}
	return 0
}

func (x *LivePageResponse_LiveInfo_User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_lsp_acfun_acfun_proto protoreflect.FileDescriptor

var file_lsp_acfun_acfun_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6c, 0x73, 0x70, 0x2f, 0x61, 0x63, 0x66, 0x75, 0x6e, 0x2f, 0x61, 0x63, 0x66, 0x75,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x61, 0x63, 0x66, 0x75, 0x6e, 0x22, 0xf2,
	0x05, 0x0a, 0x16, 0x41, 0x70, 0x69, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x57, 0x0a, 0x0f, 0x63, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x61, 0x63, 0x66, 0x75, 0x6e, 0x2e, 0x41, 0x70, 0x69, 0x43, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x0f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x61,
	0x74, 0x61, 0x1a, 0xfe, 0x04, 0x0a, 0x0f, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4c, 0x69,
	0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x56, 0x0a, 0x08,
	0x6c, 0x69, 0x76, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3a,
	0x2e, 0x61, 0x63, 0x66, 0x75, 0x6e, 0x2e, 0x41, 0x70, 0x69, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x43, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x4c, 0x69,
	0x76, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x08, 0x6c, 0x69, 0x76, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x63,
	0x75, 0x72, 0x73, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x63, 0x75,
	0x72, 0x73, 0x6f, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x1a, 0x8c, 0x03, 0x0a, 0x0c, 0x4c, 0x69, 0x76, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x53, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x3f, 0x2e, 0x61, 0x63, 0x66, 0x75, 0x6e, 0x2e, 0x41, 0x70, 0x69, 0x43,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x61,
	0x74, 0x61, 0x2e, 0x4c, 0x69, 0x76, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f,
	0x76, 0x65, 0x72, 0x55, 0x72, 0x6c, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x63,
	0x6f, 0x76, 0x65, 0x72, 0x55, 0x72, 0x6c, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x49, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x69,
	0x76, 0x65, 0x49, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x69, 0x76, 0x65,
	0x49, 0x64, 0x1a, 0x9e, 0x01, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x66, 0x61, 0x6e, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d,
	0x66, 0x61, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x66, 0x61, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x66, 0x61, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x65, 0x61,
	0x64, 0x55, 0x72, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64,
	0x55, 0x72, 0x6c, 0x22, 0xf4, 0x01, 0x0a, 0x10, 0x4c, 0x69, 0x76, 0x65, 0x50, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x08, 0x6c, 0x69, 0x76, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x61, 0x63, 0x66,
	0x75, 0x6e, 0x2e, 0x4c, 0x69, 0x76, 0x65, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x4c, 0x69, 0x76, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x6c, 0x69,
	0x76, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0xa1, 0x01, 0x0a, 0x08, 0x4c, 0x69, 0x76, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x39, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x25, 0x2e, 0x61, 0x63, 0x66, 0x75, 0x6e, 0x2e, 0x4c, 0x69, 0x76, 0x65, 0x50, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4c, 0x69, 0x76, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x1a, 0x5a,
	0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x55, 0x72,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x55, 0x72, 0x6c,
	0x12, 0x24, 0x0a, 0x0d, 0x66, 0x61, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x66, 0x61, 0x6e, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x0b, 0x5a, 0x09, 0x6c, 0x73,
	0x70, 0x2f, 0x61, 0x63, 0x66, 0x75, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lsp_acfun_acfun_proto_rawDescOnce sync.Once
	file_lsp_acfun_acfun_proto_rawDescData = file_lsp_acfun_acfun_proto_rawDesc
)

func file_lsp_acfun_acfun_proto_rawDescGZIP() []byte {
	file_lsp_acfun_acfun_proto_rawDescOnce.Do(func() {
		file_lsp_acfun_acfun_proto_rawDescData = protoimpl.X.CompressGZIP(file_lsp_acfun_acfun_proto_rawDescData)
	})
	return file_lsp_acfun_acfun_proto_rawDescData
}

var file_lsp_acfun_acfun_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_lsp_acfun_acfun_proto_goTypes = []interface{}{
	(*ApiChannelListResponse)(nil),                                   // 0: acfun.ApiChannelListResponse
	(*LivePageResponse)(nil),                                         // 1: acfun.LivePageResponse
	(*ApiChannelListResponse_ChannelListData)(nil),                   // 2: acfun.ApiChannelListResponse.ChannelListData
	(*ApiChannelListResponse_ChannelListData_LiveListItem)(nil),      // 3: acfun.ApiChannelListResponse.ChannelListData.LiveListItem
	(*ApiChannelListResponse_ChannelListData_LiveListItem_User)(nil), // 4: acfun.ApiChannelListResponse.ChannelListData.LiveListItem.User
	(*LivePageResponse_LiveInfo)(nil),                                // 5: acfun.LivePageResponse.LiveInfo
	(*LivePageResponse_LiveInfo_User)(nil),                           // 6: acfun.LivePageResponse.LiveInfo.User
}
var file_lsp_acfun_acfun_proto_depIdxs = []int32{
	2, // 0: acfun.ApiChannelListResponse.channelListData:type_name -> acfun.ApiChannelListResponse.ChannelListData
	5, // 1: acfun.LivePageResponse.liveInfo:type_name -> acfun.LivePageResponse.LiveInfo
	3, // 2: acfun.ApiChannelListResponse.ChannelListData.liveList:type_name -> acfun.ApiChannelListResponse.ChannelListData.LiveListItem
	4, // 3: acfun.ApiChannelListResponse.ChannelListData.LiveListItem.user:type_name -> acfun.ApiChannelListResponse.ChannelListData.LiveListItem.User
	6, // 4: acfun.LivePageResponse.LiveInfo.user:type_name -> acfun.LivePageResponse.LiveInfo.User
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_lsp_acfun_acfun_proto_init() }
func file_lsp_acfun_acfun_proto_init() {
	if File_lsp_acfun_acfun_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lsp_acfun_acfun_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApiChannelListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lsp_acfun_acfun_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LivePageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lsp_acfun_acfun_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApiChannelListResponse_ChannelListData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lsp_acfun_acfun_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApiChannelListResponse_ChannelListData_LiveListItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lsp_acfun_acfun_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApiChannelListResponse_ChannelListData_LiveListItem_User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lsp_acfun_acfun_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LivePageResponse_LiveInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lsp_acfun_acfun_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LivePageResponse_LiveInfo_User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lsp_acfun_acfun_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lsp_acfun_acfun_proto_goTypes,
		DependencyIndexes: file_lsp_acfun_acfun_proto_depIdxs,
		MessageInfos:      file_lsp_acfun_acfun_proto_msgTypes,
	}.Build()
	File_lsp_acfun_acfun_proto = out.File
	file_lsp_acfun_acfun_proto_rawDesc = nil
	file_lsp_acfun_acfun_proto_goTypes = nil
	file_lsp_acfun_acfun_proto_depIdxs = nil
}
