// Code generated by protoc-gen-go. DO NOT EDIT.
// source: acfun.proto

package acfun

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ApiChannelListResponse struct {
	ChannelListData      *ApiChannelListResponse_ChannelListData `protobuf:"bytes,1,opt,name=channelListData,proto3" json:"channelListData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                `json:"-"`
	XXX_unrecognized     []byte                                  `json:"-"`
	XXX_sizecache        int32                                   `json:"-"`
}

func (m *ApiChannelListResponse) Reset()         { *m = ApiChannelListResponse{} }
func (m *ApiChannelListResponse) String() string { return proto.CompactTextString(m) }
func (*ApiChannelListResponse) ProtoMessage()    {}
func (*ApiChannelListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_df38f3088a19a4c5, []int{0}
}

func (m *ApiChannelListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiChannelListResponse.Unmarshal(m, b)
}
func (m *ApiChannelListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiChannelListResponse.Marshal(b, m, deterministic)
}
func (m *ApiChannelListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiChannelListResponse.Merge(m, src)
}
func (m *ApiChannelListResponse) XXX_Size() int {
	return xxx_messageInfo_ApiChannelListResponse.Size(m)
}
func (m *ApiChannelListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiChannelListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApiChannelListResponse proto.InternalMessageInfo

func (m *ApiChannelListResponse) GetChannelListData() *ApiChannelListResponse_ChannelListData {
	if m != nil {
		return m.ChannelListData
	}
	return nil
}

type ApiChannelListResponse_ChannelListData struct {
	Result               int64                                                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	RequestId            string                                                 `protobuf:"bytes,2,opt,name=requestId,proto3" json:"requestId,omitempty"`
	LiveList             []*ApiChannelListResponse_ChannelListData_LiveListItem `protobuf:"bytes,3,rep,name=liveList,proto3" json:"liveList,omitempty"`
	Count                int32                                                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Pcursor              string                                                 `protobuf:"bytes,5,opt,name=pcursor,proto3" json:"pcursor,omitempty"`
	TotalCount           int32                                                  `protobuf:"varint,6,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                               `json:"-"`
	XXX_unrecognized     []byte                                                 `json:"-"`
	XXX_sizecache        int32                                                  `json:"-"`
}

func (m *ApiChannelListResponse_ChannelListData) Reset() {
	*m = ApiChannelListResponse_ChannelListData{}
}
func (m *ApiChannelListResponse_ChannelListData) String() string { return proto.CompactTextString(m) }
func (*ApiChannelListResponse_ChannelListData) ProtoMessage()    {}
func (*ApiChannelListResponse_ChannelListData) Descriptor() ([]byte, []int) {
	return fileDescriptor_df38f3088a19a4c5, []int{0, 0}
}

func (m *ApiChannelListResponse_ChannelListData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiChannelListResponse_ChannelListData.Unmarshal(m, b)
}
func (m *ApiChannelListResponse_ChannelListData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiChannelListResponse_ChannelListData.Marshal(b, m, deterministic)
}
func (m *ApiChannelListResponse_ChannelListData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiChannelListResponse_ChannelListData.Merge(m, src)
}
func (m *ApiChannelListResponse_ChannelListData) XXX_Size() int {
	return xxx_messageInfo_ApiChannelListResponse_ChannelListData.Size(m)
}
func (m *ApiChannelListResponse_ChannelListData) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiChannelListResponse_ChannelListData.DiscardUnknown(m)
}

var xxx_messageInfo_ApiChannelListResponse_ChannelListData proto.InternalMessageInfo

func (m *ApiChannelListResponse_ChannelListData) GetResult() int64 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *ApiChannelListResponse_ChannelListData) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *ApiChannelListResponse_ChannelListData) GetLiveList() []*ApiChannelListResponse_ChannelListData_LiveListItem {
	if m != nil {
		return m.LiveList
	}
	return nil
}

func (m *ApiChannelListResponse_ChannelListData) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ApiChannelListResponse_ChannelListData) GetPcursor() string {
	if m != nil {
		return m.Pcursor
	}
	return ""
}

func (m *ApiChannelListResponse_ChannelListData) GetTotalCount() int32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

type ApiChannelListResponse_ChannelListData_LiveListItem struct {
	User                 *ApiChannelListResponse_ChannelListData_LiveListItem_User `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`
	CoverUrls            []string                                                  `protobuf:"bytes,7,rep,name=coverUrls,proto3" json:"coverUrls,omitempty"`
	Title                string                                                    `protobuf:"bytes,8,opt,name=title,proto3" json:"title,omitempty"`
	CreateTime           int64                                                     `protobuf:"varint,9,opt,name=createTime,proto3" json:"createTime,omitempty"`
	AuthorId             int64                                                     `protobuf:"varint,10,opt,name=authorId,proto3" json:"authorId,omitempty"`
	LiveId               string                                                    `protobuf:"bytes,11,opt,name=liveId,proto3" json:"liveId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                  `json:"-"`
	XXX_unrecognized     []byte                                                    `json:"-"`
	XXX_sizecache        int32                                                     `json:"-"`
}

func (m *ApiChannelListResponse_ChannelListData_LiveListItem) Reset() {
	*m = ApiChannelListResponse_ChannelListData_LiveListItem{}
}
func (m *ApiChannelListResponse_ChannelListData_LiveListItem) String() string {
	return proto.CompactTextString(m)
}
func (*ApiChannelListResponse_ChannelListData_LiveListItem) ProtoMessage() {}
func (*ApiChannelListResponse_ChannelListData_LiveListItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_df38f3088a19a4c5, []int{0, 0, 0}
}

func (m *ApiChannelListResponse_ChannelListData_LiveListItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiChannelListResponse_ChannelListData_LiveListItem.Unmarshal(m, b)
}
func (m *ApiChannelListResponse_ChannelListData_LiveListItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiChannelListResponse_ChannelListData_LiveListItem.Marshal(b, m, deterministic)
}
func (m *ApiChannelListResponse_ChannelListData_LiveListItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiChannelListResponse_ChannelListData_LiveListItem.Merge(m, src)
}
func (m *ApiChannelListResponse_ChannelListData_LiveListItem) XXX_Size() int {
	return xxx_messageInfo_ApiChannelListResponse_ChannelListData_LiveListItem.Size(m)
}
func (m *ApiChannelListResponse_ChannelListData_LiveListItem) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiChannelListResponse_ChannelListData_LiveListItem.DiscardUnknown(m)
}

var xxx_messageInfo_ApiChannelListResponse_ChannelListData_LiveListItem proto.InternalMessageInfo

func (m *ApiChannelListResponse_ChannelListData_LiveListItem) GetUser() *ApiChannelListResponse_ChannelListData_LiveListItem_User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *ApiChannelListResponse_ChannelListData_LiveListItem) GetCoverUrls() []string {
	if m != nil {
		return m.CoverUrls
	}
	return nil
}

func (m *ApiChannelListResponse_ChannelListData_LiveListItem) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ApiChannelListResponse_ChannelListData_LiveListItem) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *ApiChannelListResponse_ChannelListData_LiveListItem) GetAuthorId() int64 {
	if m != nil {
		return m.AuthorId
	}
	return 0
}

func (m *ApiChannelListResponse_ChannelListData_LiveListItem) GetLiveId() string {
	if m != nil {
		return m.LiveId
	}
	return ""
}

//      bool disableDanmakuShow = 1;
//      string requestId = 2;
//      string groupId = 3;
//      int32 action = 4;
//      int32 href = 5;
type ApiChannelListResponse_ChannelListData_LiveListItem_User struct {
	Action               int32    `protobuf:"varint,1,opt,name=action,proto3" json:"action,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	FanCountValue        int64    `protobuf:"varint,4,opt,name=fanCountValue,proto3" json:"fanCountValue,omitempty"`
	FanCount             string   `protobuf:"bytes,5,opt,name=fanCount,proto3" json:"fanCount,omitempty"`
	HeadUrl              string   `protobuf:"bytes,6,opt,name=headUrl,proto3" json:"headUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiChannelListResponse_ChannelListData_LiveListItem_User) Reset() {
	*m = ApiChannelListResponse_ChannelListData_LiveListItem_User{}
}
func (m *ApiChannelListResponse_ChannelListData_LiveListItem_User) String() string {
	return proto.CompactTextString(m)
}
func (*ApiChannelListResponse_ChannelListData_LiveListItem_User) ProtoMessage() {}
func (*ApiChannelListResponse_ChannelListData_LiveListItem_User) Descriptor() ([]byte, []int) {
	return fileDescriptor_df38f3088a19a4c5, []int{0, 0, 0, 0}
}

func (m *ApiChannelListResponse_ChannelListData_LiveListItem_User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiChannelListResponse_ChannelListData_LiveListItem_User.Unmarshal(m, b)
}
func (m *ApiChannelListResponse_ChannelListData_LiveListItem_User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiChannelListResponse_ChannelListData_LiveListItem_User.Marshal(b, m, deterministic)
}
func (m *ApiChannelListResponse_ChannelListData_LiveListItem_User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiChannelListResponse_ChannelListData_LiveListItem_User.Merge(m, src)
}
func (m *ApiChannelListResponse_ChannelListData_LiveListItem_User) XXX_Size() int {
	return xxx_messageInfo_ApiChannelListResponse_ChannelListData_LiveListItem_User.Size(m)
}
func (m *ApiChannelListResponse_ChannelListData_LiveListItem_User) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiChannelListResponse_ChannelListData_LiveListItem_User.DiscardUnknown(m)
}

var xxx_messageInfo_ApiChannelListResponse_ChannelListData_LiveListItem_User proto.InternalMessageInfo

func (m *ApiChannelListResponse_ChannelListData_LiveListItem_User) GetAction() int32 {
	if m != nil {
		return m.Action
	}
	return 0
}

func (m *ApiChannelListResponse_ChannelListData_LiveListItem_User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ApiChannelListResponse_ChannelListData_LiveListItem_User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ApiChannelListResponse_ChannelListData_LiveListItem_User) GetFanCountValue() int64 {
	if m != nil {
		return m.FanCountValue
	}
	return 0
}

func (m *ApiChannelListResponse_ChannelListData_LiveListItem_User) GetFanCount() string {
	if m != nil {
		return m.FanCount
	}
	return ""
}

func (m *ApiChannelListResponse_ChannelListData_LiveListItem_User) GetHeadUrl() string {
	if m != nil {
		return m.HeadUrl
	}
	return ""
}

type V2UserContentProfileResponse struct {
	Errorid              int32                               `protobuf:"varint,1,opt,name=errorid,proto3" json:"errorid,omitempty"`
	Requestid            string                              `protobuf:"bytes,2,opt,name=requestid,proto3" json:"requestid,omitempty"`
	Vdata                *V2UserContentProfileResponse_Vdata `protobuf:"bytes,3,opt,name=vdata,proto3" json:"vdata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *V2UserContentProfileResponse) Reset()         { *m = V2UserContentProfileResponse{} }
func (m *V2UserContentProfileResponse) String() string { return proto.CompactTextString(m) }
func (*V2UserContentProfileResponse) ProtoMessage()    {}
func (*V2UserContentProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_df38f3088a19a4c5, []int{1}
}

func (m *V2UserContentProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_V2UserContentProfileResponse.Unmarshal(m, b)
}
func (m *V2UserContentProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_V2UserContentProfileResponse.Marshal(b, m, deterministic)
}
func (m *V2UserContentProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_V2UserContentProfileResponse.Merge(m, src)
}
func (m *V2UserContentProfileResponse) XXX_Size() int {
	return xxx_messageInfo_V2UserContentProfileResponse.Size(m)
}
func (m *V2UserContentProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_V2UserContentProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_V2UserContentProfileResponse proto.InternalMessageInfo

func (m *V2UserContentProfileResponse) GetErrorid() int32 {
	if m != nil {
		return m.Errorid
	}
	return 0
}

func (m *V2UserContentProfileResponse) GetRequestid() string {
	if m != nil {
		return m.Requestid
	}
	return ""
}

func (m *V2UserContentProfileResponse) GetVdata() *V2UserContentProfileResponse_Vdata {
	if m != nil {
		return m.Vdata
	}
	return nil
}

type V2UserContentProfileResponse_Vdata struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	UserImg              string   `protobuf:"bytes,2,opt,name=userImg,proto3" json:"userImg,omitempty"`
	Followed             int64    `protobuf:"varint,3,opt,name=Followed,proto3" json:"Followed,omitempty"`
	Username             string   `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *V2UserContentProfileResponse_Vdata) Reset()         { *m = V2UserContentProfileResponse_Vdata{} }
func (m *V2UserContentProfileResponse_Vdata) String() string { return proto.CompactTextString(m) }
func (*V2UserContentProfileResponse_Vdata) ProtoMessage()    {}
func (*V2UserContentProfileResponse_Vdata) Descriptor() ([]byte, []int) {
	return fileDescriptor_df38f3088a19a4c5, []int{1, 0}
}

func (m *V2UserContentProfileResponse_Vdata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_V2UserContentProfileResponse_Vdata.Unmarshal(m, b)
}
func (m *V2UserContentProfileResponse_Vdata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_V2UserContentProfileResponse_Vdata.Marshal(b, m, deterministic)
}
func (m *V2UserContentProfileResponse_Vdata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_V2UserContentProfileResponse_Vdata.Merge(m, src)
}
func (m *V2UserContentProfileResponse_Vdata) XXX_Size() int {
	return xxx_messageInfo_V2UserContentProfileResponse_Vdata.Size(m)
}
func (m *V2UserContentProfileResponse_Vdata) XXX_DiscardUnknown() {
	xxx_messageInfo_V2UserContentProfileResponse_Vdata.DiscardUnknown(m)
}

var xxx_messageInfo_V2UserContentProfileResponse_Vdata proto.InternalMessageInfo

func (m *V2UserContentProfileResponse_Vdata) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *V2UserContentProfileResponse_Vdata) GetUserImg() string {
	if m != nil {
		return m.UserImg
	}
	return ""
}

func (m *V2UserContentProfileResponse_Vdata) GetFollowed() int64 {
	if m != nil {
		return m.Followed
	}
	return 0
}

func (m *V2UserContentProfileResponse_Vdata) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func init() {
	proto.RegisterType((*ApiChannelListResponse)(nil), "acfun.ApiChannelListResponse")
	proto.RegisterType((*ApiChannelListResponse_ChannelListData)(nil), "acfun.ApiChannelListResponse.ChannelListData")
	proto.RegisterType((*ApiChannelListResponse_ChannelListData_LiveListItem)(nil), "acfun.ApiChannelListResponse.ChannelListData.LiveListItem")
	proto.RegisterType((*ApiChannelListResponse_ChannelListData_LiveListItem_User)(nil), "acfun.ApiChannelListResponse.ChannelListData.LiveListItem.User")
	proto.RegisterType((*V2UserContentProfileResponse)(nil), "acfun.V2UserContentProfileResponse")
	proto.RegisterType((*V2UserContentProfileResponse_Vdata)(nil), "acfun.V2UserContentProfileResponse.Vdata")
}

func init() {
	proto.RegisterFile("acfun.proto", fileDescriptor_df38f3088a19a4c5)
}

var fileDescriptor_df38f3088a19a4c5 = []byte{
	// 512 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x5d, 0x8b, 0xd3, 0x40,
	0x14, 0xa5, 0x4d, 0xb2, 0x6d, 0x6f, 0xd5, 0x85, 0x41, 0x96, 0xa1, 0x2c, 0x52, 0x16, 0x1f, 0xea,
	0x83, 0x79, 0xa8, 0x6f, 0xbe, 0x2c, 0x5a, 0x11, 0x0a, 0xfb, 0x20, 0xa3, 0xad, 0xe0, 0xdb, 0x98,
	0xdc, 0xda, 0x81, 0x69, 0xa6, 0x3b, 0x99, 0xd4, 0xff, 0x20, 0xfe, 0x06, 0x7f, 0xa4, 0x3f, 0x40,
	0xe4, 0xde, 0x7c, 0x6c, 0xb7, 0x88, 0xa0, 0x6f, 0x39, 0x27, 0xf7, 0xe3, 0xe4, 0x9c, 0xc9, 0xc0,
	0x58, 0x67, 0x9b, 0xaa, 0x48, 0xf7, 0xde, 0x05, 0x27, 0x12, 0x06, 0x57, 0x3f, 0x13, 0xb8, 0x78,
	0xb5, 0x37, 0x8b, 0xad, 0x2e, 0x0a, 0xb4, 0x37, 0xa6, 0x0c, 0x0a, 0xcb, 0xbd, 0x2b, 0x4a, 0x14,
	0x1f, 0xe1, 0x3c, 0xbb, 0xa3, 0xdf, 0xe8, 0xa0, 0x65, 0x6f, 0xda, 0x9b, 0x8d, 0xe7, 0xcf, 0xd3,
	0x7a, 0xd0, 0x9f, 0xfb, 0xd2, 0xc5, 0xfd, 0x26, 0x75, 0x3a, 0x65, 0xf2, 0x2b, 0x86, 0xf3, 0x93,
	0x22, 0x71, 0x01, 0x67, 0x1e, 0xcb, 0xca, 0x06, 0xde, 0x11, 0xa9, 0x06, 0x89, 0x4b, 0x18, 0x79,
	0xbc, 0xad, 0xb0, 0x0c, 0xcb, 0x5c, 0xf6, 0xa7, 0xbd, 0xd9, 0x48, 0xdd, 0x11, 0x62, 0x0d, 0x43,
	0x6b, 0x0e, 0x48, 0x53, 0x64, 0x34, 0x8d, 0x66, 0xe3, 0xf9, 0xcb, 0x7f, 0xd2, 0x96, 0xde, 0x34,
	0xdd, 0xcb, 0x80, 0x3b, 0xd5, 0xcd, 0x12, 0x8f, 0x21, 0xc9, 0x5c, 0x55, 0x04, 0x19, 0x4f, 0x7b,
	0xb3, 0x44, 0xd5, 0x40, 0x48, 0x18, 0xec, 0xb3, 0xca, 0x97, 0xce, 0xcb, 0x84, 0x95, 0xb4, 0x50,
	0x3c, 0x01, 0x08, 0x2e, 0x68, 0xbb, 0xe0, 0xa6, 0x33, 0x6e, 0x3a, 0x62, 0x26, 0xdf, 0x23, 0x78,
	0x70, 0xbc, 0x4a, 0xbc, 0x87, 0xb8, 0x2a, 0xd1, 0x73, 0xe9, 0x78, 0x7e, 0xfd, 0xff, 0xa2, 0xd3,
	0x55, 0x89, 0x5e, 0xf1, 0x30, 0xf2, 0x2a, 0x73, 0x07, 0xf4, 0x2b, 0x6f, 0x4b, 0x39, 0x98, 0x46,
	0xe4, 0x55, 0x47, 0xd0, 0x37, 0x05, 0x13, 0x2c, 0xca, 0x21, 0x6b, 0xaf, 0x01, 0x29, 0xcf, 0x3c,
	0xea, 0x80, 0x1f, 0xcc, 0x0e, 0xe5, 0x88, 0xbd, 0x3f, 0x62, 0xc4, 0x04, 0x86, 0xba, 0x0a, 0x5b,
	0xe7, 0x97, 0xb9, 0x04, 0x7e, 0xdb, 0x61, 0xca, 0x8c, 0x1c, 0x5b, 0xe6, 0x72, 0xcc, 0x23, 0x1b,
	0x34, 0xf9, 0xd1, 0x83, 0x98, 0x64, 0x51, 0x81, 0xce, 0x82, 0x71, 0x05, 0x87, 0x9a, 0xa8, 0x06,
	0x89, 0x47, 0xd0, 0x37, 0x6d, 0x9a, 0x7d, 0x93, 0x0b, 0x01, 0x71, 0xa1, 0x77, 0x28, 0x23, 0x66,
	0xf8, 0x59, 0x3c, 0x85, 0x87, 0x1b, 0x5d, 0xb0, 0x7d, 0x6b, 0x6d, 0x2b, 0xe4, 0x28, 0x22, 0x75,
	0x9f, 0x24, 0x79, 0x2d, 0xd1, 0x64, 0xd2, 0x61, 0x8a, 0x6b, 0x8b, 0x3a, 0x5f, 0x79, 0xcb, 0x36,
	0x8f, 0x54, 0x0b, 0xaf, 0xbe, 0xf5, 0xe1, 0x72, 0x3d, 0x27, 0x89, 0x0b, 0x57, 0x04, 0x2c, 0xc2,
	0x3b, 0xef, 0x36, 0xc6, 0x62, 0x77, 0xf4, 0x25, 0x0c, 0xd0, 0x7b, 0xe7, 0x4d, 0xde, 0x28, 0x6f,
	0xe1, 0xd1, 0x79, 0x34, 0xa7, 0xe7, 0xd1, 0xe4, 0xe2, 0x1a, 0x92, 0x43, 0x4e, 0x3f, 0x4a, 0xc4,
	0xb9, 0x3e, 0x6b, 0x72, 0xfd, 0xdb, 0xae, 0x74, 0x4d, 0x0d, 0xaa, 0xee, 0x9b, 0xdc, 0x42, 0xc2,
	0x98, 0xac, 0xa3, 0x4c, 0x97, 0x79, 0xfb, 0x3f, 0xd4, 0x88, 0x94, 0xf1, 0xd3, 0xee, 0x4b, 0xb3,
	0xbd, 0x85, 0x64, 0xc5, 0x5b, 0x67, 0xad, 0xfb, 0x8a, 0x39, 0xaf, 0x8f, 0x54, 0x87, 0xe9, 0x1d,
	0x95, 0xb1, 0xc9, 0x71, 0x6d, 0x53, 0x8b, 0x5f, 0x0f, 0x3e, 0xd5, 0x57, 0xc1, 0xe7, 0x33, 0xbe,
	0x18, 0x5e, 0xfc, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x61, 0x5d, 0x60, 0x90, 0x27, 0x04, 0x00, 0x00,
}
