// Code generated by protoc-gen-go. DO NOT EDIT.
// source: backend.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GenericHeader struct {
	RequestId            string   `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ErrorCode            int32    `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenericHeader) Reset()         { *m = GenericHeader{} }
func (m *GenericHeader) String() string { return proto.CompactTextString(m) }
func (*GenericHeader) ProtoMessage()    {}
func (*GenericHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{0}
}

func (m *GenericHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenericHeader.Unmarshal(m, b)
}
func (m *GenericHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenericHeader.Marshal(b, m, deterministic)
}
func (m *GenericHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenericHeader.Merge(m, src)
}
func (m *GenericHeader) XXX_Size() int {
	return xxx_messageInfo_GenericHeader.Size(m)
}
func (m *GenericHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_GenericHeader.DiscardUnknown(m)
}

var xxx_messageInfo_GenericHeader proto.InternalMessageInfo

func (m *GenericHeader) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *GenericHeader) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *GenericHeader) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type PingResponse struct {
	Header               *GenericHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Message              string         `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PingResponse) Reset()         { *m = PingResponse{} }
func (m *PingResponse) String() string { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()    {}
func (*PingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{1}
}

func (m *PingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResponse.Unmarshal(m, b)
}
func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResponse.Marshal(b, m, deterministic)
}
func (m *PingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResponse.Merge(m, src)
}
func (m *PingResponse) XXX_Size() int {
	return xxx_messageInfo_PingResponse.Size(m)
}
func (m *PingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

func (m *PingResponse) GetHeader() *GenericHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *PingResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*GenericHeader)(nil), "model.GenericHeader")
	proto.RegisterType((*PingResponse)(nil), "model.PingResponse")
}

func init() {
	proto.RegisterFile("backend.proto", fileDescriptor_5ab9ba5b8d8b2ba5)
}

var fileDescriptor_5ab9ba5b8d8b2ba5 = []byte{
	// 197 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0xbf, 0x6e, 0x83, 0x30,
	0x10, 0xc6, 0x05, 0x15, 0x20, 0xae, 0xb0, 0x58, 0x1d, 0xbc, 0x54, 0x42, 0x74, 0x61, 0xa8, 0x18,
	0xda, 0x37, 0x68, 0x87, 0x24, 0x43, 0xa4, 0xc8, 0x43, 0x86, 0x2c, 0x08, 0xf0, 0x89, 0xa0, 0x04,
	0x9b, 0x9c, 0xc9, 0xfb, 0x47, 0x39, 0x60, 0xc8, 0x78, 0xbf, 0xef, 0xf4, 0xfd, 0x81, 0xb4, 0xa9,
	0xdb, 0x0b, 0x1a, 0x5d, 0x8e, 0x64, 0x27, 0x2b, 0x82, 0xc1, 0x6a, 0xbc, 0xe6, 0x04, 0xe9, 0x06,
	0x0d, 0x52, 0xdf, 0x6e, 0xb1, 0xd6, 0x48, 0xe2, 0x13, 0x80, 0xf0, 0x76, 0x47, 0x37, 0x55, 0xbd,
	0x96, 0x5e, 0xe6, 0x15, 0xb1, 0x8a, 0x17, 0xb2, 0xd3, 0x4f, 0x19, 0x89, 0x2c, 0x55, 0xad, 0xd5,
	0x28, 0xfd, 0xcc, 0x2b, 0x02, 0x15, 0x33, 0xf9, 0xb7, 0x1a, 0xc5, 0x17, 0xa4, 0xb3, 0x3c, 0xa0,
	0x73, 0x75, 0x87, 0xf2, 0x8d, 0x0d, 0x12, 0x86, 0xfb, 0x99, 0xe5, 0x47, 0x48, 0x0e, 0xbd, 0xe9,
	0x14, 0xba, 0xd1, 0x1a, 0x87, 0xe2, 0x1b, 0xc2, 0x33, 0x87, 0x73, 0xdc, 0xfb, 0xcf, 0x47, 0xc9,
	0xdd, 0xca, 0x97, 0x62, 0x6a, 0xf9, 0x11, 0x12, 0xa2, 0xd5, 0xdc, 0x67, 0xf3, 0xf5, 0xfc, 0x8b,
	0x4e, 0xf3, 0xa8, 0x26, 0xe4, 0x89, 0xbf, 0x8f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5b, 0xde, 0xa2,
	0xd4, 0xf3, 0x00, 0x00, 0x00,
}
