// Code generated by protoc-gen-go. DO NOT EDIT.
// source: douyu.proto

package douyu

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ShowStatus int32

const (
	ShowStatus_Unknown  ShowStatus = 0
	ShowStatus_Living   ShowStatus = 1
	ShowStatus_NoLiving ShowStatus = 2
)

var ShowStatus_name = map[int32]string{
	0: "Unknown",
	1: "Living",
	2: "NoLiving",
}

var ShowStatus_value = map[string]int32{
	"Unknown":  0,
	"Living":   1,
	"NoLiving": 2,
}

func (x ShowStatus) String() string {
	return proto.EnumName(ShowStatus_name, int32(x))
}

func (ShowStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_50f0928b53cdacf8, []int{0}
}

type VideoLoopStatus int32

const (
	VideoLoopStatus_Off VideoLoopStatus = 0
	VideoLoopStatus_On  VideoLoopStatus = 1
)

var VideoLoopStatus_name = map[int32]string{
	0: "Off",
	1: "On",
}

var VideoLoopStatus_value = map[string]int32{
	"Off": 0,
	"On":  1,
}

func (x VideoLoopStatus) String() string {
	return proto.EnumName(VideoLoopStatus_name, int32(x))
}

func (VideoLoopStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_50f0928b53cdacf8, []int{1}
}

type Avatar struct {
	Big                  string   `protobuf:"bytes,1,opt,name=big,proto3" json:"big,omitempty"`
	Middle               string   `protobuf:"bytes,2,opt,name=middle,proto3" json:"middle,omitempty"`
	Small                string   `protobuf:"bytes,3,opt,name=small,proto3" json:"small,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Avatar) Reset()         { *m = Avatar{} }
func (m *Avatar) String() string { return proto.CompactTextString(m) }
func (*Avatar) ProtoMessage()    {}
func (*Avatar) Descriptor() ([]byte, []int) {
	return fileDescriptor_50f0928b53cdacf8, []int{0}
}

func (m *Avatar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Avatar.Unmarshal(m, b)
}
func (m *Avatar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Avatar.Marshal(b, m, deterministic)
}
func (m *Avatar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Avatar.Merge(m, src)
}
func (m *Avatar) XXX_Size() int {
	return xxx_messageInfo_Avatar.Size(m)
}
func (m *Avatar) XXX_DiscardUnknown() {
	xxx_messageInfo_Avatar.DiscardUnknown(m)
}

var xxx_messageInfo_Avatar proto.InternalMessageInfo

func (m *Avatar) GetBig() string {
	if m != nil {
		return m.Big
	}
	return ""
}

func (m *Avatar) GetMiddle() string {
	if m != nil {
		return m.Middle
	}
	return ""
}

func (m *Avatar) GetSmall() string {
	if m != nil {
		return m.Small
	}
	return ""
}

type Room struct {
	Nickname             string          `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	RoomId               int64           `protobuf:"varint,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	RoomName             string          `protobuf:"bytes,3,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	RoomUrl              string          `protobuf:"bytes,4,opt,name=room_url,json=roomUrl,proto3" json:"room_url,omitempty"`
	ShowStatus           ShowStatus      `protobuf:"varint,5,opt,name=show_status,json=showStatus,proto3,enum=douyu.ShowStatus" json:"show_status,omitempty"`
	VideoLoop            VideoLoopStatus `protobuf:"varint,6,opt,name=videoLoop,proto3,enum=douyu.VideoLoopStatus" json:"videoLoop,omitempty"`
	Avatar               *Avatar         `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Room) Reset()         { *m = Room{} }
func (m *Room) String() string { return proto.CompactTextString(m) }
func (*Room) ProtoMessage()    {}
func (*Room) Descriptor() ([]byte, []int) {
	return fileDescriptor_50f0928b53cdacf8, []int{1}
}

func (m *Room) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Room.Unmarshal(m, b)
}
func (m *Room) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Room.Marshal(b, m, deterministic)
}
func (m *Room) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Room.Merge(m, src)
}
func (m *Room) XXX_Size() int {
	return xxx_messageInfo_Room.Size(m)
}
func (m *Room) XXX_DiscardUnknown() {
	xxx_messageInfo_Room.DiscardUnknown(m)
}

var xxx_messageInfo_Room proto.InternalMessageInfo

func (m *Room) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *Room) GetRoomId() int64 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *Room) GetRoomName() string {
	if m != nil {
		return m.RoomName
	}
	return ""
}

func (m *Room) GetRoomUrl() string {
	if m != nil {
		return m.RoomUrl
	}
	return ""
}

func (m *Room) GetShowStatus() ShowStatus {
	if m != nil {
		return m.ShowStatus
	}
	return ShowStatus_Unknown
}

func (m *Room) GetVideoLoop() VideoLoopStatus {
	if m != nil {
		return m.VideoLoop
	}
	return VideoLoopStatus_Off
}

func (m *Room) GetAvatar() *Avatar {
	if m != nil {
		return m.Avatar
	}
	return nil
}

type BetardResponse struct {
	Room                 *Room    `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BetardResponse) Reset()         { *m = BetardResponse{} }
func (m *BetardResponse) String() string { return proto.CompactTextString(m) }
func (*BetardResponse) ProtoMessage()    {}
func (*BetardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_50f0928b53cdacf8, []int{2}
}

func (m *BetardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BetardResponse.Unmarshal(m, b)
}
func (m *BetardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BetardResponse.Marshal(b, m, deterministic)
}
func (m *BetardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BetardResponse.Merge(m, src)
}
func (m *BetardResponse) XXX_Size() int {
	return xxx_messageInfo_BetardResponse.Size(m)
}
func (m *BetardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BetardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BetardResponse proto.InternalMessageInfo

func (m *BetardResponse) GetRoom() *Room {
	if m != nil {
		return m.Room
	}
	return nil
}

type LiveInfo struct {
	Nickname             string          `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	RoomId               int64           `protobuf:"varint,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	RoomName             string          `protobuf:"bytes,3,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	RoomUrl              string          `protobuf:"bytes,4,opt,name=room_url,json=roomUrl,proto3" json:"room_url,omitempty"`
	ShowStatus           ShowStatus      `protobuf:"varint,5,opt,name=show_status,json=showStatus,proto3,enum=douyu.ShowStatus" json:"show_status,omitempty"`
	VideoLoop            VideoLoopStatus `protobuf:"varint,6,opt,name=videoLoop,proto3,enum=douyu.VideoLoopStatus" json:"videoLoop,omitempty"`
	Avatar               *Avatar         `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *LiveInfo) Reset()         { *m = LiveInfo{} }
func (m *LiveInfo) String() string { return proto.CompactTextString(m) }
func (*LiveInfo) ProtoMessage()    {}
func (*LiveInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_50f0928b53cdacf8, []int{3}
}

func (m *LiveInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LiveInfo.Unmarshal(m, b)
}
func (m *LiveInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LiveInfo.Marshal(b, m, deterministic)
}
func (m *LiveInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiveInfo.Merge(m, src)
}
func (m *LiveInfo) XXX_Size() int {
	return xxx_messageInfo_LiveInfo.Size(m)
}
func (m *LiveInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LiveInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LiveInfo proto.InternalMessageInfo

func (m *LiveInfo) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *LiveInfo) GetRoomId() int64 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *LiveInfo) GetRoomName() string {
	if m != nil {
		return m.RoomName
	}
	return ""
}

func (m *LiveInfo) GetRoomUrl() string {
	if m != nil {
		return m.RoomUrl
	}
	return ""
}

func (m *LiveInfo) GetShowStatus() ShowStatus {
	if m != nil {
		return m.ShowStatus
	}
	return ShowStatus_Unknown
}

func (m *LiveInfo) GetVideoLoop() VideoLoopStatus {
	if m != nil {
		return m.VideoLoop
	}
	return VideoLoopStatus_Off
}

func (m *LiveInfo) GetAvatar() *Avatar {
	if m != nil {
		return m.Avatar
	}
	return nil
}

func init() {
	proto.RegisterEnum("douyu.ShowStatus", ShowStatus_name, ShowStatus_value)
	proto.RegisterEnum("douyu.VideoLoopStatus", VideoLoopStatus_name, VideoLoopStatus_value)
	proto.RegisterType((*Avatar)(nil), "douyu.Avatar")
	proto.RegisterType((*Room)(nil), "douyu.Room")
	proto.RegisterType((*BetardResponse)(nil), "douyu.BetardResponse")
	proto.RegisterType((*LiveInfo)(nil), "douyu.LiveInfo")
}

func init() {
	proto.RegisterFile("douyu.proto", fileDescriptor_50f0928b53cdacf8)
}

var fileDescriptor_50f0928b53cdacf8 = []byte{
	// 363 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x52, 0x4d, 0x6b, 0xe2, 0x50,
	0x14, 0x35, 0x89, 0xbe, 0xc4, 0x9b, 0x19, 0x27, 0x73, 0x19, 0x9c, 0xcc, 0xcc, 0x62, 0x24, 0x50,
	0x10, 0x17, 0x42, 0x63, 0xff, 0x40, 0x5d, 0x55, 0x10, 0x85, 0x88, 0x5d, 0x74, 0x23, 0xb1, 0x89,
	0xfa, 0x30, 0x79, 0x57, 0xf2, 0x25, 0xdd, 0x77, 0xd1, 0x9f, 0x5d, 0xf2, 0xf2, 0xaa, 0xd0, 0xbf,
	0xd0, 0xdd, 0x3d, 0xe7, 0xe4, 0x9c, 0x9b, 0x77, 0xb8, 0x60, 0x47, 0x54, 0xbe, 0x94, 0xe3, 0x53,
	0x46, 0x05, 0x61, 0x47, 0x02, 0xef, 0x01, 0xd8, 0x7d, 0x15, 0x16, 0x61, 0x86, 0x0e, 0x18, 0x5b,
	0xbe, 0x77, 0xb5, 0x81, 0x36, 0xec, 0x06, 0xf5, 0x88, 0x7d, 0x60, 0x29, 0x8f, 0xa2, 0x24, 0x76,
	0x75, 0x49, 0x2a, 0x84, 0xbf, 0xa0, 0x93, 0xa7, 0x61, 0x92, 0xb8, 0x86, 0xa4, 0x1b, 0xe0, 0xbd,
	0xea, 0xd0, 0x0e, 0x88, 0x52, 0xfc, 0x0b, 0x96, 0xe0, 0xcf, 0x47, 0x11, 0xa6, 0xb1, 0x4a, 0xbb,
	0x60, 0xfc, 0x0d, 0x66, 0x46, 0x94, 0x6e, 0x78, 0x24, 0x33, 0x8d, 0x80, 0xd5, 0x70, 0x16, 0xe1,
	0x3f, 0xe8, 0x4a, 0x41, 0xba, 0x9a, 0x5c, 0xab, 0x26, 0x16, 0xb5, 0xeb, 0x0f, 0xc8, 0x79, 0x53,
	0x66, 0x89, 0xdb, 0x96, 0x9a, 0x4c, 0x59, 0x67, 0x09, 0xfa, 0x60, 0xe7, 0x07, 0x3a, 0x6f, 0xf2,
	0x22, 0x2c, 0xca, 0xdc, 0xed, 0x0c, 0xb4, 0x61, 0xcf, 0xff, 0x39, 0x6e, 0x5e, 0xba, 0x3a, 0xd0,
	0x79, 0x25, 0x85, 0x00, 0xf2, 0xcb, 0x8c, 0x77, 0xd0, 0xad, 0x78, 0x14, 0xd3, 0x9c, 0xe8, 0xe4,
	0x32, 0xe9, 0xe8, 0x2b, 0xc7, 0xe3, 0x07, 0xaf, 0x6c, 0xd7, 0x0f, 0xf1, 0x06, 0x58, 0x28, 0x9b,
	0x72, 0xcd, 0x81, 0x36, 0xb4, 0xfd, 0xef, 0xca, 0xd2, 0xd4, 0x17, 0x28, 0xd1, 0xbb, 0x85, 0xde,
	0x34, 0x2e, 0xc2, 0x2c, 0x0a, 0xe2, 0xfc, 0x44, 0x22, 0x8f, 0xf1, 0x3f, 0xb4, 0xeb, 0xbf, 0x95,
	0x5d, 0xd8, 0xbe, 0xad, 0x6c, 0x75, 0x55, 0x81, 0x14, 0xbc, 0x37, 0x1d, 0xac, 0x39, 0xaf, 0xe2,
	0x99, 0xd8, 0xd1, 0xd7, 0x6e, 0x6f, 0x34, 0x01, 0xb8, 0xae, 0x45, 0x1b, 0xcc, 0xb5, 0x38, 0x0a,
	0x3a, 0x0b, 0xa7, 0x85, 0x00, 0x6c, 0xce, 0x2b, 0x2e, 0xf6, 0x8e, 0x86, 0xdf, 0xc0, 0x5a, 0x90,
	0x42, 0xfa, 0xc8, 0x83, 0x1f, 0x9f, 0x36, 0xa3, 0x09, 0xc6, 0x72, 0xb7, 0x73, 0x5a, 0xc8, 0x40,
	0x5f, 0x0a, 0x47, 0x9b, 0x9a, 0x4f, 0xcd, 0xc1, 0x6f, 0x99, 0x3c, 0xff, 0xc9, 0x7b, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x58, 0x1f, 0x48, 0x2b, 0x0d, 0x03, 0x00, 0x00,
}
