// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.23.1
// source: lsp/douyu/douyu.proto

package douyu

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShowStatus int32

const (
	ShowStatus_Unknown  ShowStatus = 0
	ShowStatus_Living   ShowStatus = 1
	ShowStatus_NoLiving ShowStatus = 2
)

// Enum value maps for ShowStatus.
var (
	ShowStatus_name = map[int32]string{
		0: "Unknown",
		1: "Living",
		2: "NoLiving",
	}
	ShowStatus_value = map[string]int32{
		"Unknown":  0,
		"Living":   1,
		"NoLiving": 2,
	}
)

func (x ShowStatus) Enum() *ShowStatus {
	p := new(ShowStatus)
	*p = x
	return p
}

func (x ShowStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShowStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_lsp_douyu_douyu_proto_enumTypes[0].Descriptor()
}

func (ShowStatus) Type() protoreflect.EnumType {
	return &file_lsp_douyu_douyu_proto_enumTypes[0]
}

func (x ShowStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShowStatus.Descriptor instead.
func (ShowStatus) EnumDescriptor() ([]byte, []int) {
	return file_lsp_douyu_douyu_proto_rawDescGZIP(), []int{0}
}

type VideoLoopStatus int32

const (
	VideoLoopStatus_Off VideoLoopStatus = 0
	VideoLoopStatus_On  VideoLoopStatus = 1
)

// Enum value maps for VideoLoopStatus.
var (
	VideoLoopStatus_name = map[int32]string{
		0: "Off",
		1: "On",
	}
	VideoLoopStatus_value = map[string]int32{
		"Off": 0,
		"On":  1,
	}
)

func (x VideoLoopStatus) Enum() *VideoLoopStatus {
	p := new(VideoLoopStatus)
	*p = x
	return p
}

func (x VideoLoopStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VideoLoopStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_lsp_douyu_douyu_proto_enumTypes[1].Descriptor()
}

func (VideoLoopStatus) Type() protoreflect.EnumType {
	return &file_lsp_douyu_douyu_proto_enumTypes[1]
}

func (x VideoLoopStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VideoLoopStatus.Descriptor instead.
func (VideoLoopStatus) EnumDescriptor() ([]byte, []int) {
	return file_lsp_douyu_douyu_proto_rawDescGZIP(), []int{1}
}

type Avatar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Big    string `protobuf:"bytes,1,opt,name=big,proto3" json:"big,omitempty"`
	Middle string `protobuf:"bytes,2,opt,name=middle,proto3" json:"middle,omitempty"`
	Small  string `protobuf:"bytes,3,opt,name=small,proto3" json:"small,omitempty"`
}

func (x *Avatar) Reset() {
	*x = Avatar{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lsp_douyu_douyu_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Avatar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Avatar) ProtoMessage() {}

func (x *Avatar) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_douyu_douyu_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Avatar.ProtoReflect.Descriptor instead.
func (*Avatar) Descriptor() ([]byte, []int) {
	return file_lsp_douyu_douyu_proto_rawDescGZIP(), []int{0}
}

func (x *Avatar) GetBig() string {
	if x != nil {
		return x.Big
	}
	return ""
}

func (x *Avatar) GetMiddle() string {
	if x != nil {
		return x.Middle
	}
	return ""
}

func (x *Avatar) GetSmall() string {
	if x != nil {
		return x.Small
	}
	return ""
}

type Room struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nickname   string          `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	RoomId     int64           `protobuf:"varint,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	RoomName   string          `protobuf:"bytes,3,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	RoomUrl    string          `protobuf:"bytes,4,opt,name=room_url,json=roomUrl,proto3" json:"room_url,omitempty"`
	ShowStatus ShowStatus      `protobuf:"varint,5,opt,name=show_status,json=showStatus,proto3,enum=douyu.ShowStatus" json:"show_status,omitempty"`
	VideoLoop  VideoLoopStatus `protobuf:"varint,6,opt,name=videoLoop,proto3,enum=douyu.VideoLoopStatus" json:"videoLoop,omitempty"`
	Avatar     *Avatar         `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar,omitempty"`
}

func (x *Room) Reset() {
	*x = Room{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lsp_douyu_douyu_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_douyu_douyu_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_lsp_douyu_douyu_proto_rawDescGZIP(), []int{1}
}

func (x *Room) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *Room) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *Room) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *Room) GetRoomUrl() string {
	if x != nil {
		return x.RoomUrl
	}
	return ""
}

func (x *Room) GetShowStatus() ShowStatus {
	if x != nil {
		return x.ShowStatus
	}
	return ShowStatus_Unknown
}

func (x *Room) GetVideoLoop() VideoLoopStatus {
	if x != nil {
		return x.VideoLoop
	}
	return VideoLoopStatus_Off
}

func (x *Room) GetAvatar() *Avatar {
	if x != nil {
		return x.Avatar
	}
	return nil
}

type BetardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Room *Room `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
}

func (x *BetardResponse) Reset() {
	*x = BetardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lsp_douyu_douyu_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BetardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BetardResponse) ProtoMessage() {}

func (x *BetardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_douyu_douyu_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BetardResponse.ProtoReflect.Descriptor instead.
func (*BetardResponse) Descriptor() ([]byte, []int) {
	return file_lsp_douyu_douyu_proto_rawDescGZIP(), []int{2}
}

func (x *BetardResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

var File_lsp_douyu_douyu_proto protoreflect.FileDescriptor

var file_lsp_douyu_douyu_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6c, 0x73, 0x70, 0x2f, 0x64, 0x6f, 0x75, 0x79, 0x75, 0x2f, 0x64, 0x6f, 0x75, 0x79,
	0x75, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x64, 0x6f, 0x75, 0x79, 0x75, 0x22, 0x48,
	0x0a, 0x06, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x69, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x62, 0x69, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x69,
	0x64, 0x64, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x69, 0x64, 0x64,
	0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x6d, 0x61, 0x6c, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x73, 0x6d, 0x61, 0x6c, 0x6c, 0x22, 0x84, 0x02, 0x0a, 0x04, 0x52, 0x6f, 0x6f,
	0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a,
	0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x75, 0x72, 0x6c, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x55, 0x72, 0x6c, 0x12, 0x32,
	0x0a, 0x0b, 0x73, 0x68, 0x6f, 0x77, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x64, 0x6f, 0x75, 0x79, 0x75, 0x2e, 0x53, 0x68, 0x6f, 0x77,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0a, 0x73, 0x68, 0x6f, 0x77, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x34, 0x0a, 0x09, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x4c, 0x6f, 0x6f, 0x70, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x64, 0x6f, 0x75, 0x79, 0x75, 0x2e, 0x56, 0x69,
	0x64, 0x65, 0x6f, 0x4c, 0x6f, 0x6f, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x09, 0x76,
	0x69, 0x64, 0x65, 0x6f, 0x4c, 0x6f, 0x6f, 0x70, 0x12, 0x25, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74,
	0x61, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x64, 0x6f, 0x75, 0x79, 0x75,
	0x2e, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x22,
	0x31, 0x0a, 0x0e, 0x42, 0x65, 0x74, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1f, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x64, 0x6f, 0x75, 0x79, 0x75, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x04, 0x72, 0x6f,
	0x6f, 0x6d, 0x2a, 0x33, 0x0a, 0x0a, 0x53, 0x68, 0x6f, 0x77, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x0b, 0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x0a, 0x0a,
	0x06, 0x4c, 0x69, 0x76, 0x69, 0x6e, 0x67, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x6f, 0x4c,
	0x69, 0x76, 0x69, 0x6e, 0x67, 0x10, 0x02, 0x2a, 0x22, 0x0a, 0x0f, 0x56, 0x69, 0x64, 0x65, 0x6f,
	0x4c, 0x6f, 0x6f, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x07, 0x0a, 0x03, 0x4f, 0x66,
	0x66, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x6e, 0x10, 0x01, 0x42, 0x0b, 0x5a, 0x09, 0x6c,
	0x73, 0x70, 0x2f, 0x64, 0x6f, 0x75, 0x79, 0x75, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lsp_douyu_douyu_proto_rawDescOnce sync.Once
	file_lsp_douyu_douyu_proto_rawDescData = file_lsp_douyu_douyu_proto_rawDesc
)

func file_lsp_douyu_douyu_proto_rawDescGZIP() []byte {
	file_lsp_douyu_douyu_proto_rawDescOnce.Do(func() {
		file_lsp_douyu_douyu_proto_rawDescData = protoimpl.X.CompressGZIP(file_lsp_douyu_douyu_proto_rawDescData)
	})
	return file_lsp_douyu_douyu_proto_rawDescData
}

var file_lsp_douyu_douyu_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_lsp_douyu_douyu_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_lsp_douyu_douyu_proto_goTypes = []interface{}{
	(ShowStatus)(0),        // 0: douyu.ShowStatus
	(VideoLoopStatus)(0),   // 1: douyu.VideoLoopStatus
	(*Avatar)(nil),         // 2: douyu.Avatar
	(*Room)(nil),           // 3: douyu.Room
	(*BetardResponse)(nil), // 4: douyu.BetardResponse
}
var file_lsp_douyu_douyu_proto_depIdxs = []int32{
	0, // 0: douyu.Room.show_status:type_name -> douyu.ShowStatus
	1, // 1: douyu.Room.videoLoop:type_name -> douyu.VideoLoopStatus
	2, // 2: douyu.Room.avatar:type_name -> douyu.Avatar
	3, // 3: douyu.BetardResponse.room:type_name -> douyu.Room
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_lsp_douyu_douyu_proto_init() }
func file_lsp_douyu_douyu_proto_init() {
	if File_lsp_douyu_douyu_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lsp_douyu_douyu_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Avatar); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lsp_douyu_douyu_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Room); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lsp_douyu_douyu_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BetardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lsp_douyu_douyu_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lsp_douyu_douyu_proto_goTypes,
		DependencyIndexes: file_lsp_douyu_douyu_proto_depIdxs,
		EnumInfos:         file_lsp_douyu_douyu_proto_enumTypes,
		MessageInfos:      file_lsp_douyu_douyu_proto_msgTypes,
	}.Build()
	File_lsp_douyu_douyu_proto = out.File
	file_lsp_douyu_douyu_proto_rawDesc = nil
	file_lsp_douyu_douyu_proto_goTypes = nil
	file_lsp_douyu_douyu_proto_depIdxs = nil
}
