package buntdb

import (
	"github.com/stretchr/testify/assert"
	"testing"
)

func TestKeys(t *testing.T) {
	ModeKey()
	BilibiliGroupConcernStateKey()
	BilibiliGroupConcernConfigKey()
	BilibliFreshKey()
	BilibiliCurrentLiveKey()
	BilibiliCurrentNewsKey()
	BilibiliDynamicIdKey()
	BilibiliUidFirstTimestampKey()
	BilibiliUserCookieInfoKey()
	BilibiliNotLiveCountKey()
	BilibiliUserInfoKey()
	BilibiliUserStatKey()
	BilibiliGroupAtAllMarkKey()
	BilibiliNotifyMsgKey()
	BilibiliCompactMarkKey()
	DouyuGroupConcernStateKey()
	DouyuGroupConcernConfigKey()
	DouyuFreshKey()
	DouyuCurrentLiveKey()
	DouyuGroupAtAllMarkKey()
	YoutubeGroupConcernStateKey()
	YoutubeGroupConcernConfigKey()
	YoutubeFreshKey()
	YoutubeUserInfoKey()
	YoutubeInfoKey()
	YoutubeVideoKey()
	YoutubeGroupAtAllMarkKey()
	HuyaGroupConcernStateKey()
	HuyaGroupConcernConfigKey()
	HuyaFreshKey()
	HuyaCurrentLiveKey()
	HuyaGroupAtAllMarkKey()
	PermissionKey()
	BlockListKey()
	GroupPermissionKey()
	GroupEnabledKey()
	GlobalEnabledKey()
	GroupMessageImageKey()
	GroupSilenceKey()
	GlobalSilenceKey()
	GroupMuteKey()
	GroupInvitorKey()
	LoliconPoolStoreKey()
	ImageCacheKey()
	ModeKey()
	NewFriendRequestKey()
	GroupInvitedKey()
	VersionKey()
	BilibiliLastFreshKey()
	AcfunLiveInfoKey()
	AcfunNotLiveKey()
	AcfunUidFirstTimestampKey()
	AcfunUserInfoKey()
	WeiboMarkMblogIdKey()
	WeiboNewsInfoKey()
	WeiboUserInfoKey()
	assert.Panics(t, func() {
		BilibiliGroupConcernStateKey(&struct{}{})
	})
	assert.Panics(t, func() {
		Key(nil)
	})
}
