package buntdb

import (
	"github.com/stretchr/testify/assert"
	"testing"
)

func TestKeys(t *testing.T) {
	ModeKey()
	BilibiliConcernStateKey()
	BilibiliConcernConfigKey()
	BilibliFreshKey()
	BilibiliCurrentLiveKey()
	BilibiliCurrentNewsKey()
	BilibiliDynamicIdKey()
	BilibiliUidFirstTimestampKey()
	BilibiliUserCookieInfoKey()
	BilibiliNotLiveCountKey()
	BilibiliUserInfoKey()
	BilibiliUserStatKey()
	BilibiliAtAllMarkKey()
	BilibiliNotifyMsgKey()
	BilibiliCompactMarkKey()
	DouyuConcernStateKey()
	DouyuConcernConfigKey()
	DouyuFreshKey()
	DouyuCurrentLiveKey()
	DouyuAtAllMarkKey()
	YoutubeConcernStateKey()
	YoutubeConcernConfigKey()
	YoutubeFreshKey()
	YoutubeUserInfoKey()
	YoutubeInfoKey()
	YoutubeVideoKey()
	YoutubeAtAllMarkKey()
	HuyaConcernStateKey()
	HuyaConcernConfigKey()
	HuyaFreshKey()
	HuyaCurrentLiveKey()
	HuyaAtAllMarkKey()
	PermissionKey()
	BlockListKey()
	TargetPermissionKey()
	TargetEnabledKey()
	GlobalEnabledKey()
	GroupMessageImageKey()
	TargetSilenceKey()
	GlobalSilenceKey()
	TargetMuteKey()
	GroupInvitorKey()
	LoliconPoolStoreKey()
	ImageCacheKey()
	ModeKey()
	NewFriendRequestKey()
	GroupInvitedKey()
	VersionKey()
	BilibiliLastFreshKey()
	AcfunLiveInfoKey()
	AcfunNotLiveKey()
	AcfunUidFirstTimestampKey()
	AcfunUserInfoKey()
	WeiboMarkMblogIdKey()
	WeiboNewsInfoKey()
	WeiboUserInfoKey()
	assert.Panics(t, func() {
		BilibiliConcernStateKey(&struct{}{})
	})
	assert.Panics(t, func() {
		Key(nil)
	})
}
