// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bilibili.proto

package bilibili

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LiveStatus int32

const (
	LiveStatus_NoLiving LiveStatus = 0
	LiveStatus_Living   LiveStatus = 1
)

var LiveStatus_name = map[int32]string{
	0: "NoLiving",
	1: "Living",
}

var LiveStatus_value = map[string]int32{
	"NoLiving": 0,
	"Living":   1,
}

func (x LiveStatus) String() string {
	return proto.EnumName(LiveStatus_name, int32(x))
}

func (LiveStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d0021bc90478bd43, []int{0}
}

type RoundStatus int32

const (
	RoundStatus_Off RoundStatus = 0
	RoundStatus_On  RoundStatus = 1
)

var RoundStatus_name = map[int32]string{
	0: "Off",
	1: "On",
}

var RoundStatus_value = map[string]int32{
	"Off": 0,
	"On":  1,
}

func (x RoundStatus) String() string {
	return proto.EnumName(RoundStatus_name, int32(x))
}

func (RoundStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d0021bc90478bd43, []int{1}
}

type RoomStatus int32

const (
	RoomStatus_NonExist RoomStatus = 0
	RoomStatus_Exist    RoomStatus = 1
)

var RoomStatus_name = map[int32]string{
	0: "NonExist",
	1: "Exist",
}

var RoomStatus_value = map[string]int32{
	"NonExist": 0,
	"Exist":    1,
}

func (x RoomStatus) String() string {
	return proto.EnumName(RoomStatus_name, int32(x))
}

func (RoomStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d0021bc90478bd43, []int{2}
}

type SpecialType int32

const (
	SpecialType_Normal       SpecialType = 0
	SpecialType_Pay          SpecialType = 1
	SpecialType_YearFestival SpecialType = 2
)

var SpecialType_name = map[int32]string{
	0: "Normal",
	1: "Pay",
	2: "YearFestival",
}

var SpecialType_value = map[string]int32{
	"Normal":       0,
	"Pay":          1,
	"YearFestival": 2,
}

func (x SpecialType) String() string {
	return proto.EnumName(SpecialType_name, int32(x))
}

func (SpecialType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d0021bc90478bd43, []int{3}
}

type DynamicDescType int32

const (
	DynamicDescType_Unknown    DynamicDescType = 0
	DynamicDescType_WithOrigin DynamicDescType = 1
	DynamicDescType_WithImage  DynamicDescType = 2
	DynamicDescType_TextOnly   DynamicDescType = 4
	DynamicDescType_WithVideo  DynamicDescType = 8
	DynamicDescType_WithPost   DynamicDescType = 64
	DynamicDescType_WithMusic  DynamicDescType = 256
)

var DynamicDescType_name = map[int32]string{
	0:   "Unknown",
	1:   "WithOrigin",
	2:   "WithImage",
	4:   "TextOnly",
	8:   "WithVideo",
	64:  "WithPost",
	256: "WithMusic",
}

var DynamicDescType_value = map[string]int32{
	"Unknown":    0,
	"WithOrigin": 1,
	"WithImage":  2,
	"TextOnly":   4,
	"WithVideo":  8,
	"WithPost":   64,
	"WithMusic":  256,
}

func (x DynamicDescType) String() string {
	return proto.EnumName(DynamicDescType_name, int32(x))
}

func (DynamicDescType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d0021bc90478bd43, []int{4}
}

type RoomInitResponse struct {
	Code                 int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *RoomInitResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *RoomInitResponse) Reset()         { *m = RoomInitResponse{} }
func (m *RoomInitResponse) String() string { return proto.CompactTextString(m) }
func (*RoomInitResponse) ProtoMessage()    {}
func (*RoomInitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0021bc90478bd43, []int{0}
}

func (m *RoomInitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomInitResponse.Unmarshal(m, b)
}
func (m *RoomInitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomInitResponse.Marshal(b, m, deterministic)
}
func (m *RoomInitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomInitResponse.Merge(m, src)
}
func (m *RoomInitResponse) XXX_Size() int {
	return xxx_messageInfo_RoomInitResponse.Size(m)
}
func (m *RoomInitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomInitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RoomInitResponse proto.InternalMessageInfo

func (m *RoomInitResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RoomInitResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RoomInitResponse) GetData() *RoomInitResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type RoomInitResponse_Data struct {
	RoomId               int64      `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ShortId              int64      `protobuf:"varint,2,opt,name=short_id,json=shortId,proto3" json:"short_id,omitempty"`
	Uid                  int64      `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	IsHidden             bool       `protobuf:"varint,5,opt,name=is_hidden,json=isHidden,proto3" json:"is_hidden,omitempty"`
	IsLocked             bool       `protobuf:"varint,6,opt,name=is_locked,json=isLocked,proto3" json:"is_locked,omitempty"`
	LiveStatus           LiveStatus `protobuf:"varint,8,opt,name=live_status,json=liveStatus,proto3,enum=bilibili.LiveStatus" json:"live_status,omitempty"`
	IsSp                 int32      `protobuf:"varint,15,opt,name=is_sp,json=isSp,proto3" json:"is_sp,omitempty"`
	SpecialType          int32      `protobuf:"varint,16,opt,name=special_type,json=specialType,proto3" json:"special_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RoomInitResponse_Data) Reset()         { *m = RoomInitResponse_Data{} }
func (m *RoomInitResponse_Data) String() string { return proto.CompactTextString(m) }
func (*RoomInitResponse_Data) ProtoMessage()    {}
func (*RoomInitResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0021bc90478bd43, []int{0, 0}
}

func (m *RoomInitResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomInitResponse_Data.Unmarshal(m, b)
}
func (m *RoomInitResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomInitResponse_Data.Marshal(b, m, deterministic)
}
func (m *RoomInitResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomInitResponse_Data.Merge(m, src)
}
func (m *RoomInitResponse_Data) XXX_Size() int {
	return xxx_messageInfo_RoomInitResponse_Data.Size(m)
}
func (m *RoomInitResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomInitResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_RoomInitResponse_Data proto.InternalMessageInfo

func (m *RoomInitResponse_Data) GetRoomId() int64 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *RoomInitResponse_Data) GetShortId() int64 {
	if m != nil {
		return m.ShortId
	}
	return 0
}

func (m *RoomInitResponse_Data) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *RoomInitResponse_Data) GetIsHidden() bool {
	if m != nil {
		return m.IsHidden
	}
	return false
}

func (m *RoomInitResponse_Data) GetIsLocked() bool {
	if m != nil {
		return m.IsLocked
	}
	return false
}

func (m *RoomInitResponse_Data) GetLiveStatus() LiveStatus {
	if m != nil {
		return m.LiveStatus
	}
	return LiveStatus_NoLiving
}

func (m *RoomInitResponse_Data) GetIsSp() int32 {
	if m != nil {
		return m.IsSp
	}
	return 0
}

func (m *RoomInitResponse_Data) GetSpecialType() int32 {
	if m != nil {
		return m.SpecialType
	}
	return 0
}

type XSpaceAccInfoResponse struct {
	Code                 int32                       `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string                      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *XSpaceAccInfoResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *XSpaceAccInfoResponse) Reset()         { *m = XSpaceAccInfoResponse{} }
func (m *XSpaceAccInfoResponse) String() string { return proto.CompactTextString(m) }
func (*XSpaceAccInfoResponse) ProtoMessage()    {}
func (*XSpaceAccInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0021bc90478bd43, []int{1}
}

func (m *XSpaceAccInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XSpaceAccInfoResponse.Unmarshal(m, b)
}
func (m *XSpaceAccInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XSpaceAccInfoResponse.Marshal(b, m, deterministic)
}
func (m *XSpaceAccInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XSpaceAccInfoResponse.Merge(m, src)
}
func (m *XSpaceAccInfoResponse) XXX_Size() int {
	return xxx_messageInfo_XSpaceAccInfoResponse.Size(m)
}
func (m *XSpaceAccInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_XSpaceAccInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_XSpaceAccInfoResponse proto.InternalMessageInfo

func (m *XSpaceAccInfoResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *XSpaceAccInfoResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *XSpaceAccInfoResponse) GetData() *XSpaceAccInfoResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type XSpaceAccInfoResponse_Data struct {
	Mid                  int64                                `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`
	Name                 string                               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Level                int32                                `protobuf:"varint,7,opt,name=level,proto3" json:"level,omitempty"`
	LiveRoom             *XSpaceAccInfoResponse_Data_LiveRoom `protobuf:"bytes,17,opt,name=live_room,json=liveRoom,proto3" json:"live_room,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *XSpaceAccInfoResponse_Data) Reset()         { *m = XSpaceAccInfoResponse_Data{} }
func (m *XSpaceAccInfoResponse_Data) String() string { return proto.CompactTextString(m) }
func (*XSpaceAccInfoResponse_Data) ProtoMessage()    {}
func (*XSpaceAccInfoResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0021bc90478bd43, []int{1, 0}
}

func (m *XSpaceAccInfoResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XSpaceAccInfoResponse_Data.Unmarshal(m, b)
}
func (m *XSpaceAccInfoResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XSpaceAccInfoResponse_Data.Marshal(b, m, deterministic)
}
func (m *XSpaceAccInfoResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XSpaceAccInfoResponse_Data.Merge(m, src)
}
func (m *XSpaceAccInfoResponse_Data) XXX_Size() int {
	return xxx_messageInfo_XSpaceAccInfoResponse_Data.Size(m)
}
func (m *XSpaceAccInfoResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_XSpaceAccInfoResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_XSpaceAccInfoResponse_Data proto.InternalMessageInfo

func (m *XSpaceAccInfoResponse_Data) GetMid() int64 {
	if m != nil {
		return m.Mid
	}
	return 0
}

func (m *XSpaceAccInfoResponse_Data) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *XSpaceAccInfoResponse_Data) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *XSpaceAccInfoResponse_Data) GetLiveRoom() *XSpaceAccInfoResponse_Data_LiveRoom {
	if m != nil {
		return m.LiveRoom
	}
	return nil
}

type XSpaceAccInfoResponse_Data_LiveRoom struct {
	RoomStatus           int32    `protobuf:"varint,1,opt,name=roomStatus,proto3" json:"roomStatus,omitempty"`
	LiveStatus           int32    `protobuf:"varint,2,opt,name=liveStatus,proto3" json:"liveStatus,omitempty"`
	Url                  string   `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Title                string   `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Cover                string   `protobuf:"bytes,5,opt,name=cover,proto3" json:"cover,omitempty"`
	Roomid               int64    `protobuf:"varint,6,opt,name=roomid,proto3" json:"roomid,omitempty"`
	RoundStatus          int32    `protobuf:"varint,7,opt,name=roundStatus,proto3" json:"roundStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XSpaceAccInfoResponse_Data_LiveRoom) Reset()         { *m = XSpaceAccInfoResponse_Data_LiveRoom{} }
func (m *XSpaceAccInfoResponse_Data_LiveRoom) String() string { return proto.CompactTextString(m) }
func (*XSpaceAccInfoResponse_Data_LiveRoom) ProtoMessage()    {}
func (*XSpaceAccInfoResponse_Data_LiveRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0021bc90478bd43, []int{1, 0, 0}
}

func (m *XSpaceAccInfoResponse_Data_LiveRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XSpaceAccInfoResponse_Data_LiveRoom.Unmarshal(m, b)
}
func (m *XSpaceAccInfoResponse_Data_LiveRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XSpaceAccInfoResponse_Data_LiveRoom.Marshal(b, m, deterministic)
}
func (m *XSpaceAccInfoResponse_Data_LiveRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XSpaceAccInfoResponse_Data_LiveRoom.Merge(m, src)
}
func (m *XSpaceAccInfoResponse_Data_LiveRoom) XXX_Size() int {
	return xxx_messageInfo_XSpaceAccInfoResponse_Data_LiveRoom.Size(m)
}
func (m *XSpaceAccInfoResponse_Data_LiveRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_XSpaceAccInfoResponse_Data_LiveRoom.DiscardUnknown(m)
}

var xxx_messageInfo_XSpaceAccInfoResponse_Data_LiveRoom proto.InternalMessageInfo

func (m *XSpaceAccInfoResponse_Data_LiveRoom) GetRoomStatus() int32 {
	if m != nil {
		return m.RoomStatus
	}
	return 0
}

func (m *XSpaceAccInfoResponse_Data_LiveRoom) GetLiveStatus() int32 {
	if m != nil {
		return m.LiveStatus
	}
	return 0
}

func (m *XSpaceAccInfoResponse_Data_LiveRoom) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *XSpaceAccInfoResponse_Data_LiveRoom) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *XSpaceAccInfoResponse_Data_LiveRoom) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

func (m *XSpaceAccInfoResponse_Data_LiveRoom) GetRoomid() int64 {
	if m != nil {
		return m.Roomid
	}
	return 0
}

func (m *XSpaceAccInfoResponse_Data_LiveRoom) GetRoundStatus() int32 {
	if m != nil {
		return m.RoundStatus
	}
	return 0
}

type GetRoomInfoOldResponse struct {
	Code                 int32                        `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string                       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *GetRoomInfoOldResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *GetRoomInfoOldResponse) Reset()         { *m = GetRoomInfoOldResponse{} }
func (m *GetRoomInfoOldResponse) String() string { return proto.CompactTextString(m) }
func (*GetRoomInfoOldResponse) ProtoMessage()    {}
func (*GetRoomInfoOldResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0021bc90478bd43, []int{2}
}

func (m *GetRoomInfoOldResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRoomInfoOldResponse.Unmarshal(m, b)
}
func (m *GetRoomInfoOldResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRoomInfoOldResponse.Marshal(b, m, deterministic)
}
func (m *GetRoomInfoOldResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRoomInfoOldResponse.Merge(m, src)
}
func (m *GetRoomInfoOldResponse) XXX_Size() int {
	return xxx_messageInfo_GetRoomInfoOldResponse.Size(m)
}
func (m *GetRoomInfoOldResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRoomInfoOldResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRoomInfoOldResponse proto.InternalMessageInfo

func (m *GetRoomInfoOldResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetRoomInfoOldResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetRoomInfoOldResponse) GetData() *GetRoomInfoOldResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetRoomInfoOldResponse_Data struct {
	RoomStatus           RoomStatus  `protobuf:"varint,1,opt,name=roomStatus,proto3,enum=bilibili.RoomStatus" json:"roomStatus,omitempty"`
	RoundStatus          RoundStatus `protobuf:"varint,2,opt,name=roundStatus,proto3,enum=bilibili.RoundStatus" json:"roundStatus,omitempty"`
	LiveStatus           LiveStatus  `protobuf:"varint,3,opt,name=liveStatus,proto3,enum=bilibili.LiveStatus" json:"liveStatus,omitempty"`
	Url                  string      `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Title                string      `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Cover                string      `protobuf:"bytes,6,opt,name=cover,proto3" json:"cover,omitempty"`
	Online               int64       `protobuf:"varint,7,opt,name=online,proto3" json:"online,omitempty"`
	Roomid               int64       `protobuf:"varint,8,opt,name=roomid,proto3" json:"roomid,omitempty"`
	BroadcastType        int32       `protobuf:"varint,9,opt,name=broadcast_type,json=broadcastType,proto3" json:"broadcast_type,omitempty"`
	OnlineHidden         int32       `protobuf:"varint,10,opt,name=online_hidden,json=onlineHidden,proto3" json:"online_hidden,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetRoomInfoOldResponse_Data) Reset()         { *m = GetRoomInfoOldResponse_Data{} }
func (m *GetRoomInfoOldResponse_Data) String() string { return proto.CompactTextString(m) }
func (*GetRoomInfoOldResponse_Data) ProtoMessage()    {}
func (*GetRoomInfoOldResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0021bc90478bd43, []int{2, 0}
}

func (m *GetRoomInfoOldResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRoomInfoOldResponse_Data.Unmarshal(m, b)
}
func (m *GetRoomInfoOldResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRoomInfoOldResponse_Data.Marshal(b, m, deterministic)
}
func (m *GetRoomInfoOldResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRoomInfoOldResponse_Data.Merge(m, src)
}
func (m *GetRoomInfoOldResponse_Data) XXX_Size() int {
	return xxx_messageInfo_GetRoomInfoOldResponse_Data.Size(m)
}
func (m *GetRoomInfoOldResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRoomInfoOldResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_GetRoomInfoOldResponse_Data proto.InternalMessageInfo

func (m *GetRoomInfoOldResponse_Data) GetRoomStatus() RoomStatus {
	if m != nil {
		return m.RoomStatus
	}
	return RoomStatus_NonExist
}

func (m *GetRoomInfoOldResponse_Data) GetRoundStatus() RoundStatus {
	if m != nil {
		return m.RoundStatus
	}
	return RoundStatus_Off
}

func (m *GetRoomInfoOldResponse_Data) GetLiveStatus() LiveStatus {
	if m != nil {
		return m.LiveStatus
	}
	return LiveStatus_NoLiving
}

func (m *GetRoomInfoOldResponse_Data) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *GetRoomInfoOldResponse_Data) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *GetRoomInfoOldResponse_Data) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

func (m *GetRoomInfoOldResponse_Data) GetOnline() int64 {
	if m != nil {
		return m.Online
	}
	return 0
}

func (m *GetRoomInfoOldResponse_Data) GetRoomid() int64 {
	if m != nil {
		return m.Roomid
	}
	return 0
}

func (m *GetRoomInfoOldResponse_Data) GetBroadcastType() int32 {
	if m != nil {
		return m.BroadcastType
	}
	return 0
}

func (m *GetRoomInfoOldResponse_Data) GetOnlineHidden() int32 {
	if m != nil {
		return m.OnlineHidden
	}
	return 0
}

type DynamicSvrSpaceHistoryResponse struct {
	Code                 int32                                `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string                               `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *DynamicSvrSpaceHistoryResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *DynamicSvrSpaceHistoryResponse) Reset()         { *m = DynamicSvrSpaceHistoryResponse{} }
func (m *DynamicSvrSpaceHistoryResponse) String() string { return proto.CompactTextString(m) }
func (*DynamicSvrSpaceHistoryResponse) ProtoMessage()    {}
func (*DynamicSvrSpaceHistoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0021bc90478bd43, []int{3}
}

func (m *DynamicSvrSpaceHistoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DynamicSvrSpaceHistoryResponse.Unmarshal(m, b)
}
func (m *DynamicSvrSpaceHistoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DynamicSvrSpaceHistoryResponse.Marshal(b, m, deterministic)
}
func (m *DynamicSvrSpaceHistoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DynamicSvrSpaceHistoryResponse.Merge(m, src)
}
func (m *DynamicSvrSpaceHistoryResponse) XXX_Size() int {
	return xxx_messageInfo_DynamicSvrSpaceHistoryResponse.Size(m)
}
func (m *DynamicSvrSpaceHistoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DynamicSvrSpaceHistoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DynamicSvrSpaceHistoryResponse proto.InternalMessageInfo

func (m *DynamicSvrSpaceHistoryResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DynamicSvrSpaceHistoryResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *DynamicSvrSpaceHistoryResponse) GetData() *DynamicSvrSpaceHistoryResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type DynamicSvrSpaceHistoryResponse_Data struct {
	Cards                []*DynamicSvrSpaceHistoryResponse_Data_Card `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	HasMore              int32                                       `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	NextOffset           int64                                       `protobuf:"varint,3,opt,name=next_offset,json=nextOffset,proto3" json:"next_offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                    `json:"-"`
	XXX_unrecognized     []byte                                      `json:"-"`
	XXX_sizecache        int32                                       `json:"-"`
}

func (m *DynamicSvrSpaceHistoryResponse_Data) Reset()         { *m = DynamicSvrSpaceHistoryResponse_Data{} }
func (m *DynamicSvrSpaceHistoryResponse_Data) String() string { return proto.CompactTextString(m) }
func (*DynamicSvrSpaceHistoryResponse_Data) ProtoMessage()    {}
func (*DynamicSvrSpaceHistoryResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0021bc90478bd43, []int{3, 0}
}

func (m *DynamicSvrSpaceHistoryResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DynamicSvrSpaceHistoryResponse_Data.Unmarshal(m, b)
}
func (m *DynamicSvrSpaceHistoryResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DynamicSvrSpaceHistoryResponse_Data.Marshal(b, m, deterministic)
}
func (m *DynamicSvrSpaceHistoryResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DynamicSvrSpaceHistoryResponse_Data.Merge(m, src)
}
func (m *DynamicSvrSpaceHistoryResponse_Data) XXX_Size() int {
	return xxx_messageInfo_DynamicSvrSpaceHistoryResponse_Data.Size(m)
}
func (m *DynamicSvrSpaceHistoryResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_DynamicSvrSpaceHistoryResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_DynamicSvrSpaceHistoryResponse_Data proto.InternalMessageInfo

func (m *DynamicSvrSpaceHistoryResponse_Data) GetCards() []*DynamicSvrSpaceHistoryResponse_Data_Card {
	if m != nil {
		return m.Cards
	}
	return nil
}

func (m *DynamicSvrSpaceHistoryResponse_Data) GetHasMore() int32 {
	if m != nil {
		return m.HasMore
	}
	return 0
}

func (m *DynamicSvrSpaceHistoryResponse_Data) GetNextOffset() int64 {
	if m != nil {
		return m.NextOffset
	}
	return 0
}

type DynamicSvrSpaceHistoryResponse_Data_Card struct {
	Card                 string                                            `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	Desc                 *DynamicSvrSpaceHistoryResponse_Data_Card_Desc    `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	Extra                *DynamicSvrSpaceHistoryResponse_Data_Card_Extra   `protobuf:"bytes,5,opt,name=extra,proto3" json:"extra,omitempty"`
	Display              *DynamicSvrSpaceHistoryResponse_Data_Card_Display `protobuf:"bytes,6,opt,name=display,proto3" json:"display,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                          `json:"-"`
	XXX_unrecognized     []byte                                            `json:"-"`
	XXX_sizecache        int32                                             `json:"-"`
}

func (m *DynamicSvrSpaceHistoryResponse_Data_Card) Reset() {
	*m = DynamicSvrSpaceHistoryResponse_Data_Card{}
}
func (m *DynamicSvrSpaceHistoryResponse_Data_Card) String() string { return proto.CompactTextString(m) }
func (*DynamicSvrSpaceHistoryResponse_Data_Card) ProtoMessage()    {}
func (*DynamicSvrSpaceHistoryResponse_Data_Card) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0021bc90478bd43, []int{3, 0, 0}
}

func (m *DynamicSvrSpaceHistoryResponse_Data_Card) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DynamicSvrSpaceHistoryResponse_Data_Card.Unmarshal(m, b)
}
func (m *DynamicSvrSpaceHistoryResponse_Data_Card) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DynamicSvrSpaceHistoryResponse_Data_Card.Marshal(b, m, deterministic)
}
func (m *DynamicSvrSpaceHistoryResponse_Data_Card) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DynamicSvrSpaceHistoryResponse_Data_Card.Merge(m, src)
}
func (m *DynamicSvrSpaceHistoryResponse_Data_Card) XXX_Size() int {
	return xxx_messageInfo_DynamicSvrSpaceHistoryResponse_Data_Card.Size(m)
}
func (m *DynamicSvrSpaceHistoryResponse_Data_Card) XXX_DiscardUnknown() {
	xxx_messageInfo_DynamicSvrSpaceHistoryResponse_Data_Card.DiscardUnknown(m)
}

var xxx_messageInfo_DynamicSvrSpaceHistoryResponse_Data_Card proto.InternalMessageInfo

func (m *DynamicSvrSpaceHistoryResponse_Data_Card) GetCard() string {
	if m != nil {
		return m.Card
	}
	return ""
}

func (m *DynamicSvrSpaceHistoryResponse_Data_Card) GetDesc() *DynamicSvrSpaceHistoryResponse_Data_Card_Desc {
	if m != nil {
		return m.Desc
	}
	return nil
}

func (m *DynamicSvrSpaceHistoryResponse_Data_Card) GetExtra() *DynamicSvrSpaceHistoryResponse_Data_Card_Extra {
	if m != nil {
		return m.Extra
	}
	return nil
}

func (m *DynamicSvrSpaceHistoryResponse_Data_Card) GetDisplay() *DynamicSvrSpaceHistoryResponse_Data_Card_Display {
	if m != nil {
		return m.Display
	}
	return nil
}

type DynamicSvrSpaceHistoryResponse_Data_Card_Desc struct {
	DynamicId            int64           `protobuf:"varint,1,opt,name=dynamic_id,json=dynamicId,proto3" json:"dynamic_id,omitempty"`
	OrigDyId             int64           `protobuf:"varint,2,opt,name=orig_dy_id,json=origDyId,proto3" json:"orig_dy_id,omitempty"`
	OrigType             DynamicDescType `protobuf:"varint,3,opt,name=orig_type,json=origType,proto3,enum=bilibili.DynamicDescType" json:"orig_type,omitempty"`
	PreDyId              int64           `protobuf:"varint,4,opt,name=pre_dy_id,json=preDyId,proto3" json:"pre_dy_id,omitempty"`
	Comment              int32           `protobuf:"varint,5,opt,name=comment,proto3" json:"comment,omitempty"`
	Like                 int32           `protobuf:"varint,6,opt,name=like,proto3" json:"like,omitempty"`
	View                 int32           `protobuf:"varint,7,opt,name=view,proto3" json:"view,omitempty"`
	Repost               int32           `protobuf:"varint,8,opt,name=repost,proto3" json:"repost,omitempty"`
	Timestamp            int32           `protobuf:"varint,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Type                 DynamicDescType `protobuf:"varint,10,opt,name=type,proto3,enum=bilibili.DynamicDescType" json:"type,omitempty"`
	Bvid                 string          `protobuf:"bytes,11,opt,name=bvid,proto3" json:"bvid,omitempty"`
	DynamicIdStr         string          `protobuf:"bytes,12,opt,name=dynamic_id_str,json=dynamicIdStr,proto3" json:"dynamic_id_str,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Desc) Reset() {
	*m = DynamicSvrSpaceHistoryResponse_Data_Card_Desc{}
}
func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Desc) String() string {
	return proto.CompactTextString(m)
}
func (*DynamicSvrSpaceHistoryResponse_Data_Card_Desc) ProtoMessage() {}
func (*DynamicSvrSpaceHistoryResponse_Data_Card_Desc) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0021bc90478bd43, []int{3, 0, 0, 0}
}

func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Desc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DynamicSvrSpaceHistoryResponse_Data_Card_Desc.Unmarshal(m, b)
}
func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Desc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DynamicSvrSpaceHistoryResponse_Data_Card_Desc.Marshal(b, m, deterministic)
}
func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Desc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DynamicSvrSpaceHistoryResponse_Data_Card_Desc.Merge(m, src)
}
func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Desc) XXX_Size() int {
	return xxx_messageInfo_DynamicSvrSpaceHistoryResponse_Data_Card_Desc.Size(m)
}
func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Desc) XXX_DiscardUnknown() {
	xxx_messageInfo_DynamicSvrSpaceHistoryResponse_Data_Card_Desc.DiscardUnknown(m)
}

var xxx_messageInfo_DynamicSvrSpaceHistoryResponse_Data_Card_Desc proto.InternalMessageInfo

func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Desc) GetDynamicId() int64 {
	if m != nil {
		return m.DynamicId
	}
	return 0
}

func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Desc) GetOrigDyId() int64 {
	if m != nil {
		return m.OrigDyId
	}
	return 0
}

func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Desc) GetOrigType() DynamicDescType {
	if m != nil {
		return m.OrigType
	}
	return DynamicDescType_Unknown
}

func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Desc) GetPreDyId() int64 {
	if m != nil {
		return m.PreDyId
	}
	return 0
}

func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Desc) GetComment() int32 {
	if m != nil {
		return m.Comment
	}
	return 0
}

func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Desc) GetLike() int32 {
	if m != nil {
		return m.Like
	}
	return 0
}

func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Desc) GetView() int32 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Desc) GetRepost() int32 {
	if m != nil {
		return m.Repost
	}
	return 0
}

func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Desc) GetTimestamp() int32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Desc) GetType() DynamicDescType {
	if m != nil {
		return m.Type
	}
	return DynamicDescType_Unknown
}

func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Desc) GetBvid() string {
	if m != nil {
		return m.Bvid
	}
	return ""
}

func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Desc) GetDynamicIdStr() string {
	if m != nil {
		return m.DynamicIdStr
	}
	return ""
}

type DynamicSvrSpaceHistoryResponse_Data_Card_Extra struct {
	IsSpaceTop           int32    `protobuf:"varint,1,opt,name=is_space_top,json=isSpaceTop,proto3" json:"is_space_top,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Extra) Reset() {
	*m = DynamicSvrSpaceHistoryResponse_Data_Card_Extra{}
}
func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Extra) String() string {
	return proto.CompactTextString(m)
}
func (*DynamicSvrSpaceHistoryResponse_Data_Card_Extra) ProtoMessage() {}
func (*DynamicSvrSpaceHistoryResponse_Data_Card_Extra) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0021bc90478bd43, []int{3, 0, 0, 1}
}

func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Extra) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DynamicSvrSpaceHistoryResponse_Data_Card_Extra.Unmarshal(m, b)
}
func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Extra) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DynamicSvrSpaceHistoryResponse_Data_Card_Extra.Marshal(b, m, deterministic)
}
func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Extra) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DynamicSvrSpaceHistoryResponse_Data_Card_Extra.Merge(m, src)
}
func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Extra) XXX_Size() int {
	return xxx_messageInfo_DynamicSvrSpaceHistoryResponse_Data_Card_Extra.Size(m)
}
func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Extra) XXX_DiscardUnknown() {
	xxx_messageInfo_DynamicSvrSpaceHistoryResponse_Data_Card_Extra.DiscardUnknown(m)
}

var xxx_messageInfo_DynamicSvrSpaceHistoryResponse_Data_Card_Extra proto.InternalMessageInfo

func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Extra) GetIsSpaceTop() int32 {
	if m != nil {
		return m.IsSpaceTop
	}
	return 0
}

type DynamicSvrSpaceHistoryResponse_Data_Card_Display struct {
	EmojiInfo            *DynamicSvrSpaceHistoryResponse_Data_Card_Display_EmojiInfo `protobuf:"bytes,1,opt,name=emoji_info,json=emojiInfo,proto3" json:"emoji_info,omitempty"`
	Origin               *DynamicSvrSpaceHistoryResponse_Data_Card_Display_Origin    `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                    `json:"-"`
	XXX_unrecognized     []byte                                                      `json:"-"`
	XXX_sizecache        int32                                                       `json:"-"`
}

func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Display) Reset() {
	*m = DynamicSvrSpaceHistoryResponse_Data_Card_Display{}
}
func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Display) String() string {
	return proto.CompactTextString(m)
}
func (*DynamicSvrSpaceHistoryResponse_Data_Card_Display) ProtoMessage() {}
func (*DynamicSvrSpaceHistoryResponse_Data_Card_Display) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0021bc90478bd43, []int{3, 0, 0, 2}
}

func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Display) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DynamicSvrSpaceHistoryResponse_Data_Card_Display.Unmarshal(m, b)
}
func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Display) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DynamicSvrSpaceHistoryResponse_Data_Card_Display.Marshal(b, m, deterministic)
}
func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Display) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DynamicSvrSpaceHistoryResponse_Data_Card_Display.Merge(m, src)
}
func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Display) XXX_Size() int {
	return xxx_messageInfo_DynamicSvrSpaceHistoryResponse_Data_Card_Display.Size(m)
}
func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Display) XXX_DiscardUnknown() {
	xxx_messageInfo_DynamicSvrSpaceHistoryResponse_Data_Card_Display.DiscardUnknown(m)
}

var xxx_messageInfo_DynamicSvrSpaceHistoryResponse_Data_Card_Display proto.InternalMessageInfo

func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Display) GetEmojiInfo() *DynamicSvrSpaceHistoryResponse_Data_Card_Display_EmojiInfo {
	if m != nil {
		return m.EmojiInfo
	}
	return nil
}

func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Display) GetOrigin() *DynamicSvrSpaceHistoryResponse_Data_Card_Display_Origin {
	if m != nil {
		return m.Origin
	}
	return nil
}

type DynamicSvrSpaceHistoryResponse_Data_Card_Display_EmojiInfo struct {
	EmojiDetails         []*DynamicSvrSpaceHistoryResponse_Data_Card_Display_EmojiInfo_EmojiDetail `protobuf:"bytes,1,rep,name=emoji_details,json=emojiDetails,proto3" json:"emoji_details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                                  `json:"-"`
	XXX_unrecognized     []byte                                                                    `json:"-"`
	XXX_sizecache        int32                                                                     `json:"-"`
}

func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Display_EmojiInfo) Reset() {
	*m = DynamicSvrSpaceHistoryResponse_Data_Card_Display_EmojiInfo{}
}
func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Display_EmojiInfo) String() string {
	return proto.CompactTextString(m)
}
func (*DynamicSvrSpaceHistoryResponse_Data_Card_Display_EmojiInfo) ProtoMessage() {}
func (*DynamicSvrSpaceHistoryResponse_Data_Card_Display_EmojiInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0021bc90478bd43, []int{3, 0, 0, 2, 0}
}

func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Display_EmojiInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DynamicSvrSpaceHistoryResponse_Data_Card_Display_EmojiInfo.Unmarshal(m, b)
}
func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Display_EmojiInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DynamicSvrSpaceHistoryResponse_Data_Card_Display_EmojiInfo.Marshal(b, m, deterministic)
}
func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Display_EmojiInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DynamicSvrSpaceHistoryResponse_Data_Card_Display_EmojiInfo.Merge(m, src)
}
func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Display_EmojiInfo) XXX_Size() int {
	return xxx_messageInfo_DynamicSvrSpaceHistoryResponse_Data_Card_Display_EmojiInfo.Size(m)
}
func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Display_EmojiInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DynamicSvrSpaceHistoryResponse_Data_Card_Display_EmojiInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DynamicSvrSpaceHistoryResponse_Data_Card_Display_EmojiInfo proto.InternalMessageInfo

func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Display_EmojiInfo) GetEmojiDetails() []*DynamicSvrSpaceHistoryResponse_Data_Card_Display_EmojiInfo_EmojiDetail {
	if m != nil {
		return m.EmojiDetails
	}
	return nil
}

type DynamicSvrSpaceHistoryResponse_Data_Card_Display_EmojiInfo_EmojiDetail struct {
	EmojiName            string   `protobuf:"bytes,1,opt,name=emoji_name,json=emojiName,proto3" json:"emoji_name,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	PackageId            int32    `protobuf:"varint,3,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	State                int32    `protobuf:"varint,4,opt,name=state,proto3" json:"state,omitempty"`
	Type                 int32    `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	Text                 string   `protobuf:"bytes,6,opt,name=text,proto3" json:"text,omitempty"`
	Url                  string   `protobuf:"bytes,7,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Display_EmojiInfo_EmojiDetail) Reset() {
	*m = DynamicSvrSpaceHistoryResponse_Data_Card_Display_EmojiInfo_EmojiDetail{}
}
func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Display_EmojiInfo_EmojiDetail) String() string {
	return proto.CompactTextString(m)
}
func (*DynamicSvrSpaceHistoryResponse_Data_Card_Display_EmojiInfo_EmojiDetail) ProtoMessage() {}
func (*DynamicSvrSpaceHistoryResponse_Data_Card_Display_EmojiInfo_EmojiDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0021bc90478bd43, []int{3, 0, 0, 2, 0, 0}
}

func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Display_EmojiInfo_EmojiDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DynamicSvrSpaceHistoryResponse_Data_Card_Display_EmojiInfo_EmojiDetail.Unmarshal(m, b)
}
func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Display_EmojiInfo_EmojiDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DynamicSvrSpaceHistoryResponse_Data_Card_Display_EmojiInfo_EmojiDetail.Marshal(b, m, deterministic)
}
func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Display_EmojiInfo_EmojiDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DynamicSvrSpaceHistoryResponse_Data_Card_Display_EmojiInfo_EmojiDetail.Merge(m, src)
}
func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Display_EmojiInfo_EmojiDetail) XXX_Size() int {
	return xxx_messageInfo_DynamicSvrSpaceHistoryResponse_Data_Card_Display_EmojiInfo_EmojiDetail.Size(m)
}
func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Display_EmojiInfo_EmojiDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_DynamicSvrSpaceHistoryResponse_Data_Card_Display_EmojiInfo_EmojiDetail.DiscardUnknown(m)
}

var xxx_messageInfo_DynamicSvrSpaceHistoryResponse_Data_Card_Display_EmojiInfo_EmojiDetail proto.InternalMessageInfo

func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Display_EmojiInfo_EmojiDetail) GetEmojiName() string {
	if m != nil {
		return m.EmojiName
	}
	return ""
}

func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Display_EmojiInfo_EmojiDetail) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Display_EmojiInfo_EmojiDetail) GetPackageId() int32 {
	if m != nil {
		return m.PackageId
	}
	return 0
}

func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Display_EmojiInfo_EmojiDetail) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Display_EmojiInfo_EmojiDetail) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Display_EmojiInfo_EmojiDetail) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Display_EmojiInfo_EmojiDetail) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type DynamicSvrSpaceHistoryResponse_Data_Card_Display_Origin struct {
	EmojiInfo            *DynamicSvrSpaceHistoryResponse_Data_Card_Display_EmojiInfo `protobuf:"bytes,1,opt,name=emoji_info,json=emojiInfo,proto3" json:"emoji_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                    `json:"-"`
	XXX_unrecognized     []byte                                                      `json:"-"`
	XXX_sizecache        int32                                                       `json:"-"`
}

func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Display_Origin) Reset() {
	*m = DynamicSvrSpaceHistoryResponse_Data_Card_Display_Origin{}
}
func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Display_Origin) String() string {
	return proto.CompactTextString(m)
}
func (*DynamicSvrSpaceHistoryResponse_Data_Card_Display_Origin) ProtoMessage() {}
func (*DynamicSvrSpaceHistoryResponse_Data_Card_Display_Origin) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0021bc90478bd43, []int{3, 0, 0, 2, 1}
}

func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Display_Origin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DynamicSvrSpaceHistoryResponse_Data_Card_Display_Origin.Unmarshal(m, b)
}
func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Display_Origin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DynamicSvrSpaceHistoryResponse_Data_Card_Display_Origin.Marshal(b, m, deterministic)
}
func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Display_Origin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DynamicSvrSpaceHistoryResponse_Data_Card_Display_Origin.Merge(m, src)
}
func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Display_Origin) XXX_Size() int {
	return xxx_messageInfo_DynamicSvrSpaceHistoryResponse_Data_Card_Display_Origin.Size(m)
}
func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Display_Origin) XXX_DiscardUnknown() {
	xxx_messageInfo_DynamicSvrSpaceHistoryResponse_Data_Card_Display_Origin.DiscardUnknown(m)
}

var xxx_messageInfo_DynamicSvrSpaceHistoryResponse_Data_Card_Display_Origin proto.InternalMessageInfo

func (m *DynamicSvrSpaceHistoryResponse_Data_Card_Display_Origin) GetEmojiInfo() *DynamicSvrSpaceHistoryResponse_Data_Card_Display_EmojiInfo {
	if m != nil {
		return m.EmojiInfo
	}
	return nil
}

type CardWithImage struct {
	Item                 *CardWithImage_Item `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *CardWithImage) Reset()         { *m = CardWithImage{} }
func (m *CardWithImage) String() string { return proto.CompactTextString(m) }
func (*CardWithImage) ProtoMessage()    {}
func (*CardWithImage) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0021bc90478bd43, []int{4}
}

func (m *CardWithImage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardWithImage.Unmarshal(m, b)
}
func (m *CardWithImage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardWithImage.Marshal(b, m, deterministic)
}
func (m *CardWithImage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardWithImage.Merge(m, src)
}
func (m *CardWithImage) XXX_Size() int {
	return xxx_messageInfo_CardWithImage.Size(m)
}
func (m *CardWithImage) XXX_DiscardUnknown() {
	xxx_messageInfo_CardWithImage.DiscardUnknown(m)
}

var xxx_messageInfo_CardWithImage proto.InternalMessageInfo

func (m *CardWithImage) GetItem() *CardWithImage_Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type CardWithImage_Item struct {
	Id                   int64                         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string                        `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string                        `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category             string                        `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Pictures             []*CardWithImage_Item_Picture `protobuf:"bytes,5,rep,name=pictures,proto3" json:"pictures,omitempty"`
	PicturesCount        int32                         `protobuf:"varint,6,opt,name=pictures_count,json=picturesCount,proto3" json:"pictures_count,omitempty"`
	UploadTime           int64                         `protobuf:"varint,7,opt,name=upload_time,json=uploadTime,proto3" json:"upload_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *CardWithImage_Item) Reset()         { *m = CardWithImage_Item{} }
func (m *CardWithImage_Item) String() string { return proto.CompactTextString(m) }
func (*CardWithImage_Item) ProtoMessage()    {}
func (*CardWithImage_Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0021bc90478bd43, []int{4, 0}
}

func (m *CardWithImage_Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardWithImage_Item.Unmarshal(m, b)
}
func (m *CardWithImage_Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardWithImage_Item.Marshal(b, m, deterministic)
}
func (m *CardWithImage_Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardWithImage_Item.Merge(m, src)
}
func (m *CardWithImage_Item) XXX_Size() int {
	return xxx_messageInfo_CardWithImage_Item.Size(m)
}
func (m *CardWithImage_Item) XXX_DiscardUnknown() {
	xxx_messageInfo_CardWithImage_Item.DiscardUnknown(m)
}

var xxx_messageInfo_CardWithImage_Item proto.InternalMessageInfo

func (m *CardWithImage_Item) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CardWithImage_Item) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CardWithImage_Item) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CardWithImage_Item) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *CardWithImage_Item) GetPictures() []*CardWithImage_Item_Picture {
	if m != nil {
		return m.Pictures
	}
	return nil
}

func (m *CardWithImage_Item) GetPicturesCount() int32 {
	if m != nil {
		return m.PicturesCount
	}
	return 0
}

func (m *CardWithImage_Item) GetUploadTime() int64 {
	if m != nil {
		return m.UploadTime
	}
	return 0
}

type CardWithImage_Item_Picture struct {
	ImgSrc               string   `protobuf:"bytes,1,opt,name=img_src,json=imgSrc,proto3" json:"img_src,omitempty"`
	ImgWidth             int32    `protobuf:"varint,2,opt,name=img_width,json=imgWidth,proto3" json:"img_width,omitempty"`
	ImgHeight            int32    `protobuf:"varint,3,opt,name=img_height,json=imgHeight,proto3" json:"img_height,omitempty"`
	ImgSize              float32  `protobuf:"fixed32,4,opt,name=img_size,json=imgSize,proto3" json:"img_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CardWithImage_Item_Picture) Reset()         { *m = CardWithImage_Item_Picture{} }
func (m *CardWithImage_Item_Picture) String() string { return proto.CompactTextString(m) }
func (*CardWithImage_Item_Picture) ProtoMessage()    {}
func (*CardWithImage_Item_Picture) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0021bc90478bd43, []int{4, 0, 0}
}

func (m *CardWithImage_Item_Picture) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardWithImage_Item_Picture.Unmarshal(m, b)
}
func (m *CardWithImage_Item_Picture) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardWithImage_Item_Picture.Marshal(b, m, deterministic)
}
func (m *CardWithImage_Item_Picture) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardWithImage_Item_Picture.Merge(m, src)
}
func (m *CardWithImage_Item_Picture) XXX_Size() int {
	return xxx_messageInfo_CardWithImage_Item_Picture.Size(m)
}
func (m *CardWithImage_Item_Picture) XXX_DiscardUnknown() {
	xxx_messageInfo_CardWithImage_Item_Picture.DiscardUnknown(m)
}

var xxx_messageInfo_CardWithImage_Item_Picture proto.InternalMessageInfo

func (m *CardWithImage_Item_Picture) GetImgSrc() string {
	if m != nil {
		return m.ImgSrc
	}
	return ""
}

func (m *CardWithImage_Item_Picture) GetImgWidth() int32 {
	if m != nil {
		return m.ImgWidth
	}
	return 0
}

func (m *CardWithImage_Item_Picture) GetImgHeight() int32 {
	if m != nil {
		return m.ImgHeight
	}
	return 0
}

func (m *CardWithImage_Item_Picture) GetImgSize() float32 {
	if m != nil {
		return m.ImgSize
	}
	return 0
}

type CardWithOrig struct {
	Item                 *CardWithOrig_Item       `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	Origin               string                   `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	OriginUser           *CardWithOrig_OriginUser `protobuf:"bytes,3,opt,name=origin_user,json=originUser,proto3" json:"origin_user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *CardWithOrig) Reset()         { *m = CardWithOrig{} }
func (m *CardWithOrig) String() string { return proto.CompactTextString(m) }
func (*CardWithOrig) ProtoMessage()    {}
func (*CardWithOrig) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0021bc90478bd43, []int{5}
}

func (m *CardWithOrig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardWithOrig.Unmarshal(m, b)
}
func (m *CardWithOrig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardWithOrig.Marshal(b, m, deterministic)
}
func (m *CardWithOrig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardWithOrig.Merge(m, src)
}
func (m *CardWithOrig) XXX_Size() int {
	return xxx_messageInfo_CardWithOrig.Size(m)
}
func (m *CardWithOrig) XXX_DiscardUnknown() {
	xxx_messageInfo_CardWithOrig.DiscardUnknown(m)
}

var xxx_messageInfo_CardWithOrig proto.InternalMessageInfo

func (m *CardWithOrig) GetItem() *CardWithOrig_Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *CardWithOrig) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *CardWithOrig) GetOriginUser() *CardWithOrig_OriginUser {
	if m != nil {
		return m.OriginUser
	}
	return nil
}

type CardWithOrig_Item struct {
	Content              string          `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp            int64           `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	OrigType             DynamicDescType `protobuf:"varint,3,opt,name=orig_type,json=origType,proto3,enum=bilibili.DynamicDescType" json:"orig_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CardWithOrig_Item) Reset()         { *m = CardWithOrig_Item{} }
func (m *CardWithOrig_Item) String() string { return proto.CompactTextString(m) }
func (*CardWithOrig_Item) ProtoMessage()    {}
func (*CardWithOrig_Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0021bc90478bd43, []int{5, 0}
}

func (m *CardWithOrig_Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardWithOrig_Item.Unmarshal(m, b)
}
func (m *CardWithOrig_Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardWithOrig_Item.Marshal(b, m, deterministic)
}
func (m *CardWithOrig_Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardWithOrig_Item.Merge(m, src)
}
func (m *CardWithOrig_Item) XXX_Size() int {
	return xxx_messageInfo_CardWithOrig_Item.Size(m)
}
func (m *CardWithOrig_Item) XXX_DiscardUnknown() {
	xxx_messageInfo_CardWithOrig_Item.DiscardUnknown(m)
}

var xxx_messageInfo_CardWithOrig_Item proto.InternalMessageInfo

func (m *CardWithOrig_Item) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *CardWithOrig_Item) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *CardWithOrig_Item) GetOrigType() DynamicDescType {
	if m != nil {
		return m.OrigType
	}
	return DynamicDescType_Unknown
}

type CardWithOrig_OriginUser struct {
	Info                 *CardWithOrig_OriginUser_Info `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *CardWithOrig_OriginUser) Reset()         { *m = CardWithOrig_OriginUser{} }
func (m *CardWithOrig_OriginUser) String() string { return proto.CompactTextString(m) }
func (*CardWithOrig_OriginUser) ProtoMessage()    {}
func (*CardWithOrig_OriginUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0021bc90478bd43, []int{5, 1}
}

func (m *CardWithOrig_OriginUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardWithOrig_OriginUser.Unmarshal(m, b)
}
func (m *CardWithOrig_OriginUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardWithOrig_OriginUser.Marshal(b, m, deterministic)
}
func (m *CardWithOrig_OriginUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardWithOrig_OriginUser.Merge(m, src)
}
func (m *CardWithOrig_OriginUser) XXX_Size() int {
	return xxx_messageInfo_CardWithOrig_OriginUser.Size(m)
}
func (m *CardWithOrig_OriginUser) XXX_DiscardUnknown() {
	xxx_messageInfo_CardWithOrig_OriginUser.DiscardUnknown(m)
}

var xxx_messageInfo_CardWithOrig_OriginUser proto.InternalMessageInfo

func (m *CardWithOrig_OriginUser) GetInfo() *CardWithOrig_OriginUser_Info {
	if m != nil {
		return m.Info
	}
	return nil
}

type CardWithOrig_OriginUser_Info struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Uname                string   `protobuf:"bytes,2,opt,name=uname,proto3" json:"uname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CardWithOrig_OriginUser_Info) Reset()         { *m = CardWithOrig_OriginUser_Info{} }
func (m *CardWithOrig_OriginUser_Info) String() string { return proto.CompactTextString(m) }
func (*CardWithOrig_OriginUser_Info) ProtoMessage()    {}
func (*CardWithOrig_OriginUser_Info) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0021bc90478bd43, []int{5, 1, 0}
}

func (m *CardWithOrig_OriginUser_Info) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardWithOrig_OriginUser_Info.Unmarshal(m, b)
}
func (m *CardWithOrig_OriginUser_Info) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardWithOrig_OriginUser_Info.Marshal(b, m, deterministic)
}
func (m *CardWithOrig_OriginUser_Info) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardWithOrig_OriginUser_Info.Merge(m, src)
}
func (m *CardWithOrig_OriginUser_Info) XXX_Size() int {
	return xxx_messageInfo_CardWithOrig_OriginUser_Info.Size(m)
}
func (m *CardWithOrig_OriginUser_Info) XXX_DiscardUnknown() {
	xxx_messageInfo_CardWithOrig_OriginUser_Info.DiscardUnknown(m)
}

var xxx_messageInfo_CardWithOrig_OriginUser_Info proto.InternalMessageInfo

func (m *CardWithOrig_OriginUser_Info) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *CardWithOrig_OriginUser_Info) GetUname() string {
	if m != nil {
		return m.Uname
	}
	return ""
}

type CardWithVideo struct {
	Desc                 string   `protobuf:"bytes,1,opt,name=desc,proto3" json:"desc,omitempty"`
	Duration             int32    `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
	Dynamic              string   `protobuf:"bytes,3,opt,name=dynamic,proto3" json:"dynamic,omitempty"`
	Pubdate              int64    `protobuf:"varint,4,opt,name=pubdate,proto3" json:"pubdate,omitempty"`
	Title                string   `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Tname                string   `protobuf:"bytes,6,opt,name=tname,proto3" json:"tname,omitempty"`
	Videos               int32    `protobuf:"varint,7,opt,name=videos,proto3" json:"videos,omitempty"`
	Pic                  string   `protobuf:"bytes,8,opt,name=pic,proto3" json:"pic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CardWithVideo) Reset()         { *m = CardWithVideo{} }
func (m *CardWithVideo) String() string { return proto.CompactTextString(m) }
func (*CardWithVideo) ProtoMessage()    {}
func (*CardWithVideo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0021bc90478bd43, []int{6}
}

func (m *CardWithVideo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardWithVideo.Unmarshal(m, b)
}
func (m *CardWithVideo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardWithVideo.Marshal(b, m, deterministic)
}
func (m *CardWithVideo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardWithVideo.Merge(m, src)
}
func (m *CardWithVideo) XXX_Size() int {
	return xxx_messageInfo_CardWithVideo.Size(m)
}
func (m *CardWithVideo) XXX_DiscardUnknown() {
	xxx_messageInfo_CardWithVideo.DiscardUnknown(m)
}

var xxx_messageInfo_CardWithVideo proto.InternalMessageInfo

func (m *CardWithVideo) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *CardWithVideo) GetDuration() int32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *CardWithVideo) GetDynamic() string {
	if m != nil {
		return m.Dynamic
	}
	return ""
}

func (m *CardWithVideo) GetPubdate() int64 {
	if m != nil {
		return m.Pubdate
	}
	return 0
}

func (m *CardWithVideo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CardWithVideo) GetTname() string {
	if m != nil {
		return m.Tname
	}
	return ""
}

func (m *CardWithVideo) GetVideos() int32 {
	if m != nil {
		return m.Videos
	}
	return 0
}

func (m *CardWithVideo) GetPic() string {
	if m != nil {
		return m.Pic
	}
	return ""
}

type CardTextOnly struct {
	Item                 *CardTextOnly_Item `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CardTextOnly) Reset()         { *m = CardTextOnly{} }
func (m *CardTextOnly) String() string { return proto.CompactTextString(m) }
func (*CardTextOnly) ProtoMessage()    {}
func (*CardTextOnly) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0021bc90478bd43, []int{7}
}

func (m *CardTextOnly) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardTextOnly.Unmarshal(m, b)
}
func (m *CardTextOnly) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardTextOnly.Marshal(b, m, deterministic)
}
func (m *CardTextOnly) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardTextOnly.Merge(m, src)
}
func (m *CardTextOnly) XXX_Size() int {
	return xxx_messageInfo_CardTextOnly.Size(m)
}
func (m *CardTextOnly) XXX_DiscardUnknown() {
	xxx_messageInfo_CardTextOnly.DiscardUnknown(m)
}

var xxx_messageInfo_CardTextOnly proto.InternalMessageInfo

func (m *CardTextOnly) GetItem() *CardTextOnly_Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type CardTextOnly_Item struct {
	RpId                 int64    `protobuf:"varint,1,opt,name=rp_id,json=rpId,proto3" json:"rp_id,omitempty"`
	Uid                  int64    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Ctrl                 string   `protobuf:"bytes,4,opt,name=ctrl,proto3" json:"ctrl,omitempty"`
	Timestamp            int64    `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Reply                int32    `protobuf:"varint,8,opt,name=reply,proto3" json:"reply,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CardTextOnly_Item) Reset()         { *m = CardTextOnly_Item{} }
func (m *CardTextOnly_Item) String() string { return proto.CompactTextString(m) }
func (*CardTextOnly_Item) ProtoMessage()    {}
func (*CardTextOnly_Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0021bc90478bd43, []int{7, 0}
}

func (m *CardTextOnly_Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardTextOnly_Item.Unmarshal(m, b)
}
func (m *CardTextOnly_Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardTextOnly_Item.Marshal(b, m, deterministic)
}
func (m *CardTextOnly_Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardTextOnly_Item.Merge(m, src)
}
func (m *CardTextOnly_Item) XXX_Size() int {
	return xxx_messageInfo_CardTextOnly_Item.Size(m)
}
func (m *CardTextOnly_Item) XXX_DiscardUnknown() {
	xxx_messageInfo_CardTextOnly_Item.DiscardUnknown(m)
}

var xxx_messageInfo_CardTextOnly_Item proto.InternalMessageInfo

func (m *CardTextOnly_Item) GetRpId() int64 {
	if m != nil {
		return m.RpId
	}
	return 0
}

func (m *CardTextOnly_Item) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *CardTextOnly_Item) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *CardTextOnly_Item) GetCtrl() string {
	if m != nil {
		return m.Ctrl
	}
	return ""
}

func (m *CardTextOnly_Item) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *CardTextOnly_Item) GetReply() int32 {
	if m != nil {
		return m.Reply
	}
	return 0
}

type CardWithPost struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Summary              string   `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	ImageUrls            []string `protobuf:"bytes,3,rep,name=image_urls,json=imageUrls,proto3" json:"image_urls,omitempty"`
	BannerUrl            string   `protobuf:"bytes,4,opt,name=banner_url,json=bannerUrl,proto3" json:"banner_url,omitempty"`
	PublishTime          int64    `protobuf:"varint,5,opt,name=publish_time,json=publishTime,proto3" json:"publish_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CardWithPost) Reset()         { *m = CardWithPost{} }
func (m *CardWithPost) String() string { return proto.CompactTextString(m) }
func (*CardWithPost) ProtoMessage()    {}
func (*CardWithPost) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0021bc90478bd43, []int{8}
}

func (m *CardWithPost) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardWithPost.Unmarshal(m, b)
}
func (m *CardWithPost) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardWithPost.Marshal(b, m, deterministic)
}
func (m *CardWithPost) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardWithPost.Merge(m, src)
}
func (m *CardWithPost) XXX_Size() int {
	return xxx_messageInfo_CardWithPost.Size(m)
}
func (m *CardWithPost) XXX_DiscardUnknown() {
	xxx_messageInfo_CardWithPost.DiscardUnknown(m)
}

var xxx_messageInfo_CardWithPost proto.InternalMessageInfo

func (m *CardWithPost) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CardWithPost) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *CardWithPost) GetImageUrls() []string {
	if m != nil {
		return m.ImageUrls
	}
	return nil
}

func (m *CardWithPost) GetBannerUrl() string {
	if m != nil {
		return m.BannerUrl
	}
	return ""
}

func (m *CardWithPost) GetPublishTime() int64 {
	if m != nil {
		return m.PublishTime
	}
	return 0
}

func init() {
	proto.RegisterEnum("bilibili.LiveStatus", LiveStatus_name, LiveStatus_value)
	proto.RegisterEnum("bilibili.RoundStatus", RoundStatus_name, RoundStatus_value)
	proto.RegisterEnum("bilibili.RoomStatus", RoomStatus_name, RoomStatus_value)
	proto.RegisterEnum("bilibili.SpecialType", SpecialType_name, SpecialType_value)
	proto.RegisterEnum("bilibili.DynamicDescType", DynamicDescType_name, DynamicDescType_value)
	proto.RegisterType((*RoomInitResponse)(nil), "bilibili.RoomInitResponse")
	proto.RegisterType((*RoomInitResponse_Data)(nil), "bilibili.RoomInitResponse.Data")
	proto.RegisterType((*XSpaceAccInfoResponse)(nil), "bilibili.XSpaceAccInfoResponse")
	proto.RegisterType((*XSpaceAccInfoResponse_Data)(nil), "bilibili.XSpaceAccInfoResponse.Data")
	proto.RegisterType((*XSpaceAccInfoResponse_Data_LiveRoom)(nil), "bilibili.XSpaceAccInfoResponse.Data.LiveRoom")
	proto.RegisterType((*GetRoomInfoOldResponse)(nil), "bilibili.GetRoomInfoOldResponse")
	proto.RegisterType((*GetRoomInfoOldResponse_Data)(nil), "bilibili.GetRoomInfoOldResponse.Data")
	proto.RegisterType((*DynamicSvrSpaceHistoryResponse)(nil), "bilibili.DynamicSvrSpaceHistoryResponse")
	proto.RegisterType((*DynamicSvrSpaceHistoryResponse_Data)(nil), "bilibili.DynamicSvrSpaceHistoryResponse.Data")
	proto.RegisterType((*DynamicSvrSpaceHistoryResponse_Data_Card)(nil), "bilibili.DynamicSvrSpaceHistoryResponse.Data.Card")
	proto.RegisterType((*DynamicSvrSpaceHistoryResponse_Data_Card_Desc)(nil), "bilibili.DynamicSvrSpaceHistoryResponse.Data.Card.Desc")
	proto.RegisterType((*DynamicSvrSpaceHistoryResponse_Data_Card_Extra)(nil), "bilibili.DynamicSvrSpaceHistoryResponse.Data.Card.Extra")
	proto.RegisterType((*DynamicSvrSpaceHistoryResponse_Data_Card_Display)(nil), "bilibili.DynamicSvrSpaceHistoryResponse.Data.Card.Display")
	proto.RegisterType((*DynamicSvrSpaceHistoryResponse_Data_Card_Display_EmojiInfo)(nil), "bilibili.DynamicSvrSpaceHistoryResponse.Data.Card.Display.EmojiInfo")
	proto.RegisterType((*DynamicSvrSpaceHistoryResponse_Data_Card_Display_EmojiInfo_EmojiDetail)(nil), "bilibili.DynamicSvrSpaceHistoryResponse.Data.Card.Display.EmojiInfo.EmojiDetail")
	proto.RegisterType((*DynamicSvrSpaceHistoryResponse_Data_Card_Display_Origin)(nil), "bilibili.DynamicSvrSpaceHistoryResponse.Data.Card.Display.Origin")
	proto.RegisterType((*CardWithImage)(nil), "bilibili.CardWithImage")
	proto.RegisterType((*CardWithImage_Item)(nil), "bilibili.CardWithImage.Item")
	proto.RegisterType((*CardWithImage_Item_Picture)(nil), "bilibili.CardWithImage.Item.Picture")
	proto.RegisterType((*CardWithOrig)(nil), "bilibili.CardWithOrig")
	proto.RegisterType((*CardWithOrig_Item)(nil), "bilibili.CardWithOrig.Item")
	proto.RegisterType((*CardWithOrig_OriginUser)(nil), "bilibili.CardWithOrig.OriginUser")
	proto.RegisterType((*CardWithOrig_OriginUser_Info)(nil), "bilibili.CardWithOrig.OriginUser.Info")
	proto.RegisterType((*CardWithVideo)(nil), "bilibili.CardWithVideo")
	proto.RegisterType((*CardTextOnly)(nil), "bilibili.CardTextOnly")
	proto.RegisterType((*CardTextOnly_Item)(nil), "bilibili.CardTextOnly.Item")
	proto.RegisterType((*CardWithPost)(nil), "bilibili.CardWithPost")
}

func init() {
	proto.RegisterFile("bilibili.proto", fileDescriptor_d0021bc90478bd43)
}

var fileDescriptor_d0021bc90478bd43 = []byte{
	// 1829 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x58, 0x4f, 0x6f, 0x24, 0x47,
	0x15, 0x77, 0xcf, 0x4c, 0x7b, 0xa6, 0x5f, 0x8f, 0x9d, 0xa6, 0xb2, 0x09, 0x93, 0xc9, 0xb2, 0x71,
	0xcc, 0x6e, 0x64, 0x2c, 0x65, 0x40, 0x4e, 0x20, 0x21, 0xa7, 0x6c, 0xe2, 0x85, 0x35, 0x6c, 0xd6,
	0xab, 0xb6, 0x97, 0x10, 0x2e, 0xad, 0x76, 0x77, 0x79, 0x5c, 0x6c, 0x77, 0x57, 0xab, 0xba, 0x66,
	0xd6, 0x93, 0x13, 0x5f, 0x00, 0xf1, 0x11, 0x10, 0x67, 0x2e, 0x91, 0xf8, 0x06, 0x88, 0x0b, 0x47,
	0x84, 0xf8, 0x08, 0x1c, 0x10, 0x42, 0x9c, 0x90, 0x38, 0xa2, 0xf7, 0xaa, 0xfa, 0xcf, 0xec, 0x6e,
	0x36, 0x89, 0x41, 0x1c, 0x46, 0x7a, 0x7f, 0xaa, 0x5f, 0x55, 0xbd, 0xf7, 0x7b, 0x7f, 0x6a, 0x60,
	0xfb, 0x4c, 0x64, 0x02, 0x7f, 0xb3, 0x52, 0x49, 0x2d, 0xd9, 0xa8, 0xe6, 0x77, 0xff, 0xd1, 0x83,
	0x20, 0x94, 0x32, 0x3f, 0x2a, 0x84, 0x0e, 0x79, 0x55, 0xca, 0xa2, 0xe2, 0x8c, 0xc1, 0x20, 0x91,
	0x29, 0x9f, 0x38, 0x3b, 0xce, 0x9e, 0x1b, 0x12, 0xcd, 0x26, 0x30, 0xcc, 0x79, 0x55, 0xc5, 0x73,
	0x3e, 0xe9, 0xed, 0x38, 0x7b, 0x5e, 0x58, 0xb3, 0xec, 0x2d, 0x18, 0xa4, 0xb1, 0x8e, 0x27, 0xfd,
	0x1d, 0x67, 0xcf, 0x3f, 0x78, 0x6d, 0xd6, 0xec, 0xf5, 0xa4, 0xdd, 0xd9, 0x61, 0xac, 0xe3, 0x90,
	0x16, 0x4f, 0xff, 0xe5, 0xc0, 0x00, 0x59, 0xf6, 0x75, 0x18, 0x2a, 0x29, 0xf3, 0x48, 0xa4, 0xb4,
	0x5d, 0x3f, 0xdc, 0x44, 0xf6, 0x28, 0x65, 0xaf, 0xc0, 0xa8, 0xba, 0x90, 0x4a, 0xa3, 0xa6, 0x47,
	0x9a, 0x21, 0xf1, 0x47, 0x29, 0x0b, 0xa0, 0xbf, 0x10, 0x29, 0x6d, 0xd8, 0x0f, 0x91, 0x64, 0xaf,
	0x82, 0x27, 0xaa, 0xe8, 0x42, 0xa4, 0x29, 0x2f, 0x26, 0xee, 0x8e, 0xb3, 0x37, 0x0a, 0x47, 0xa2,
	0xba, 0x4b, 0xbc, 0x55, 0x66, 0x32, 0x79, 0xc4, 0xd3, 0xc9, 0x66, 0xad, 0xbc, 0x47, 0x3c, 0xfb,
	0x2e, 0xf8, 0x99, 0x58, 0xf2, 0xa8, 0xd2, 0xb1, 0x5e, 0x54, 0x93, 0xd1, 0x8e, 0xb3, 0xb7, 0x7d,
	0x70, 0xad, 0xbd, 0xc4, 0x3d, 0xb1, 0xe4, 0x27, 0xa4, 0x0b, 0x21, 0x6b, 0x68, 0xf6, 0x22, 0xb8,
	0xa2, 0x8a, 0xaa, 0x72, 0xf2, 0x82, 0xf1, 0x91, 0xa8, 0x4e, 0x4a, 0xf6, 0x3a, 0x8c, 0xab, 0x92,
	0x27, 0x22, 0xce, 0x22, 0xbd, 0x2a, 0xf9, 0x24, 0x20, 0x9d, 0x6f, 0x65, 0xa7, 0xab, 0x92, 0xef,
	0xfe, 0xa5, 0x0f, 0x2f, 0xfd, 0xf4, 0xa4, 0x8c, 0x13, 0x7e, 0x3b, 0x49, 0x8e, 0x8a, 0x73, 0x79,
	0x45, 0xa7, 0xbf, 0xbb, 0xe6, 0xf4, 0x9b, 0xed, 0x79, 0x9f, 0x69, 0xbc, 0xeb, 0xf9, 0x3f, 0xf7,
	0xac, 0xe7, 0x03, 0xe8, 0xe7, 0x8d, 0xd7, 0x91, 0xc4, 0x23, 0x14, 0x71, 0x5e, 0xef, 0x45, 0x34,
	0xbb, 0x06, 0x6e, 0xc6, 0x97, 0x3c, 0x9b, 0x0c, 0xe9, 0x5c, 0x86, 0x61, 0x3f, 0x02, 0x8f, 0xbc,
	0x86, 0xb1, 0x9a, 0x7c, 0x8d, 0xce, 0xf0, 0xe6, 0x97, 0x39, 0x03, 0xb9, 0x13, 0x71, 0x11, 0x8e,
	0x32, 0x4b, 0x4d, 0x7f, 0xef, 0xc0, 0xa8, 0x16, 0xb3, 0x1b, 0x00, 0x68, 0xd3, 0x78, 0xd9, 0xfa,
	0xa2, 0x23, 0x41, 0x7d, 0x1b, 0x05, 0x3a, 0xa8, 0xbb, 0x16, 0x17, 0x84, 0x86, 0xca, 0xc8, 0x2d,
	0x5e, 0x88, 0x24, 0x5e, 0x40, 0x0b, 0x9d, 0xf1, 0xc9, 0x80, 0x64, 0x86, 0x41, 0x69, 0x22, 0x97,
	0x5c, 0x11, 0x58, 0xbc, 0xd0, 0x30, 0xec, 0x65, 0x20, 0xf4, 0x09, 0x03, 0x13, 0x8b, 0x45, 0x91,
	0xb2, 0x1d, 0xf0, 0x95, 0x5c, 0x14, 0xa9, 0xdd, 0xd6, 0xb8, 0xa2, 0x2b, 0xda, 0xfd, 0x5b, 0x1f,
	0x5e, 0xfe, 0x21, 0xd7, 0x06, 0xf2, 0xe7, 0xf2, 0x38, 0x4b, 0xaf, 0x18, 0xd8, 0xef, 0xaf, 0x05,
	0xf6, 0x56, 0xeb, 0xd4, 0x67, 0x5b, 0xef, 0x46, 0xf6, 0xaf, 0x75, 0x64, 0xdf, 0x7e, 0xca, 0x89,
	0x6b, 0x90, 0x0e, 0x1b, 0xdd, 0x9a, 0x6b, 0xdf, 0x59, 0xbf, 0x64, 0x8f, 0x3e, 0x7b, 0xa9, 0xfb,
	0x59, 0xa3, 0x5c, 0xbb, 0x3b, 0x6e, 0xd7, 0x89, 0x49, 0xff, 0x4b, 0x66, 0x90, 0x8d, 0xd4, 0xe0,
	0x19, 0x91, 0x72, 0x9f, 0x19, 0xa9, 0xcd, 0x27, 0x22, 0x25, 0x8b, 0x4c, 0x14, 0x9c, 0x82, 0xd1,
	0x0f, 0x2d, 0xd7, 0x89, 0xe0, 0x68, 0x2d, 0x82, 0xb7, 0x60, 0xfb, 0x4c, 0xc9, 0x38, 0x4d, 0xe2,
	0x4a, 0x9b, 0xe4, 0xf4, 0x28, 0x1c, 0x5b, 0x8d, 0x14, 0xd3, 0x93, 0x7d, 0x13, 0xb6, 0x8c, 0xa1,
	0xba, 0x96, 0x00, 0xad, 0x1a, 0x1b, 0xa1, 0xa9, 0x27, 0xbb, 0x7f, 0x18, 0xc3, 0x8d, 0xc3, 0x55,
	0x11, 0xe7, 0x22, 0x39, 0x59, 0x2a, 0xc2, 0xfa, 0x5d, 0x51, 0x69, 0xa9, 0x56, 0x57, 0x8c, 0xf9,
	0xed, 0xb5, 0x98, 0x77, 0x12, 0xe9, 0xf9, 0xbb, 0x74, 0x63, 0xff, 0x99, 0x6f, 0x63, 0x7f, 0x17,
	0xdc, 0x24, 0x56, 0x29, 0x86, 0xbd, 0xbf, 0xe7, 0x1f, 0x1c, 0x7c, 0x25, 0x63, 0xb3, 0x0f, 0x63,
	0x95, 0x86, 0xc6, 0x00, 0x16, 0xe0, 0x8b, 0xb8, 0x8a, 0x72, 0xa9, 0xb8, 0x4d, 0xb4, 0xe1, 0x45,
	0x5c, 0x7d, 0x24, 0x15, 0x67, 0xaf, 0x81, 0x5f, 0xf0, 0x4b, 0x1d, 0xc9, 0xf3, 0xf3, 0x8a, 0x6b,
	0x5b, 0x88, 0x01, 0x45, 0xc7, 0x24, 0x99, 0xfe, 0x06, 0x60, 0x80, 0xb6, 0xc8, 0x11, 0xb1, 0x32,
	0x55, 0xc6, 0x0b, 0x89, 0x66, 0x3f, 0x86, 0x41, 0xca, 0xab, 0x84, 0x8c, 0xfa, 0x07, 0xef, 0x7c,
	0xf5, 0x13, 0xce, 0x0e, 0x79, 0x95, 0x84, 0x64, 0x84, 0xdd, 0x07, 0x97, 0x5f, 0x6a, 0x15, 0x13,
	0x68, 0xfc, 0x83, 0x77, 0xaf, 0x60, 0xed, 0x0e, 0x7e, 0x1f, 0x1a, 0x33, 0xec, 0x14, 0x86, 0xa9,
	0xa8, 0xca, 0x2c, 0x5e, 0x11, 0xe0, 0xfc, 0x83, 0xf7, 0xae, 0x72, 0x3e, 0x63, 0x21, 0xac, 0x4d,
	0x4d, 0xff, 0x8d, 0xa9, 0x89, 0xc7, 0xfd, 0x06, 0x40, 0x6a, 0xac, 0xb4, 0x1d, 0xcf, 0xb3, 0x92,
	0xa3, 0x94, 0x5d, 0x07, 0x90, 0x4a, 0xcc, 0xa3, 0x74, 0xd5, 0xb6, 0xbd, 0x11, 0x4a, 0x0e, 0x57,
	0x47, 0x29, 0xfb, 0x1e, 0x78, 0xa4, 0x25, 0xfc, 0x9a, 0x3c, 0x7b, 0xe5, 0xa9, 0xd3, 0xe1, 0x36,
	0x88, 0x65, 0xf3, 0x1d, 0xa1, 0x7a, 0x0a, 0x5e, 0xa9, 0xb8, 0x35, 0x3a, 0x30, 0xbd, 0xb4, 0x54,
	0x9c, 0x6c, 0x4e, 0x60, 0x98, 0xc8, 0x3c, 0xe7, 0x85, 0x26, 0x0f, 0xba, 0x61, 0xcd, 0x62, 0xe8,
	0x32, 0xf1, 0x88, 0x93, 0x1b, 0xdc, 0x90, 0x68, 0x94, 0x2d, 0x05, 0x7f, 0x6c, 0x2b, 0x20, 0xd1,
	0x94, 0x72, 0xbc, 0x94, 0x95, 0xa6, 0x94, 0x73, 0x43, 0xcb, 0xb1, 0xeb, 0xe0, 0x69, 0x91, 0xf3,
	0x4a, 0xc7, 0x79, 0x69, 0xb3, 0xad, 0x15, 0xb0, 0x37, 0x61, 0x40, 0xd7, 0x80, 0x2f, 0xba, 0x06,
	0x2d, 0xc3, 0x8d, 0xcf, 0x96, 0x22, 0x9d, 0xf8, 0x06, 0x47, 0x48, 0xb3, 0x9b, 0xb0, 0xdd, 0xfa,
	0x32, 0xaa, 0xb4, 0x9a, 0x8c, 0x49, 0x3b, 0x6e, 0xfc, 0x79, 0xa2, 0xd5, 0xf4, 0x5b, 0xe0, 0x52,
	0x80, 0xd9, 0x0e, 0x8c, 0xa9, 0x65, 0xc7, 0x09, 0x8f, 0xb4, 0x2c, 0xeb, 0xe6, 0x82, 0x9d, 0x3b,
	0x4e, 0xf8, 0xa9, 0x2c, 0xa7, 0x7f, 0x1f, 0xc0, 0xd0, 0x86, 0x8e, 0x25, 0x00, 0x3c, 0x97, 0x3f,
	0x17, 0x91, 0x28, 0xce, 0x25, 0xad, 0xf5, 0x0f, 0x0e, 0xaf, 0x0e, 0x85, 0xd9, 0x1d, 0x34, 0x46,
	0xfd, 0xd0, 0xe3, 0x35, 0xc9, 0x3e, 0x81, 0x4d, 0x0c, 0x92, 0x28, 0x6c, 0x2e, 0xdc, 0xfe, 0x2f,
	0x36, 0x38, 0x26, 0x43, 0xa1, 0x35, 0x38, 0xfd, 0xac, 0x07, 0x5e, 0xb3, 0x27, 0x5b, 0xc0, 0x96,
	0xb9, 0x4d, 0xca, 0x75, 0x2c, 0xb2, 0xba, 0x3a, 0x3c, 0xf8, 0x5f, 0x5c, 0xc8, 0x50, 0x87, 0x64,
	0x38, 0x1c, 0xf3, 0x96, 0xa9, 0xa6, 0xbf, 0x75, 0xc0, 0xef, 0x68, 0x11, 0xfd, 0xe6, 0x18, 0x34,
	0x66, 0x98, 0x9a, 0x60, 0xdc, 0x71, 0x1f, 0x67, 0x8d, 0x6d, 0xe8, 0x59, 0xd4, 0xbb, 0x61, 0x4f,
	0xa4, 0xb8, 0xbc, 0x8c, 0x93, 0x47, 0xf1, 0x9c, 0x47, 0x76, 0xdc, 0x73, 0x43, 0xcf, 0x4a, 0x8e,
	0x52, 0xec, 0x0c, 0x38, 0xb5, 0x99, 0xce, 0xee, 0x86, 0x86, 0x41, 0xa4, 0x10, 0xb0, 0x0c, 0x9a,
	0x1b, 0xf4, 0x68, 0x7e, 0xa9, 0x6d, 0x0b, 0x21, 0xba, 0xee, 0x3f, 0xc3, 0xa6, 0xff, 0x4c, 0x73,
	0xd8, 0x34, 0x4e, 0xfc, 0xbf, 0x04, 0x7f, 0xf7, 0x77, 0x7d, 0xd8, 0xc2, 0x55, 0x1f, 0x0b, 0x7d,
	0x71, 0x94, 0x63, 0x1f, 0xf8, 0x0e, 0x0c, 0x84, 0xe6, 0xb9, 0xdd, 0xf0, 0x7a, 0xbb, 0xe1, 0xda,
	0xb2, 0xd9, 0x91, 0xe6, 0x79, 0x48, 0x2b, 0xa7, 0xff, 0xec, 0xc1, 0x00, 0x59, 0xeb, 0x3a, 0x53,
	0x4f, 0xd0, 0x75, 0x4d, 0x2f, 0xed, 0x75, 0x7b, 0xe9, 0x0e, 0xf8, 0x58, 0x34, 0x95, 0x28, 0xb5,
	0x90, 0x85, 0x9d, 0x92, 0xba, 0x22, 0x36, 0x85, 0x51, 0x12, 0x6b, 0x3e, 0x97, 0x6a, 0x65, 0x5b,
	0x73, 0xc3, 0xb3, 0xf7, 0x61, 0x54, 0x8a, 0x44, 0x2f, 0x14, 0xaf, 0x26, 0x2e, 0xe1, 0xe7, 0xe6,
	0xf3, 0x8e, 0x38, 0x7b, 0x60, 0x16, 0x87, 0xcd, 0x57, 0xd8, 0x85, 0x6b, 0x3a, 0x4a, 0xe4, 0xa2,
	0xd0, 0xb6, 0xb8, 0x6c, 0xd5, 0xd2, 0x0f, 0x51, 0x88, 0xed, 0x65, 0x51, 0x66, 0x32, 0x4e, 0x23,
	0xac, 0x17, 0xb6, 0xc3, 0x83, 0x11, 0x9d, 0x8a, 0x9c, 0x4f, 0x57, 0x30, 0xb4, 0xc6, 0xf1, 0xfd,
	0x20, 0xf2, 0x79, 0x54, 0xa9, 0xc4, 0xe2, 0x69, 0x53, 0xe4, 0xf3, 0x13, 0x95, 0xd0, 0xd4, 0x9f,
	0xcf, 0xa3, 0xc7, 0x22, 0xd5, 0x17, 0x16, 0x53, 0x23, 0x91, 0xcf, 0x3f, 0x46, 0x1e, 0x91, 0x85,
	0xca, 0x0b, 0x2e, 0xe6, 0x17, 0xba, 0x46, 0x96, 0xc8, 0xe7, 0x77, 0x49, 0x80, 0xad, 0x8f, 0x8c,
	0x8a, 0x4f, 0x0d, 0xb8, 0x7a, 0x21, 0x6e, 0x72, 0x22, 0x3e, 0xe5, 0xbb, 0xbf, 0xec, 0xc3, 0xb8,
	0xbe, 0x2b, 0xa2, 0x85, 0x7d, 0x7b, 0x2d, 0x68, 0xaf, 0x3e, 0xed, 0x11, 0x5c, 0xd5, 0x89, 0x19,
	0x8d, 0x2e, 0x6d, 0xd2, 0x7b, 0x75, 0xc6, 0xb2, 0x0f, 0xc0, 0x37, 0x54, 0xb4, 0xa8, 0xb8, 0xb2,
	0xc3, 0xc0, 0xeb, 0x9f, 0x63, 0xcf, 0x00, 0xf5, 0x61, 0xc5, 0x55, 0x08, 0xb2, 0xa1, 0xa7, 0x4b,
	0x0b, 0x07, 0xaa, 0xea, 0x85, 0xc6, 0xaa, 0x6e, 0xbc, 0x52, 0xb3, 0xeb, 0x55, 0xd9, 0x34, 0x98,
	0x4e, 0x55, 0xbe, 0x62, 0x87, 0x99, 0x5e, 0x02, 0xb4, 0x27, 0x62, 0xef, 0xc1, 0xa0, 0x93, 0x38,
	0x6f, 0x7c, 0xe1, 0x15, 0x66, 0x94, 0x1a, 0xf4, 0xcd, 0x74, 0x06, 0x03, 0xaa, 0x58, 0xf6, 0x8d,
	0xe7, 0xb4, 0x6f, 0xbc, 0x6b, 0xe0, 0x2e, 0x3a, 0xcf, 0x13, 0xc3, 0xec, 0xfe, 0xd1, 0x69, 0xb3,
	0xe8, 0x27, 0x22, 0xe5, 0x12, 0x93, 0x9d, 0xc6, 0x0b, 0x3b, 0x72, 0xd0, 0x94, 0x30, 0x85, 0x51,
	0xba, 0x50, 0x31, 0xa1, 0xde, 0x62, 0xa1, 0xe6, 0xd1, 0x57, 0xb6, 0x61, 0xd8, 0x84, 0xa8, 0x59,
	0xd4, 0x94, 0x8b, 0xb3, 0xb4, 0x2e, 0x31, 0xd8, 0x35, 0x0d, 0xfb, 0xf9, 0xa3, 0xaa, 0xa6, 0x13,
	0xda, 0x51, 0x95, 0x18, 0x8c, 0xf7, 0x12, 0x0f, 0x56, 0xbf, 0x1b, 0x2c, 0x87, 0x37, 0x2c, 0x45,
	0x42, 0x4d, 0xd3, 0x0b, 0x91, 0xdc, 0xfd, 0x93, 0x63, 0xb0, 0x75, 0x8a, 0x83, 0x54, 0x91, 0xad,
	0x9e, 0x8f, 0xad, 0x7a, 0x55, 0xb7, 0x1e, 0xfc, 0xca, 0xb1, 0x00, 0x78, 0x11, 0x5c, 0x55, 0xb6,
	0x23, 0xc6, 0x40, 0x95, 0xed, 0xbb, 0xb9, 0xd7, 0xfa, 0xb4, 0x83, 0x93, 0xfe, 0x3a, 0x4e, 0x70,
	0x70, 0xd3, 0xcd, 0x7c, 0x4e, 0xf4, 0x3a, 0x76, 0x86, 0x4f, 0x62, 0xe7, 0x1a, 0xb8, 0x8a, 0x97,
	0xd9, 0xca, 0x8e, 0x01, 0x86, 0xd9, 0xfd, 0xb5, 0xd3, 0xe6, 0xcb, 0x03, 0x1c, 0x0b, 0x1a, 0xd7,
	0x39, 0x5d, 0xd7, 0x4d, 0x60, 0x58, 0x2d, 0xf2, 0x3c, 0x56, 0xab, 0x7a, 0x38, 0xb6, 0xac, 0x49,
	0x55, 0x6c, 0x01, 0x0b, 0x95, 0xe1, 0xeb, 0xa2, 0x8f, 0x3d, 0x83, 0x24, 0x0f, 0x55, 0x56, 0xa1,
	0xfa, 0x2c, 0x2e, 0x0a, 0xae, 0xa2, 0xf6, 0x35, 0xe1, 0x19, 0xc9, 0x43, 0x95, 0xe1, 0x93, 0xbc,
	0x5c, 0x9c, 0x65, 0xa2, 0xba, 0x30, 0xb5, 0xc4, 0xa5, 0x53, 0xfb, 0x56, 0x86, 0xc5, 0x64, 0xff,
	0x0d, 0x80, 0xf6, 0x89, 0xc2, 0xc6, 0x30, 0xba, 0x2f, 0xef, 0x89, 0xa5, 0x28, 0xe6, 0xc1, 0x06,
	0x03, 0xd8, 0xb4, 0xb4, 0xb3, 0x7f, 0x03, 0xfc, 0xce, 0x13, 0x88, 0x0d, 0xa1, 0x7f, 0x7c, 0x7e,
	0x1e, 0x6c, 0xb0, 0x4d, 0xe8, 0x1d, 0x17, 0x81, 0xb3, 0x7f, 0x0b, 0xa0, 0x7d, 0x59, 0x19, 0x3b,
	0xc5, 0x9d, 0x4b, 0x51, 0xe9, 0x60, 0x83, 0x79, 0x38, 0x84, 0x20, 0xe9, 0xec, 0xbf, 0x0d, 0xfe,
	0x49, 0xfb, 0x87, 0x00, 0xee, 0x70, 0x5f, 0xaa, 0x3c, 0xce, 0x82, 0x0d, 0x34, 0xf9, 0x20, 0x5e,
	0x05, 0x0e, 0x0b, 0x60, 0xfc, 0x09, 0x8f, 0xd5, 0x0f, 0x78, 0xa5, 0xc5, 0x32, 0xce, 0x82, 0xde,
	0xfe, 0x25, 0xbc, 0xf0, 0x44, 0xf6, 0x31, 0x1f, 0x86, 0x0f, 0x8b, 0x47, 0x85, 0x7c, 0x5c, 0x04,
	0x1b, 0x6c, 0x1b, 0xa0, 0x4e, 0x2c, 0x51, 0x04, 0x0e, 0xdb, 0x02, 0xaf, 0xa9, 0xc6, 0x41, 0x0f,
	0x4f, 0x53, 0xc3, 0x25, 0x18, 0xd4, 0x4a, 0x4a, 0x97, 0x60, 0x84, 0xca, 0x3a, 0x3a, 0xc1, 0xfb,
	0x6c, 0xdb, 0x28, 0x3f, 0x5a, 0x54, 0x22, 0x09, 0x7e, 0xd1, 0xfb, 0x00, 0x7e, 0xd6, 0xfc, 0x5b,
	0x74, 0xb6, 0x49, 0x7f, 0x1f, 0xbd, 0xf5, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x35, 0x61, 0xa1,
	0x05, 0x50, 0x12, 0x00, 0x00,
}
